// src/components/Dropdown/Dropdown.vue
<template>
  <div
    ref="dropdownRef"
    :class="['wc-dropdown', { 'dark': isDarkMode }]"
    :style="{ backgroundColor: 'var(--wc-bg-surface)', color: 'var(--wc-text-primary)' }"
  >
    <div
      ref="triggerRef"
      class="wc-dropdown__trigger"
      @click="handleToggle"
    >
      <slot name="trigger">
        <button class="wc-dropdown__button">
          {{ triggerText }}
          <span :class="['wc-dropdown__arrow', { 'wc-dropdown__arrow--open': isOpen }]">
            ▼
          </span>
        </button>
      </slot>
    </div>

    <Transition name="dropdown">
      <div
        v-if="isOpen"
        ref="menuRef"
        :class="dropdownClasses"
        :style="dropdownStyles"
      >
        <slot name="content">
          <div v-if="variant === 'card'" class="wc-dropdown__card">
            <!-- 左侧示意图区域 -->
            <div class="wc-dropdown__card-illustration">
              <slot name="illustration">
                <img 
                  v-if="illustration" 
                  :src="illustration" 
                  :alt="illustrationAlt"
                  class="wc-dropdown__illustration-image"
                />
                <div v-else class="wc-dropdown__illustration-placeholder">
                  <span>🎨</span>
                </div>
              </slot>
              <div v-if="cardTitle || cardDescription" class="wc-dropdown__card-info">
                <h4 v-if="cardTitle" class="wc-dropdown__card-title">{{ cardTitle }}</h4>
                <p v-if="cardDescription" class="wc-dropdown__card-description">{{ cardDescription }}</p>
              </div>
            </div>
            
            <!-- 右侧列表区域 -->
            <div class="wc-dropdown__card-list">
              <div
                v-for="(item, index) in items"
                :key="item.key || index"
                :class="[
                  item.divider ? 'wc-dropdown__divider' : 'wc-dropdown__item',
                  {
                    'wc-dropdown__item--disabled': item.disabled && !item.divider
                  }
                ]"
                @click="handleItemClick(item, index)"
              >
                <span
                  v-if="item.icon"
                  class="wc-dropdown__icon"
                >{{ item.icon }}</span>
                <span class="wc-dropdown__label">{{ item.label }}</span>
              </div>
            </div>
          </div>
          
          <!-- 默认样式 -->
          <div v-else>
            <div
              v-for="(item, index) in items"
              :key="item.key || index"
              :class="[
                item.divider ? 'wc-dropdown__divider' : 'wc-dropdown__item',
                {
                  'wc-dropdown__item--disabled': item.disabled && !item.divider
                }
              ]"
              @click="handleItemClick(item, index)"
            >
              <span
                v-if="item.icon"
                class="wc-dropdown__icon"
              >{{ item.icon }}</span>
              <span class="wc-dropdown__label">{{ item.label }}</span>
            </div>
          </div>
        </slot>
      </div>
    </Transition>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import './style.css'

const props = defineProps({
  items: {
    type: Array,
    default: () => []
  },
  triggerText: {
    type: String,
    default: '选择选项'
  },
  placement: {
    type: String,
    default: 'bottom-start',
    validator: (value) => ['bottom-start', 'bottom-end', 'top-start', 'top-end'].includes(value)
  },
  disabled: {
    type: Boolean,
    default: false
  },
  trigger: {
    type: String,
    default: 'click',
    validator: (value) => ['click', 'hover'].includes(value)
  },
  variant: {
    type: String,
    default: 'default',
    validator: (value) => ['default', 'card'].includes(value)
  },
  illustration: {
    type: String,
    default: ''
  },
  illustrationAlt: {
    type: String,
    default: '示意图'
  },
  cardTitle: {
    type: String,
    default: ''
  },
  cardDescription: {
    type: String,
    default: ''
  },
  isDarkMode: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['select', 'open', 'close'])

const isOpen = ref(false)
const dropdownRef = ref(null)
const triggerRef = ref(null)
const menuRef = ref(null)

const dropdownClasses = computed(() => {
  const classes = ['wc-dropdown__menu', `wc-dropdown__menu--${props.placement}`]
  if (props.variant === 'card') {
    classes.push('wc-dropdown__menu--card')
  }
  return classes
})

const dropdownStyles = computed(() => {
  if (props.variant === 'card') {
    return {
      minWidth: '320px',
      maxWidth: '450px'
    }
  }
  return {
    minWidth: '120px'
  }
})

const handleToggle = () => {
  if (props.disabled) return
  
  isOpen.value = !isOpen.value
  
  if (isOpen.value) {
    emit('open')
  } else {
    emit('close')
  }
}

const handleItemClick = (item, index) => {
  if (item.disabled || item.divider) return
  
  emit('select', item, index)
  isOpen.value = false
  emit('close')
}

const handleClickOutside = (event) => {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target)) {
    isOpen.value = false
    emit('close')
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

// src/components/Dropdown/Dropdown.jsx
import React, { useState, useRef, useEffect } from 'react'
import './style.css'
import { 
  getDropdownClasses,
  getDropdownMenuClasses,
  getDropdownButtonClasses,
  getDropdownItemClasses,
  getArrowClasses,
  handleDropdownToggle,
  handleItemClick,
  createOutsideClickListener
} from './utils.js'

const Dropdown = ({
  items = [],
  triggerText = '选择选项',
  placement = 'bottom-start',
  size = 'md',
  variant = 'default',
  disabled = false,
  trigger = 'click',
  illustration = '',
  illustrationAlt = '示意图',
  cardTitle = '',
  cardDescription = '',
  onSelect,
  onOpen,
  onClose,
  children,
  triggerContent,
  dropdownContent,
  className = '',
  ...props
}) => {
  const [isOpen, setIsOpen] = useState(false)
  const dropdownRef = useRef(null)
  const triggerRef = useRef(null)

  const dropdownClasses = getDropdownClasses({ size, variant, disabled, className }).join(' ')
  const menuClasses = getDropdownMenuClasses(placement, variant === 'card' ? 'wc-dropdown__menu--card' : '').join(' ')
  const buttonClasses = getDropdownButtonClasses({ disabled }).join(' ')
  const arrowClasses = getArrowClasses(isOpen).join(' ')

  const menuStyles = variant === 'card' ? { minWidth: '320px', maxWidth: '450px' } : { minWidth: '120px' }

  const handleToggle = () => {
    handleDropdownToggle(isOpen, disabled, setIsOpen, onOpen, onClose)
  }

  const handleItemSelect = (item, index) => {
    handleItemClick(item, index, onSelect, setIsOpen, onClose)
  }

  const outsideClickListener = createOutsideClickListener((event) => {
    if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
      setIsOpen(false)
      onClose && onClose()
    }
  })

  useEffect(() => {
    if (isOpen) {
      outsideClickListener.add()
    } else {
      outsideClickListener.remove()
    }
    
    return () => outsideClickListener.remove()
  }, [isOpen])

  return (
    <div className={dropdownClasses} ref={dropdownRef} {...props} style={{ backgroundColor: 'var(--wc-bg-surface)', color: 'var(--wc-text-primary)' }}>
      <div
        className="wc-dropdown__trigger"
        onClick={handleToggle}
        ref={triggerRef}
      >
        {triggerContent || children || (
          <button className={buttonClasses}>
            {triggerText}
            <span className={arrowClasses}>▼</span>
          </button>
        )}
      </div>

      {isOpen && (
        <div className={menuClasses} style={menuStyles}>
          {dropdownContent || (
            variant === 'card' ? (
              <div className="wc-dropdown__card">
                {/* 左侧示意图区域 */}
                <div className="wc-dropdown__card-illustration">
                  {illustration ? (
                    <img 
                      src={illustration}
                      alt={illustrationAlt}
                      className="wc-dropdown__illustration-image"
                    />
                  ) : (
                    <div className="wc-dropdown__illustration-placeholder">
                      <span>🎨</span>
                    </div>
                  )}
                  {(cardTitle || cardDescription) && (
                    <div className="wc-dropdown__card-info">
                      {cardTitle && <h4 className="wc-dropdown__card-title">{cardTitle}</h4>}
                      {cardDescription && <p className="wc-dropdown__card-description">{cardDescription}</p>}
                    </div>
                  )}
                </div>
                
                {/* 右侧列表区域 */}
                <div className="wc-dropdown__card-list">
                  {items.map((item, index) => {
                    if (item.divider) {
                      return <div key={item.key || index} className="wc-dropdown__divider" />
                    }
                    
                    const itemClasses = getDropdownItemClasses(item).join(' ')
                    
                    return (
                      <div
                        key={item.key || index}
                        className={itemClasses}
                        onClick={() => handleItemSelect(item, index)}
                      >
                        {item.icon && (
                          <span className="wc-dropdown__icon">
                            {item.icon}
                          </span>
                        )}
                        <span className="wc-dropdown__label">
                          {item.label}
                        </span>
                      </div>
                    )
                  })}
                </div>
              </div>
            ) : (
              items.map((item, index) => {
                if (item.divider) {
                  return <div key={item.key || index} className="wc-dropdown__divider" />
                }
                
                const itemClasses = getDropdownItemClasses(item).join(' ')
                
                return (
                  <div
                    key={item.key || index}
                    className={itemClasses}
                    onClick={() => handleItemSelect(item, index)}
                  >
                    {item.icon && (
                      <span className="wc-dropdown__icon">
                        {item.icon}
                      </span>
                    )}
                    <span className="wc-dropdown__label">
                      {item.label}
                    </span>
                  </div>
                )
              })
            )
          )}
        </div>
      )}
    </div>
  )
}

Dropdown.displayName = 'Dropdown'

export default Dropdown
