// packages/vue/src/components/Select/Select.vue
<template>
  <div ref="selectRef" class="wc-select">
    <!-- Label -->
    <label 
      v-if="label" 
      :id="`${selectId}-label`"
      :class="labelClasses"
    >
      {{ label }}
      <span
        v-if="required"
        class="wc-select__required"
      >*</span>
    </label>
    
    <!-- Select Container -->
    <div
      :class="selectContainerClasses"
      :id="selectId"
      :tabindex="disabled ? -1 : 0"
      role="combobox"
      aria-haspopup="listbox"
      :aria-expanded="open"
      :aria-disabled="disabled"
      :aria-required="required"
      :aria-labelledby="label ? `${selectId}-label` : undefined"
      :aria-controls="`${selectId}-options`"
      :aria-activedescendant="open && activeIndex >= 0 ? `${selectId}-option-${activeIndex}` : undefined"
      @click="toggleDropdown"
      @keydown="handleKeydown"
    >
      <!-- Display Value -->
      <div class="wc-select__value">
        <span v-if="displayValue">{{ displayValue }}</span>
        <span
          v-else
          class="wc-select__placeholder"
        >{{ placeholder }}</span>
      </div>
      
      <!-- Arrow Icon -->
      <div class="wc-select__indicators">
        <div :class="['wc-select__arrow', { 'wc-select__arrow--open': open }]">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="6,9 12,15 18,9" />
          </svg>
        </div>
      </div>
    </div>
    
    <!-- Dropdown -->
    <div
      v-if="open"
      class="wc-select__dropdown"
      :id="`${selectId}-options`"
      ref="dropdownRef"
      role="listbox"
      :aria-multiselectable="multiple || undefined"
    >
      <div class="wc-select__options">
        <div
          v-for="(option, index) in options"
          :key="getOptionValue(option)"
          :id="`${selectId}-option-${index}`"
          :class="getOptionClasses(option)"
          role="option"
          :aria-selected="isSelected(option)"
          :data-active="activeIndex === index ? 'true' : undefined"
          @click="selectOption(option)"
        >
          <span class="wc-select__option-text">{{ getOptionLabel(option) }}</span>
          <svg
            v-if="isSelected(option)"
            class="wc-select__option-check"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="20,6 9,17 4,12" />
          </svg>
        </div>
        
        <div
          v-if="options.length === 0"
          class="wc-select__no-options"
        >
          没有可选项
        </div>
      </div>
    </div>
    
    <!-- Helper Text -->
    <div v-if="error || helperText">
      <p
        v-if="error"
        class="wc-select__error"
      >
        {{ error }}
      </p>
      <p
        v-else-if="helperText"
        class="wc-select__helper"
      >
        {{ helperText }}
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, getCurrentInstance } from 'vue'
import { useOverlayLayer } from '../../interactions'
import './style.css'

const props = defineProps({
  modelValue: {
    type: [String, Number, Array],
    default: null
  },
  options: {
    type: Array,
    default: () => []
  },
  label: {
    type: String,
    default: ''
  },
  placeholder: {
    type: String,
    default: '请选择...'
  },
  disabled: {
    type: Boolean,
    default: false
  },
  required: {
    type: Boolean,
    default: false
  },
  error: {
    type: String,
    default: ''
  },
  helperText: {
    type: String,
    default: ''
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  },
  variant: {
    type: String,
    default: 'filled',
    validator: (value) => ['outlined', 'filled', 'standard'].includes(value)
  },
  multiple: {
    type: Boolean,
    default: false
  },
  valueKey: {
    type: String,
    default: 'value'
  },
  labelKey: {
    type: String,
    default: 'label'
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const instance = getCurrentInstance()
const selectId = ref(`select-${instance?.uid || Math.random().toString(36).substr(2, 9)}`)
const open = ref(false)
const activeIndex = ref(-1)
const selectRef = ref(null)
const dropdownRef = ref(null)

const labelClasses = computed(() => {
  const classes = ['wc-select__label']
  
  classes.push(`wc-select__label--${props.size}`)
  
  if (props.error) {
    classes.push('wc-select__label--error')
  }
  
  return classes
})

const selectContainerClasses = computed(() => {
  const classes = ['wc-select__container']
  
  classes.push(`wc-select__container--${props.variant}`)
  classes.push(`wc-select__container--${props.size}`)
  
  if (props.disabled) {
    classes.push('wc-select__container--disabled')
  }
  
  if (props.error) {
    classes.push('wc-select__container--error')
  }
  
  if (open.value) {
    classes.push('wc-select__container--open')
  }
  
  return classes
})

const displayValue = computed(() => {
  if (props.multiple && Array.isArray(props.modelValue)) {
    if (props.modelValue.length === 0) return ''
    if (props.modelValue.length === 1) {
      const option = props.options.find(opt => getOptionValue(opt) === props.modelValue[0])
      return option ? getOptionLabel(option) : ''
    }
    return `已选择 ${props.modelValue.length} 项`
  } else {
    const option = props.options.find(opt => getOptionValue(opt) === props.modelValue)
    return option ? getOptionLabel(option) : ''
  }
})

const getOptionValue = (option) => {
  return typeof option === 'object' ? option[props.valueKey] : option
}

const getOptionLabel = (option) => {
  return typeof option === 'object' ? option[props.labelKey] : option
}

const isSelected = (option) => {
  const value = getOptionValue(option)
  if (props.multiple && Array.isArray(props.modelValue)) {
    return props.modelValue.includes(value)
  }
  return props.modelValue === value
}

const getOptionClasses = (option) => {
  const classes = ['wc-select__option']
  
  if (isSelected(option)) {
    classes.push('wc-select__option--selected')
  }
  
  return classes
}

const toggleDropdown = () => {
  if (props.disabled) return
  if (open.value) {
    closeDropdown()
  } else {
    openDropdown()
  }
}

const enabledOptionIndexes = computed(() => props.options
  .map((option, index) => ({ option, index }))
  .filter(({ option }) => !option.disabled)
  .map(({ index }) => index)
)

const openDropdown = (initialIndex = enabledOptionIndexes.value[0] ?? -1) => {
  open.value = true
  activeIndex.value = initialIndex
}

const closeDropdown = () => {
  open.value = false
  activeIndex.value = -1
}

const moveActiveIndex = (offset) => {
  const indexes = enabledOptionIndexes.value
  if (!indexes.length) return
  const currentIndex = indexes.indexOf(activeIndex.value)
  const nextIndex = currentIndex < 0
    ? 0
    : (currentIndex + offset + indexes.length) % indexes.length
  activeIndex.value = indexes[nextIndex]
}

const handleKeydown = (event) => {
  if (props.disabled) return
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    if (open.value && activeIndex.value >= 0) {
      selectOption(props.options[activeIndex.value])
    } else {
      openDropdown()
    }
  } else if (event.key === 'ArrowDown') {
    event.preventDefault()
    if (!open.value) openDropdown()
    else moveActiveIndex(1)
  } else if (event.key === 'ArrowUp') {
    event.preventDefault()
    if (!open.value) openDropdown(enabledOptionIndexes.value[enabledOptionIndexes.value.length - 1] ?? -1)
    else moveActiveIndex(-1)
  } else if (event.key === 'Home') {
    event.preventDefault()
    activeIndex.value = enabledOptionIndexes.value[0] ?? -1
  } else if (event.key === 'End') {
    event.preventDefault()
    activeIndex.value = enabledOptionIndexes.value[enabledOptionIndexes.value.length - 1] ?? -1
  } else if (event.key === 'Escape') {
    closeDropdown()
  }
}

const selectOption = (option) => {
  const value = getOptionValue(option)
  
  if (props.multiple) {
    const currentValue = Array.isArray(props.modelValue) ? [...props.modelValue] : []
    const index = currentValue.indexOf(value)
    
    if (index > -1) {
      currentValue.splice(index, 1)
    } else {
      currentValue.push(value)
    }
    
    emit('update:modelValue', currentValue)
    emit('change', currentValue)
  } else {
    emit('update:modelValue', value)
    emit('change', value)
    closeDropdown()
  }
}

const handleClickOutside = (event) => {
  if (!selectRef.value?.contains(event.target)) closeDropdown()
}

useOverlayLayer({
  open,
  elementRef: dropdownRef,
  refs: [selectRef],
  closeOnEscape: true,
  closeOnPointerDownOutside: true,
  onEscapeKeyDown: closeDropdown,
  onPointerDownOutside: closeDropdown,
  zIndex: 1000
})
</script>

// packages/solid/src/components/Select/Select.tsx
import { createSignal } from 'solid-js'
import { useId } from '../../useId'

import { useOverlayLayer } from '../../interactions'
import './style.css'

const Select = ({
  value = '',
  onChange,
  options = [],
  placeholder = 'Select an option',
  label = '',
  helperText = '',
  error = false,
  errorMessage = '',
  required = false,
  disabled = false,
  multiple = false,
  clearable = false,
  fullWidth = false,
  size = 'md',
  variant = 'filled',
  color = 'primary',
  maxHeight = 200,
  name = '',
  id = '',
  className = '',
  style = {},
  onFocus,
  onBlur,
  onSearch,
  renderOption,
  renderValue,
  ...props
}) => {
  const [isOpen, setIsOpen] = createSignal(false)
  const [isFocused, setIsFocused] = createSignal(false)
  const [activeIndex, setActiveIndex] = createSignal(-1)
  let selectRef = null
  let optionsRef = null

  const closeDropdown = () => {
    setIsOpen(false)
    setIsFocused(false)
    setActiveIndex(-1)
  }

  useOverlayLayer({
    open: isOpen,
    elementRef: () => optionsRef,
    refs: () => [selectRef],
    closeOnEscape: true,
    closeOnPointerDownOutside: true,
    onEscapeKeyDown: closeDropdown,
    onPointerDownOutside: closeDropdown,
    zIndex: 1000,
  })

  const selectedOption = multiple 
    ? options.filter(option => value.includes(option.value))
    : options.find(option => option.value === value)

  const getSelectClasses = () => {
    const classes = ['wc-select']
    
    classes.push(`wc-select--${variant}`)
    classes.push(`wc-select--${size}`)
    
    if (error) classes.push('wc-select--error')
    if (disabled) classes.push('wc-select--disabled')
    if (isOpen) classes.push('wc-select--open')
    if (isFocused) classes.push('wc-select--focused')
    if (fullWidth) classes.push('wc-select--full-width')
    if (multiple) classes.push('wc-select--multiple')
    
    return classes.concat(className).filter(Boolean).join(' ')
  }

  const handleToggle = () => {
    if (!disabled) {
      const nextOpen = !isOpen
      setIsOpen(nextOpen)
      setIsFocused(nextOpen)
      setActiveIndex(nextOpen ? Math.max(0, options.findIndex(option => !option.disabled)) : -1)
    }
  }

  const handleOptionClick = (option) => {
    if (option.disabled) return

    let newValue
    if (multiple) {
      const currentValues = Array.isArray(value) ? value : []
      if (currentValues.includes(option.value)) {
        newValue = currentValues.filter(v => v !== option.value)
      } else {
        newValue = [...currentValues, option.value]
      }
    } else {
      newValue = option.value
      closeDropdown()
    }

    onChange?.({ target: { name, value: newValue } })
  }

  const handleClear = (e) => {
    e.stopPropagation()
    const newValue = multiple ? [] : ''
    onChange?.({ target: { name, value: newValue } })
  }

  const handleFocus = (e) => {
    setIsFocused(true)
    onFocus?.(e)
  }

  const handleBlur = (e) => {
    // Don't blur immediately if clicking on options
    setTimeout(() => {
      if (!selectRef?.contains(document.activeElement)) {
        setIsFocused(false)
        onBlur?.(e)
      }
    }, 100)
  }

  const handleKeyDown = (e) => {
    if (disabled) return
    const enabledOptions = options
      .map((option, index) => ({ option, index }))
      .filter(({ option }) => !option.disabled)

    const focusByOffset = (offset) => {
      if (!enabledOptions.length) return
      const currentEnabledIndex = enabledOptions.findIndex(({ index }) => index === activeIndex)
      const nextEnabledIndex = currentEnabledIndex < 0
        ? 0
        : (currentEnabledIndex + offset + enabledOptions.length) % enabledOptions.length
      setActiveIndex(enabledOptions[nextEnabledIndex].index)
    }

    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      if (isOpen && activeIndex >= 0) {
        handleOptionClick(options[activeIndex])
      } else {
        handleToggle()
      }
    } else if (e.key === 'ArrowDown') {
      e.preventDefault()
      if (!isOpen) {
        setIsOpen(true)
        setIsFocused(true)
        setActiveIndex(enabledOptions[0]?.index ?? -1)
      } else {
        focusByOffset(1)
      }
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      if (!isOpen) {
        setIsOpen(true)
        setIsFocused(true)
        setActiveIndex(enabledOptions[enabledOptions.length - 1]?.index ?? -1)
      } else {
        focusByOffset(-1)
      }
    } else if (e.key === 'Home') {
      e.preventDefault()
      setActiveIndex(enabledOptions[0]?.index ?? -1)
    } else if (e.key === 'End') {
      e.preventDefault()
      setActiveIndex(enabledOptions[enabledOptions.length - 1]?.index ?? -1)
    } else if (e.key === 'Escape') {
      closeDropdown()
    }
  }

  const renderSelectedValue = () => {
    if (multiple && Array.isArray(selectedOption)) {
      if (selectedOption.length === 0) {
        return <span class="wc-select__placeholder">{placeholder}</span>
      }
      return (
        <div class="wc-select__chips">
          {selectedOption.map(option => (
            <span key={option.value} class="wc-select__chip">
              {renderValue ? renderValue(option) : (option.label || option.value)}
            </span>
          ))}
        </div>
      )
    } else if (selectedOption) {
      return renderValue ? renderValue(selectedOption) : (selectedOption.label || selectedOption.value)
    } else {
      return <span class="wc-select__placeholder">{placeholder}</span>
    }
  }

  const getLabelClasses = () => {
    const classes = ['wc-select__label']
    classes.push(`wc-select__label--${size}`)
    if (error) classes.push('wc-select__label--error')
    if (isFocused || selectedOption) classes.push('wc-select__label--active')
    return classes.join(' ')
  }
  const getContainerClasses = () => {
    const classes = ['wc-select__container']
    classes.push(`wc-select__container--${variant}`)
    classes.push(`wc-select__container--${size}`)
    if (disabled) classes.push('wc-select__container--disabled')
    if (error) classes.push('wc-select__container--error')
    if (isFocused) classes.push('wc-select__container--focused')
    if (isOpen) classes.push('wc-select__container--open')
    return classes.join(' ')
  }
  const getOptionClasses = (option, isSelected) => {
    const classes = ['wc-select__option']
    if (isSelected) classes.push('wc-select__option--selected')
    if (option.disabled) classes.push('wc-select__option--disabled')
    return classes.join(' ')
  }

  const generatedId = useId()
  const selectId = id || name || generatedId

  return (
    <div class={getSelectClasses()} style={style} ref={selectRef}>
      {label && (
        <label
          htmlFor={selectId}
          id={`${selectId}-label`}
          class={getLabelClasses()}
        >
          {label}
          {required && <span class="wc-select__required">*</span>}
        </label>
      )}
      <div class={getContainerClasses()}>
        <div
          class="wc-select__control"
          id={selectId}
          onClick={handleToggle}
          onFocus={handleFocus}
          onBlur={handleBlur}
          onKeyDown={handleKeyDown}
          tabIndex={disabled ? -1 : 0}
          role="combobox"
          aria-expanded={isOpen()}
          aria-haspopup="listbox"
          aria-labelledby={label ? `${selectId}-label` : undefined}
          aria-controls={`${selectId}-options`}
          aria-activedescendant={isOpen && activeIndex >= 0 ? `${selectId}-option-${activeIndex()}` : undefined}
          aria-disabled={disabled}
          aria-required={required}
        >
          <div class="wc-select__value">
            {renderSelectedValue()}
          </div>
          <div class="wc-select__indicators">
            {clearable && (selectedOption || (multiple && value?.length > 0)) && (
              <button
                type="button"
                class="wc-select__clear"
                onClick={handleClear}
                tabIndex={-1}
              >
                ×
              </button>
            )}
            <div class={`wc-select__arrow${isOpen ? ' wc-select__arrow--open' : ''}`}>
              ▼
            </div>
          </div>
        </div>
        {isOpen && (
          <div
            class="wc-select__dropdown"
            id={`${selectId}-options`}
            style={{ maxHeight }}
            ref={optionsRef}
          >
            <div class="wc-select__options" role="listbox">
              {options.length === 0 ? (
                <div class="wc-select__no-options">没有可选项</div>
              ) : (
                options.map((option, index) => {
                  const isSelected = multiple
                    ? Array.isArray(value) && value.includes(option.value)
                    : value === option.value
                  return (
                    <div
                      key={option.value || index}
                      id={`${selectId}-option-${index}`}
                      class={getOptionClasses(option, isSelected)}
                      onClick={() => handleOptionClick(option)}
                      role="option"
                      aria-selected={isSelected}
                      data-active={activeIndex === index ? 'true' : undefined}
                    >
                      <span class="wc-select__option-text">
                        {renderOption ? renderOption(option) : (option.label || option.value)}
                      </span>
                      {isSelected && (
                        <svg class="wc-select__option-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <polyline points="20,6 9,17 4,12" />
                        </svg>
                      )}
                    </div>
                  )
                })
              )}
            </div>
          </div>
        )}
      </div>
      {(error || helperText) && (
        <div>
          {error ? (
            <p class="wc-select__error">{errorMessage || error}</p>
          ) : (
            <p class="wc-select__helper">{helperText}</p>
          )}
        </div>
      )}
    </div>
  )
}

Select.displayName = 'Select'

export default Select
