// packages/vue/src/components/ImageGallery/ImageGallery.vue
<template>
  <div 
    class="image-gallery"
    :class="[
      `gallery-layout-${layout}`,
      `gallery-size-${size}`,
      loading && 'gallery-loading'
    ]"
  >
    <!-- 画廊标题 -->
    <div
      v-if="title || $slots.title"
      class="gallery-header"
    >
      <slot name="title">
        <h2 class="gallery-title">
          {{ title }}
        </h2>
      </slot>
      <div
        v-if="showCount"
        class="gallery-count"
      >
        {{ images.length }} 张图片
      </div>
    </div>

    <!-- 图片网格 -->
    <div 
      class="gallery-grid"
      :style="gridStyle"
    >
      <div
        v-for="(image, index) in paginatedImages"
        :key="image.id || index"
        class="gallery-item"
        :class="{ 'gallery-item-selected': selectedIndex === index }"
        @click="selectImage(index)"
      >
        <!-- 图片容器 -->
        <div class="gallery-image-container">
          <img
            :src="image.thumbnail || image.src"
            :alt="image.alt || image.title"
            class="gallery-image"
            :loading="lazyLoad ? 'lazy' : 'eager'"
            @load="onImageLoad(index)"
            @error="onImageError(index)"
          >
          
          <!-- 加载状态 -->
          <div
            v-if="!loadedImages[index] && loading"
            class="gallery-image-placeholder"
          >
            <div class="gallery-loading-spinner" />
          </div>
          
          <!-- 悬停遮罩 -->
          <div class="gallery-overlay">
            <div class="gallery-overlay-content">
              <button 
                class="gallery-action-btn gallery-view-btn"
                :aria-label="messages.openImageInLightbox(index + 1)"
                @click.stop="openLightbox(index)"
              >
                <svg
                  class="gallery-icon"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" />
                  <circle
                    cx="12"
                    cy="12"
                    r="2.75"
                  />
                </svg>
              </button>
              <button 
                v-if="showDownload"
                class="gallery-action-btn gallery-download-btn"
                :aria-label="messages.downloadImage(index + 1)"
                @click.stop="downloadImage(image)"
              >
                <svg
                  class="gallery-icon"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path d="M12 3v11" />
                  <path d="m7 10 5 5 5-5" />
                  <path d="M5 20h14" />
                </svg>
              </button>
            </div>
          </div>
          
          <!-- 图片信息 -->
          <div
            v-if="showInfo"
            class="gallery-info"
          >
            <div
              v-if="image.title"
              class="gallery-info-title"
            >
              {{ image.title }}
            </div>
            <div
              v-if="image.description"
              class="gallery-info-description"
            >
              {{ image.description }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 分页 -->
    <div
      v-if="showPagination && totalPages > 1"
      class="gallery-pagination"
    >
      <button 
        class="gallery-page-btn"
        :disabled="currentPage === 1"
        :aria-label="messages.previousPage"
        @click="goToPage(currentPage - 1)"
      >
        上一页
      </button>
      
      <span class="gallery-page-info">
        第 {{ currentPage }} 页，共 {{ totalPages }} 页
      </span>
      
      <button 
        class="gallery-page-btn"
        :disabled="currentPage === totalPages"
        :aria-label="messages.nextPage"
        @click="goToPage(currentPage + 1)"
      >
        下一页
      </button>
    </div>

    <!-- 灯箱模态框 -->
    <teleport to="body">
      <div 
        v-if="lightboxVisible"
        class="gallery-lightbox"
        tabindex="-1"
        @click="closeLightbox"
        @keydown.esc="closeLightbox"
      >
        <div
          class="gallery-lightbox-content"
          @click.stop
        >
          <button 
            class="gallery-lightbox-close"
            :aria-label="messages.closeLightbox"
            @click="closeLightbox"
          >
            <svg
              class="gallery-icon"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path d="m6 6 12 12" />
              <path d="M18 6 6 18" />
            </svg>
          </button>
          
          <div class="gallery-lightbox-image-container">
            <img
              :src="currentLightboxImage?.src"
              :alt="currentLightboxImage?.alt"
              class="gallery-lightbox-image"
            >
          </div>
          
          <div class="gallery-lightbox-info">
            <h3
              v-if="currentLightboxImage?.title"
              class="gallery-lightbox-title"
            >
              {{ currentLightboxImage.title }}
            </h3>
            <p
              v-if="currentLightboxImage?.description"
              class="gallery-lightbox-description"
            >
              {{ currentLightboxImage.description }}
            </p>
          </div>
          
          <div class="gallery-lightbox-navigation">
            <button 
              class="gallery-lightbox-nav gallery-lightbox-prev"
              :disabled="lightboxIndex === 0"
              :aria-label="messages.previousImage"
              @click="previousImage"
            >
              <svg
                class="gallery-icon"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path d="m15 18-6-6 6-6" />
              </svg>
            </button>
            <span class="gallery-lightbox-counter">
              {{ lightboxIndex + 1 }} / {{ images.length }}
            </span>
            <button 
              class="gallery-lightbox-nav gallery-lightbox-next"
              :disabled="lightboxIndex === images.length - 1"
              :aria-label="messages.nextImage"
              @click="nextImage"
            >
              <svg
                class="gallery-icon"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path d="m9 6 6 6-6 6" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </teleport>
  </div>
</template>

<script>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useLocale } from '../../LocaleVUE'

export default {
  name: 'ImageGallery',
  props: {
    images: {
      type: Array,
      default: () => []
    },
    title: {
      type: String,
      default: ''
    },
    layout: {
      type: String,
      default: 'grid',
      validator: (value) => ['grid', 'masonry', 'carousel'].includes(value)
    },
    size: {
      type: String,
      default: 'md',
      validator: (value) => ['sm', 'md', 'lg', 'xl'].includes(value)
    },
    columns: {
      type: Number,
      default: 3
    },
    gap: {
      type: Number,
      default: 16
    },
    showInfo: {
      type: Boolean,
      default: true
    },
    showCount: {
      type: Boolean,
      default: true
    },
    showDownload: {
      type: Boolean,
      default: false
    },
    showPagination: {
      type: Boolean,
      default: false
    },
    itemsPerPage: {
      type: Number,
      default: 12
    },
    lazyLoad: {
      type: Boolean,
      default: true
    },
    loading: {
      type: Boolean,
      default: false
    }
  },
  emits: ['select', 'download', 'lightbox-open', 'lightbox-close'],
  setup(props, { emit }) {
    const { messages } = useLocale()
    const selectedIndex = ref(-1)
    const lightboxVisible = ref(false)
    const lightboxIndex = ref(0)
    const currentPage = ref(1)
    const loadedImages = ref({})

    const gridStyle = computed(() => {
      return {
        gridTemplateColumns: `repeat(${props.columns}, 1fr)`,
        gap: `${props.gap}px`
      }
    })

    const totalPages = computed(() => {
      if (!props.showPagination) return 1
      return Math.ceil(props.images.length / props.itemsPerPage)
    })

    const paginatedImages = computed(() => {
      if (!props.showPagination) return props.images
      const start = (currentPage.value - 1) * props.itemsPerPage
      const end = start + props.itemsPerPage
      return props.images.slice(start, end)
    })

    const currentLightboxImage = computed(() => {
      return props.images[lightboxIndex.value]
    })

    const selectImage = (index) => {
      selectedIndex.value = index
      emit('select', { index, image: props.images[index] })
    }

    const openLightbox = (index) => {
      lightboxIndex.value = index
      lightboxVisible.value = true
      emit('lightbox-open', { index, image: props.images[index] })
      
      // 禁用页面滚动
      document.body.style.overflow = 'hidden'
    }

    const closeLightbox = () => {
      lightboxVisible.value = false
      emit('lightbox-close')
      
      // 恢复页面滚动
      document.body.style.overflow = ''
    }

    const previousImage = () => {
      if (lightboxIndex.value > 0) {
        lightboxIndex.value--
      }
    }

    const nextImage = () => {
      if (lightboxIndex.value < props.images.length - 1) {
        lightboxIndex.value++
      }
    }

    const downloadImage = (image) => {
      emit('download', image)
      
      const link = document.createElement('a')
      link.href = image.src
      link.download = image.title || 'image'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    }

    const goToPage = (page) => {
      currentPage.value = page
    }

    const onImageLoad = (index) => {
      loadedImages.value[index] = true
    }

    const onImageError = (index) => {
      console.warn(`Failed to load image at index ${index}`)
    }

    const handleKeyDown = (e) => {
      if (!lightboxVisible.value) return
      
      switch (e.key) {
        case 'ArrowLeft':
          previousImage()
          break
        case 'ArrowRight':
          nextImage()
          break
        case 'Escape':
          closeLightbox()
          break
      }
    }

    onMounted(() => {
      document.addEventListener('keydown', handleKeyDown)
    })

    onBeforeUnmount(() => {
      document.removeEventListener('keydown', handleKeyDown)
      document.body.style.overflow = ''
    })

    return {
      selectedIndex,
      lightboxVisible,
      lightboxIndex,
      currentPage,
      loadedImages,
      gridStyle,
      totalPages,
      paginatedImages,
      currentLightboxImage,
      selectImage,
      openLightbox,
      closeLightbox,
      previousImage,
      nextImage,
      downloadImage,
      goToPage,
      onImageLoad,
      onImageError,
      messages
    }
  }
}
</script>

<style src="./style.css"></style>

// packages/react/src/components/ImageGallery/ImageGallery.jsx
import React, { useState, useEffect } from 'react'
import './style.css'
import { useLocale } from '../../LocaleReact.tsx'

const EyeIcon = () => (
  <svg className="gallery-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" />
    <circle cx="12" cy="12" r="2.75" />
  </svg>
)

const DownloadIcon = () => (
  <svg className="gallery-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M12 3v11" />
    <path d="m7 10 5 5 5-5" />
    <path d="M5 20h14" />
  </svg>
)

const CloseIcon = () => (
  <svg className="gallery-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="m6 6 12 12" />
    <path d="M18 6 6 18" />
  </svg>
)

const ChevronLeftIcon = () => (
  <svg className="gallery-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="m15 18-6-6 6-6" />
  </svg>
)

const ChevronRightIcon = () => (
  <svg className="gallery-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="m9 6 6 6-6 6" />
  </svg>
)

const ImageGallery = ({
  images = [],
  title = '',
  layout = 'grid', // grid | masonry | carousel (only grid implemented)
  size = 'md', // sm | md | lg | xl (affects aspect ratio)
  columns = 3,
  gap = 16,
  showInfo = true,
  showCount = true,
  showDownload = false,
  showPagination = false,
  itemsPerPage = 12,
  lazyLoad = true,
  loading = false,
  className = '',
  style = {},
  onSelect,
  onDownload,
  onLightboxOpen,
  onLightboxClose,
  ...props
}) => {
  const [selected, setSelected] = useState(-1)
  const [page, setPage] = useState(1)
  const { messages } = useLocale()
  const totalPages = showPagination ? Math.ceil(images.length / itemsPerPage) : 1

  const aspectMap = { sm: '75%', md: '66.67%', lg: '56.25%', xl: '50%' }

  const displayedImages = showPagination
    ? images.slice((page - 1) * itemsPerPage, page * itemsPerPage)
    : images

  const handleSelect = (idx) => {
    const globalIdx = showPagination ? (page - 1) * itemsPerPage + idx : idx
    setSelected(globalIdx)
    const image = images[globalIdx]
    onSelect?.({ index: globalIdx, image })
    onLightboxOpen?.({ index: globalIdx, image })
  }

  const handleDownload = (image) => {
    onDownload?.(image)
    const link = document.createElement('a')
    link.href = image.src
    link.download = image.title || 'image'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const closeLightbox = () => {
    setSelected(-1)
    onLightboxClose?.()
  }

  const handlePrev = () => setSelected((idx) => (idx > 0 ? idx - 1 : idx))
  const handleNext = () => setSelected((idx) => (idx < images.length - 1 ? idx + 1 : idx))

  // Simple lightbox
  useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'Escape') closeLightbox()
      if (selected !== -1) {
        if (e.key === 'ArrowLeft') handlePrev()
        if (e.key === 'ArrowRight') handleNext()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [selected])

  return (
    <div className={[
      'image-gallery',
      `gallery-layout-${layout}`,
      `gallery-size-${size}`,
      loading && 'gallery-loading',
      className
    ].filter(Boolean).join(' ')} style={style} {...props}>

      {(title || showCount) && (
        <div className="gallery-header">
          {title && <h2 className="gallery-title">{title}</h2>}
          {showCount && <div className="gallery-count">{images.length} 张图片</div>}
        </div>
      )}

      <div
        className="gallery-grid"
        style={layout === 'grid'
          ? { gridTemplateColumns: `repeat(${columns},1fr)`, gap }
          : layout === 'masonry'
            ? { columnCount: columns, columnGap: gap }
            : { gap }}
      >
        {displayedImages.map((img, idx) => (
          <div
            key={img.id || idx}
            className="gallery-item"
            onClick={() => handleSelect(idx)}
          >
            <div className="gallery-image-container" style={{ paddingBottom: aspectMap[size] }}>
              <img
                src={img.thumbnail || img.src}
                alt={img.alt || img.title}
                className="gallery-image"
                loading={lazyLoad ? 'lazy' : 'eager'}
              />
              <div className="gallery-overlay">
                <div className="gallery-overlay-content">
                  <button
                    className="gallery-action-btn gallery-view-btn"
                    aria-label={messages.openImageInLightbox(idx + 1)}
                    onClick={(e) => {
                      e.stopPropagation();
                      handleSelect(idx)
                    }}
                  >
                    <EyeIcon />
                  </button>
                  {showDownload && (
                    <button
                      className="gallery-action-btn gallery-download-btn"
                      aria-label={messages.downloadImage(idx + 1)}
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDownload(img)
                      }}
                    >
                      <DownloadIcon />
                    </button>
                  )}
                </div>
              </div>
            </div>
            {showInfo && (img.title || img.description) && (
              <div className="gallery-info">
                {img.title && <div className="gallery-info-title">{img.title}</div>}
                {img.description && <div className="gallery-info-description">{img.description}</div>}
              </div>
            )}
          </div>
        ))}
      </div>

      {showPagination && totalPages > 1 && (
        <div className="gallery-pagination">
          <button className="gallery-page-btn" disabled={page === 1} aria-label={messages.previousPage} onClick={() => setPage(p => p - 1)}>上一页</button>
          <span className="gallery-page-info">第 {page} 页，共 {totalPages} 页</span>
          <button className="gallery-page-btn" disabled={page === totalPages} aria-label={messages.nextPage} onClick={() => setPage(p => p + 1)}>下一页</button>
        </div>
      )}

      {selected !== -1 && (
        <div 
          className="gallery-lightbox" 
          onClick={closeLightbox}
          role="dialog"
          aria-modal="true"
          aria-labelledby="lightbox-title"
        >
          <div className="gallery-lightbox-content" onClick={e => e.stopPropagation()}>
            <button className="gallery-lightbox-close" aria-label={messages.closeLightbox} onClick={closeLightbox}><CloseIcon /></button>
            <div className="gallery-lightbox-image-container">
              <img src={images[selected].src} alt={images[selected].alt} className="gallery-lightbox-image" />
            </div>
            {(images[selected].title || images[selected].description) && (
              <div className="gallery-lightbox-info">
                {images[selected].title && <h3 id="lightbox-title" className="gallery-lightbox-title">{images[selected].title}</h3>}
                {images[selected].description && <p className="gallery-lightbox-description">{images[selected].description}</p>}
              </div>
            )}
            <div className="gallery-lightbox-navigation">
              <button
                className="gallery-lightbox-nav gallery-lightbox-prev"
                disabled={selected === 0}
                aria-label={messages.previousImage}
                onClick={handlePrev}
              >
                <ChevronLeftIcon />
              </button>
              <span className="gallery-lightbox-counter">{selected + 1} / {images.length}</span>
              <button
                className="gallery-lightbox-nav gallery-lightbox-next"
                disabled={selected === images.length - 1}
                aria-label={messages.nextImage}
                onClick={handleNext}
              >
                <ChevronRightIcon />
              </button>
            </div>
            {showDownload && (
              <button className="gallery-action-btn gallery-download-btn" aria-label={messages.downloadImage(selected + 1)} onClick={() => handleDownload(images[selected])}><DownloadIcon /></button>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

ImageGallery.displayName = 'ImageGallery'

export default ImageGallery
