// packages/vue/src/components/Status/Status.vue
<template>
  <span
    :class="statusClasses"
    role="status"
    :title="statusText"
    :aria-label="statusText"
  >
    <span v-if="showText" class="wc-status__text">{{ statusText }}</span>
  </span>
</template>

<script setup>
import { computed } from 'vue'
import { getStatusClasses, getStatusText, isValidSize, isValidStatus } from './utils.js'
import './style.css'

const props = defineProps({
  status: {
    type: String,
    default: 'default',
    validator: isValidStatus
  },
  size: {
    type: String,
    default: 'md',
    validator: isValidSize
  },
  showText: {
    type: Boolean,
    default: false
  },
  animated: {
    type: Boolean,
    default: false
  },
  animationType: {
    type: String,
    default: 'auto'
  }
})

const statusClasses = computed(() => getStatusClasses(props))
const statusText = computed(() => getStatusText(props.status))
</script>

// packages/react/src/components/Status/Status.jsx
import React from 'react'
import './style.css'
import { getStatusClasses, getStatusText } from './utils.js'

const Status = ({
  status = 'default',
  size = 'md',
  showText = false,
  animated = false,
  animationType = 'auto',
  className = '',
  ...props
}) => {
  const statusClasses = getStatusClasses({ status, size, showText, animated, animationType, className })
  const statusTextContent = getStatusText(status)

  return (
    <span
      className={statusClasses}
      role="status"
      title={statusTextContent}
      aria-label={statusTextContent}
      {...props}
    >
      {showText && <span className="wc-status__text">{statusTextContent}</span>}
    </span>
  )
}

Status.displayName = 'Status'

export default Status
