// packages/vue/src/components/Switch/Switch.vue
<template>
  <div class="wc-switch-wrapper">
    <label
      v-if="label"
      :id="labelId"
      :for="inputId"
      class="wc-switch__label"
    >
      {{ label }}
      <span
        v-if="required"
        class="wc-switch__required"
      >*</span>
    </label>

    <div class="wc-switch__container">
      <label
        :class="switchClasses"
        :aria-disabled="disabled"
      >
        <input
          :id="inputId"
          type="checkbox"
          class="wc-switch__input"
          :checked="modelValue"
          :disabled="disabled"
          :required="required"
          role="switch"
          :aria-checked="modelValue"
          :aria-labelledby="label ? labelId : undefined"
          :aria-label="label ? undefined : messages.switchControl"
          @change="handleChange"
        >
        <span class="wc-switch__track">
          <span class="wc-switch__thumb" />
        </span>
      </label>

      <span
        v-if="description"
        class="wc-switch__description"
      >
        {{ description }}
      </span>
    </div>
  </div>
</template>

<script setup>
import { computed, getCurrentInstance } from 'vue'
import { useLocale } from '../../LocaleVUE'
import './style.css'

const { messages } = useLocale()

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  label: { type: String, default: '' },
  description: { type: String, default: '' },
  disabled: { type: Boolean, default: false },
  required: { type: Boolean, default: false },
  color: {
    type: String,
    default: 'primary',
    validator: (value) => ['primary', 'success', 'warning', 'error', 'purple', 'orange', 'cyan', 'pink'].includes(value)
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  }
})

const emit = defineEmits(['update:modelValue', 'change'])
const instance = getCurrentInstance()
const uid = instance?.uid || Math.random().toString(36).slice(2, 11)
const inputId = `wc-switch-${uid}`
const labelId = `${inputId}-label`

const switchClasses = computed(() => [
  'wc-switch',
  `wc-switch--${props.color}`,
  props.size !== 'md' && `wc-switch--${props.size}`,
  props.disabled && 'wc-switch--disabled'
].filter(Boolean))

const handleChange = (event) => {
  if (props.disabled) return
  emit('update:modelValue', event.target.checked)
  emit('change', event.target.checked)
}
</script>

// packages/react/src/components/Switch/Switch.jsx
import React, { useId } from 'react'
import { useLocale } from '../../LocaleReact'
import './style.css' // 引入组件样式

const Switch = ({
  checked = false,
  onChange,
  label = '',
  description = '',
  disabled = false,
  required = false,
  color = 'primary',
  size = 'md',
  className = '',
  ...props
}) => {
  const { messages } = useLocale()
  const labelId = useId()
  const inputId = `${labelId}-input`

  const validColors = ['primary', 'success', 'warning', 'error', 'purple', 'orange', 'cyan', 'pink']
  const safeColor = validColors.includes(color) ? color : 'primary'
  const validSizes = ['sm', 'md', 'lg']
  const safeSize = validSizes.includes(size) ? size : 'md'

  const switchClasses = [
    'wc-switch',
    `wc-switch--${safeColor}`,
    safeSize !== 'md' && `wc-switch--${safeSize}`,
    disabled && 'wc-switch--disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  const handleInputChange = (e) => {
    if (disabled || !onChange) return
    onChange(e.target.checked)
  }

  return (
    <div className="wc-switch-wrapper">
      {/* Label */}
      {label && (
        <label id={labelId} htmlFor={inputId} className="wc-switch__label">
          {label}
          {required && <span className="wc-switch__required">*</span>}
        </label>
      )}

      {/* Switch & Description */}
      <div className="wc-switch__container">
        <label className={switchClasses} aria-disabled={disabled}>
          <input
            type="checkbox"
            id={inputId}
            className="wc-switch__input"
            checked={checked}
            disabled={disabled}
            aria-labelledby={label ? labelId : undefined}
            aria-label={label ? undefined : messages.switchControl}
            aria-checked={checked}
            required={required}
            role="switch"
            onChange={handleInputChange}
            {...props}
          />
          <span className="wc-switch__track">
            <span className="wc-switch__thumb" />
          </span>
        </label>

        {description && (
          <span className="wc-switch__description">
            {description}
          </span>
        )}
      </div>
    </div>
  )
}

Switch.displayName = 'Switch'

export default Switch
