// src/components/Countdown/Countdown.vue
<template>
  <span
    :class="countdownClasses"
    :style="wrapperStyle"
  >
    {{ formattedTime }}
  </span>
</template>

<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, ref, watch } from 'vue'
import { getCountdownClasses, formatTime, getDefaultColor } from './utils.js'
import './style.css'

interface Props {
  seconds: number
  autoStart?: boolean
  size?: 'sm' | 'md' | 'lg' | 'xl'
  color?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'error'
  customColor?: string
  fontSize?: string
  format?: 'simple' | 'detailed' | 'card'
  warningTime?: number | null
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  autoStart: true,
  size: 'md',
  color: 'default',
  customColor: '',
  fontSize: '',
  format: 'simple',
  warningTime: null,
  className: ''
})

const emit = defineEmits<{ finish: [] }>()

const remaining = ref(props.seconds)
let timer: number | null = null

const start = () => {
  if (timer) return
  timer = window.setInterval(() => {
    if (remaining.value > 0) {
      remaining.value -= 1
    } else {
      clear()
      emit('finish')
    }
  }, 1000)
}

const clear = () => {
  if (timer) {
    clearInterval(timer)
    timer = null
  }
}

onMounted(() => {
  if (props.autoStart) start()
})

onBeforeUnmount(() => {
  clear()
})

watch(() => props.seconds, (val) => {
  remaining.value = val
  clear()
  if (props.autoStart) start()
})

const formattedTime = computed(() => formatTime(remaining.value))

const finalColor = computed(() => props.customColor || (props.fontSize ? getDefaultColor() : undefined))

const wrapperStyle = computed(() => {
  const style: Record<string, string> = {}
  if (props.fontSize) style.fontSize = props.fontSize
  if (finalColor.value) style.color = finalColor.value
  return style
})

const countdownClasses = computed(() =>
  getCountdownClasses({
    size: props.size,
    color: props.color,
    format: props.format,
    finished: remaining.value === 0,
    warningTime: props.warningTime,
    remaining: remaining.value,
    className: props.className,
  }).join(' ')
)

defineExpose({ start, clear })
</script>

// src/components/Countdown/Countdown.jsx
import React, { useState, useEffect, useRef, useImperativeHandle, forwardRef } from 'react'
import './style.css'
import { 
  getCountdownClasses, 
  formatTime, 
  createTimer,
  getDefaultColor 
} from './utils.js'

export const Countdown = forwardRef(function Countdown(
  {
    seconds,
    autoStart = true,
    size = 'md',
    color = 'default',
    format = 'simple',
    fontSize = '',
    customColor = '',
    warningTime = null,
    onFinish = () => {},
    className = '',
  }, ref) {
  const [remaining, setRemaining] = useState(seconds)
  const timerRef = useRef(null)

  const timer = createTimer(() => {
    setRemaining((prev) => {
      if (prev > 0) return prev - 1
      timer.stop()
      onFinish()
      return 0
    })
  })

  const clear = () => {
    timer.stop()
  }

  const start = () => {
    timer.start()
  }

  useEffect(() => {
    setRemaining(seconds)
    clear()
    if (autoStart) start()
    return () => clear()
  }, [seconds])

  useEffect(() => {
    if (autoStart) start()
  }, [])

  useImperativeHandle(ref, () => ({ start, clear }))

  const countdownClasses = getCountdownClasses({
    size,
    color,
    format,
    finished: remaining === 0,
    warningTime,
    remaining,
    className
  }).join(' ')

  const formatted = formatTime(remaining)
  
  const finalColor = customColor || 
    (fontSize ? getDefaultColor() : undefined)

  const style = {}
  if (fontSize) style.fontSize = fontSize
  if (finalColor) style.color = finalColor

  return (
    <span
      className={countdownClasses}
      style={style}
    >
      {formatted}
    </span>
  )
})

export default Countdown
