// packages/svelte/src/components/Feed/Feed.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  let { gap = 'md', class: className = '', children }: { gap?: 'none' | 'sm' | 'md' | 'lg'; class?: string; children?: Snippet } = $props()
</script>

<div class="wc-feed wc-feed--gap-{gap} {className}">{@render children?.()}</div>

<style>
  .wc-feed { display: flex; flex-direction: column; box-sizing: border-box; }
  .wc-feed--gap-none { gap: 0; }
  .wc-feed--gap-sm { gap: 8px; }
  .wc-feed--gap-md { gap: 16px; }
  .wc-feed--gap-lg { gap: 24px; }
</style>

// packages/angular/src/components/Feed/Feed.ts
import { ChangeDetectionStrategy, Component, ViewEncapsulation, input } from '@angular/core'

@Component({
  selector: 'wc-feed',
  standalone: true,
  template: `<div class="wc-feed wc-feed--gap-{{ gap() }} {{ className() }}"><ng-content /></div>`,
  styles: [
    ':host{display:contents}',
    `.wc-feed{display:flex;flex-direction:column;box-sizing:border-box}
.wc-feed--gap-none{gap:0}
.wc-feed--gap-sm{gap:8px}
.wc-feed--gap-md{gap:16px}
.wc-feed--gap-lg{gap:24px}`,
  ],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Feed {
  readonly gap = input<'none' | 'sm' | 'md' | 'lg'>('md')
  readonly className = input('')
}
