// packages/angular/src/components/ThemeProvider.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnDestroy,
  OnInit,
  afterNextRender,
  effect,
  forwardRef,
  input,
  output,
  signal,
} from '@angular/core'
import {
  applyThemeConfig,
  createThemeController,
  loadProviderThemeConfig,
  resetThemeConfig,
} from '@zeturn/watercolor-core'
import { WC_THEME, type ThemeStore } from '../hooks'

type ThemeMode = 'light' | 'dark' | 'system'
type ResolvedThemeMode = 'light' | 'dark'

@Component({
  selector: 'wc-theme-provider',
  standalone: true,
  template: '<ng-content />',
  styles: [':host{display:contents}'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: WC_THEME, useExisting: forwardRef(() => ThemeProvider) }],
})
export class ThemeProvider implements ThemeStore, OnInit, OnDestroy {
  readonly config = input<any>(undefined)
  readonly defaultMode = input<ThemeMode>('system')
  readonly themeUrl = input<string | undefined>(undefined)
  readonly target = input<HTMLElement | null | undefined>(undefined)
  readonly modeInput = input<ThemeMode | undefined>(undefined, { alias: 'mode' })
  readonly initialResolvedMode = input<ResolvedThemeMode | undefined>(undefined)
  readonly storageKey = input<string | undefined>(undefined)
  readonly storage = input<any>(undefined)
  readonly themeLoad = output<any>()
  readonly themeError = output<any>()

  private controller: any = null
  private unsubscribeFn: (() => void) | null = null
  private mounted = false
  private requestId = 0
  private abortController: AbortController | null = null

  private readonly currentMode = signal<string>('system')
  private readonly currentResolvedMode = signal<string>('light')
  private readonly isDark = signal(false)

  get mode(): string {
    return this.currentMode()
  }
  get resolvedMode(): string {
    return this.currentResolvedMode()
  }
  get dark(): boolean {
    return this.isDark()
  }

  constructor() {
    effect(() => {
      const controlled = this.modeInput()
      if (controlled !== undefined) this.controller?.setMode(controlled)
    })
    effect(() => {
      // Track config/themeUrl reactively; re-run the theme request once mounted.
      const config = this.config()
      const themeUrl = this.themeUrl()
      if (this.mounted && (config !== undefined || themeUrl !== undefined)) this.runThemeRequest()
    })
    afterNextRender(() => {
      this.mounted = true
      this.controller?.start()
      this.runThemeRequest()
    })
  }

  ngOnInit(): void {
    this.controller = createThemeController({
      target: this.target() ?? undefined,
      initialMode: (this.modeInput() ?? this.defaultMode()) as ThemeMode,
      initialResolvedMode: this.initialResolvedMode(),
      storageKey: this.storageKey(),
      storage: this.storage(),
      readStorage: this.modeInput() === undefined,
    })
    this.currentMode.set(this.controller.mode)
    this.currentResolvedMode.set(this.controller.resolvedMode)
    this.isDark.set(this.controller.dark)
    this.unsubscribeFn = this.controller.subscribe((snapshot: any) => {
      this.currentMode.set(snapshot.mode)
      this.currentResolvedMode.set(snapshot.resolvedMode)
      this.isDark.set(snapshot.dark)
    })
  }

  setMode = (next: string): void => {
    if (this.modeInput() === undefined) this.controller?.setMode(next as ThemeMode)
  }

  toggleMode = (): void => {
    this.setMode(this.currentResolvedMode() === 'dark' ? 'light' : 'dark')
  }

  private runThemeRequest(): void {
    const currentRequest = ++this.requestId
    this.abortController?.abort()
    this.abortController = typeof AbortController === 'undefined' ? null : new AbortController()

    const config = this.config()
    const themeUrl = this.themeUrl()
    const target = this.target() ?? undefined

    if (config !== undefined) {
      const result = applyThemeConfig(config, { target })
      if (result.ok) this.themeLoad.emit(result)
      else this.themeError.emit(result)
    } else if (!themeUrl) {
      resetThemeConfig(target)
    }

    if (themeUrl) {
      void loadProviderThemeConfig(themeUrl, {
        target,
        isCurrent: () => currentRequest === this.requestId,
        signal: this.abortController?.signal,
      }).then((result: any) => {
        if (!result) return
        if (result.ok) this.themeLoad.emit(result)
        else if (!this.abortController?.signal.aborted) this.themeError.emit(result)
      })
    }
  }

  ngOnDestroy(): void {
    this.abortController?.abort()
    resetThemeConfig(this.target() ?? undefined)
    this.unsubscribeFn?.()
    this.controller?.destroy()
  }
}

// packages/svelte/src/components/ThemeProvider.svelte
<script lang="ts">
  import { setContext, onMount, onDestroy } from 'svelte'
  import {
    createThemeController,
    applyThemeConfig,
    loadProviderThemeConfig,
    resetThemeConfig,
  } from '@zeturn/watercolor-core'
  import type { Snippet } from 'svelte'

  type ThemeMode = 'light' | 'dark' | 'system'
  type ResolvedThemeMode = 'light' | 'dark'

  let {
    config = undefined,
    defaultMode = 'system',
    themeUrl = undefined,
    target = undefined,
    mode = undefined,
    initialResolvedMode = undefined,
    storageKey = undefined,
    storage = undefined,
    onThemeLoad = undefined,
    onThemeError = undefined,
    children,
  }: {
    config?: any
    defaultMode?: ThemeMode
    themeUrl?: string
    target?: HTMLElement | null
    mode?: ThemeMode
    initialResolvedMode?: ResolvedThemeMode
    storageKey?: string
    storage?: any
    onThemeLoad?: (result: any) => void
    onThemeError?: (result: any) => void
    children?: Snippet
  } = $props()

  // The controller is intentionally configured once; reactive mode changes are handled below.
  // svelte-ignore state_referenced_locally
  const controller = createThemeController({
    target,
    initialMode: (mode ?? defaultMode) as ThemeMode,
    initialResolvedMode: initialResolvedMode as ResolvedThemeMode | undefined,
    storageKey,
    storage,
    readStorage: mode === undefined,
  })

  let currentMode = $state(controller.mode)
  let currentResolvedMode = $state(controller.resolvedMode)
  let isDark = $state(controller.dark)

  const unsubscribe = controller.subscribe((snapshot: any) => {
    currentMode = snapshot.mode
    currentResolvedMode = snapshot.resolvedMode
    isDark = snapshot.dark
  })

  function setMode(next: ThemeMode) {
    if (mode === undefined) controller.setMode(next)
  }
  function toggleMode() {
    setMode(currentResolvedMode === 'dark' ? 'light' : 'dark')
  }

  const store = {
    get mode() {
      return currentMode
    },
    get resolvedMode() {
      return currentResolvedMode
    },
    get dark() {
      return isDark
    },
    setMode,
    toggleMode,
  }
  setContext('wc-theme', store)

  let mounted = false
  let requestId = 0
  let abortController: AbortController | null = null

  function emitThemeLoad(result: any) {
    onThemeLoad?.(result)
  }
  function emitThemeError(result: any) {
    onThemeError?.(result)
  }
  function runThemeRequest() {
    const currentRequest = ++requestId
    abortController?.abort()
    abortController = typeof AbortController === 'undefined' ? null : new AbortController()

    if (config !== undefined) {
      const result = applyThemeConfig(config, { target })
      if (result.ok) emitThemeLoad(result)
      else emitThemeError(result)
    } else if (!themeUrl) {
      resetThemeConfig(target)
    }

    if (themeUrl) {
      void loadProviderThemeConfig(themeUrl, {
        target,
        isCurrent: () => currentRequest === requestId,
        signal: abortController?.signal,
      }).then((result: any) => {
        if (!result) return
        if (result.ok) emitThemeLoad(result)
        else if (!abortController?.signal.aborted) emitThemeError(result)
      })
    }
  }

  onMount(() => {
    mounted = true
    controller.start()
    runThemeRequest()
  })

  onDestroy(() => {
    abortController?.abort()
    resetThemeConfig(target)
    unsubscribe()
    controller.destroy()
  })

  $effect(() => {
    if (mode !== undefined) controller.setMode(mode)
  })
  $effect(() => {
    if (mounted && (config !== undefined || themeUrl !== undefined)) runThemeRequest()
  })
</script>

{@render children?.()}
