// src/components/Form/FormControl.vue
<template>
  <div
    class="form-control"
    :class="formControlClasses"
  >
    <slot />
  </div>
</template>

<script setup>
import { computed, provide } from 'vue'

const props = defineProps({
  disabled: {
    type: Boolean,
    default: false
  },
  error: {
    type: Boolean,
    default: false
  },
  required: {
    type: Boolean,
    default: false
  },
  variant: {
    type: String,
    default: 'outlined',
    validator: (value) => ['outlined', 'filled', 'standard'].includes(value)
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  },
  fullWidth: {
    type: Boolean,
    default: false
  },
  margin: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'dense', 'normal'].includes(value)
  }
})

const formControlClasses = computed(() => {
  const classes = []
  
  // Width
  if (props.fullWidth) {
    classes.push('form-control--full-width')
  }
  
  // Margin
  if (props.margin === 'dense') {
    classes.push('form-control--margin-dense')
  } else if (props.margin === 'normal') {
    classes.push('form-control--margin-normal')
  }
  
  // States
  if (props.disabled) {
    classes.push('form-control--disabled')
  }
  
  if (props.error) {
    classes.push('form-control--error')
  }
  
  return classes
})

// Provide context to child components
provide('formControlContext', {
  disabled: props.disabled,
  error: props.error,
  required: props.required,
  variant: props.variant,
  size: props.size
})
</script>

<style scoped>
.form-control {
  display: flex;
  flex-direction: column;
  position: relative;
}

.form-control--full-width {
  width: 100%;
}

.form-control--margin-dense {
  margin-bottom: 8px;
}

.form-control--margin-normal {
  margin-bottom: 16px;
}

.form-control--disabled {
  opacity: 0.6;
  pointer-events: none;
}

.form-control--error {
  /* Error state will be handled by child components */
}
</style>

// src/components/Form/FormControl.jsx
import React, { createContext, useMemo } from 'react'

export const FormControlContext = createContext(null)

const FormControl = ({
  disabled = false,
  error = false,
  required = false,
  variant = 'outlined', // outlined | filled | standard
  size = 'md', // sm | md | lg
  fullWidth = false,
  margin = 'normal', // none | dense | normal
  className = '',
  style = {},
  children,
  ...props
}) => {
  const contextValue = useMemo(() => ({
    disabled,
    error,
    required,
    variant,
    size
  }), [disabled, error, required, variant, size])

  const classes = [
    'form-control',
    fullWidth && 'form-control--full-width',
    margin === 'dense' && 'form-control--margin-dense',
    margin === 'normal' && 'form-control--margin-normal',
    disabled && 'form-control--disabled',
    error && 'form-control--error',
    className
  ].filter(Boolean).join(' ')

  return (
    <FormControlContext.Provider value={contextValue}>
      <div className={classes} style={style} {...props}>
        {children}
      </div>
    </FormControlContext.Provider>
  )
}

FormControl.displayName = 'FormControl'

export default FormControl
