// packages/solid/src/components/SlideOver/SlideOver.tsx
import { mergeProps, Show } from 'solid-js'

import { Portal, useOverlayLayer } from '../../interactions'
import { useLocale } from '../../LocaleSolid.tsx'
import './style.css'

/**
 * SlideOver (Solid)
 * 侧滑面板，支持左右方向、宽度自定义。
 */
const SlideOver = (rawProps) => {
  const props = mergeProps({ open: false, placement: 'right', width: 400 }, rawProps)
  let panelRef = null
  const { messages } = useLocale()

  const handleClose = () => {
    props.onClose?.()
  }

  useOverlayLayer({
    open: () => props.open,
    elementRef: () => panelRef,
    modal: true,
    lockScroll: true,
    restoreFocus: true,
    initialFocus: true,
    closeOnEscape: true,
    closeOnPointerDownOutside: false,
    onEscapeKeyDown: handleClose,
    zIndex: 3000,
  })

  return (
    <Show when={props.open}>
      <Portal>
        <div class="wc-slideover-wrapper">
          <div class="wc-slideover-overlay" onClick={handleClose} />
          <div
            ref={(el) => { panelRef = el }}
            class={`wc-slideover-panel wc-slideover-${props.placement}`}
            style={{ width: typeof props.width === 'number' ? `${props.width}px` : props.width }}
            role="dialog"
            aria-modal="true"
            tabIndex={-1}
          >
            {props.header && <header class="wc-slideover-header">{props.header}</header>}
            <div class="wc-slideover-body">{props.children}</div>
            {props.footer && <footer class="wc-slideover-footer">{props.footer}</footer>}
            <button class="wc-slideover-close" type="button" onClick={handleClose} aria-label={messages.closeDialog}>
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M6 6l12 12M18 6 6 18" />
              </svg>
            </button>
          </div>
        </div>
      </Portal>
    </Show>
  )
}

export default SlideOver

// packages/react/src/components/SlideOver/SlideOver.jsx
import React, { useCallback, useRef } from 'react'
import { Portal, useOverlayLayer } from '../../interactions.jsx'
import { useLocale } from '../../LocaleReact.tsx'
import './style.css'

/**
 * SlideOver (React)
 * 侧滑面板，支持左右方向、宽度自定义。
 */
const SlideOver = ({ open = false, onClose = () => {}, placement = 'right', width = 400, children, header, footer }) => {
  const panelRef = useRef(null)
  const { messages } = useLocale()

  const handleClose = useCallback(() => {
    onClose?.()
  }, [onClose])

  useOverlayLayer({
    open,
    elementRef: panelRef,
    modal: true,
    lockScroll: true,
    restoreFocus: true,
    initialFocus: true,
    closeOnEscape: true,
    closeOnPointerDownOutside: false,
    onEscapeKeyDown: handleClose,
    zIndex: 3000,
  })

  return (
    <Portal>
      {open ? (
        <div className="wc-slideover-wrapper">
          <div className="wc-slideover-overlay" onClick={handleClose} />
          <div
            ref={panelRef}
            className={`wc-slideover-panel wc-slideover-${placement}`}
            style={{ width: typeof width === 'number' ? `${width}px` : width }}
            role="dialog"
            aria-modal="true"
            tabIndex={-1}
          >
            {header && <header className="wc-slideover-header">{header}</header>}
            <div className="wc-slideover-body">{children}</div>
            {footer && <footer className="wc-slideover-footer">{footer}</footer>}
            <button className="wc-slideover-close" type="button" onClick={handleClose} aria-label={messages.closeDialog}>
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M6 6l12 12M18 6 6 18" />
              </svg>
            </button>
          </div>
        </div>
      ) : null}
    </Portal>
  )
}

export default SlideOver
