// src/components/List/List.jsx
import React, { createContext } from 'react'

/**
 * ListContext 用于向 ListItem 及其子组件传递密集模式 (dense) 设置
 */
export const ListContext = createContext({ dense: false })

/**
 * React 版本的 List 组件
 *
 * Props:
 *  - dense            是否使用紧凑模式，影响内部 padding 与字体大小
 *  - disablePadding   是否禁用垂直内边距
 *  - subheader        可选子标题（暂未实现渲染，保持 API 对齐）
 */
const List = ({
  children,
  dense = false,
  disablePadding = false,
  subheader = '',
  className = '',
  ...rest
}) => {
  const listClasses = [
    'w-full',
    !disablePadding && 'py-2',
    className
  ].filter(Boolean).join(' ')

  return (
    <ListContext.Provider value={{ dense }}>
      <ul role="list" className={listClasses} {...rest}>
        {children}
      </ul>
    </ListContext.Provider>
  )
}

export default List

// src/components/List/List.vue
<template>
  <template v-if="subheader">
    <div class="wc-list-subheader">
      {{ subheader }}
    </div>
    <component
      :is="component"
      :class="listClasses"
      role="list"
    >
      <slot />
    </component>
  </template>
  <component
    :is="component"
    v-else
    :class="listClasses"
    role="list"
    v-bind="$attrs"
  >
    <slot />
  </component>
</template>

<script setup>
import { computed, provide } from 'vue'

defineOptions({
  inheritAttrs: false
})

const props = defineProps({
  dense: {
    type: Boolean,
    default: false
  },
  disablePadding: {
    type: Boolean,
    default: false
  },
  subheader: {
    type: String,
    default: ''
  },
  component: {
    type: String,
    default: 'ul'
  },
  nav: {
    type: Boolean,
    default: false
  }
})

const listClasses = computed(() => {
  const classes = ['wc-list', 'w-full']
  
  if (props.dense) {
    classes.push('wc-list--dense')
  }
  
  if (props.disablePadding) {
    classes.push('wc-list--no-padding')
  } else {
    classes.push('py-2')
  }
  
  if (props.nav) {
    classes.push('wc-list--nav')
  }
  
  return classes
})

// Provide context to child ListItem components
provide('listContext', {
  dense: props.dense
})
</script>
