// src/components/Card/CardContent.vue
<template>
  <div :class="cardContentClasses">
    <slot />
  </div>
</template>

<script setup>
import { computed } from 'vue'
import './style.css'

const props = defineProps({
  disablePadding: {
    type: Boolean,
    default: false
  },
  padding: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'dense', 'normal', 'comfortable'].includes(value)
  }
})

const cardContentClasses = computed(() => {
  const baseClasses = 'wc-card-content'
  const classes = [baseClasses]
  
  if (!props.disablePadding) {
    const paddingMap = {
      'none': '',
      'dense': 'wc-padding-dense',
      'normal': 'wc-padding-normal',
      'comfortable': 'wc-padding-comfortable'
    }
    classes.push(paddingMap[props.padding])
  }
  
  return classes
})
</script>

// packages/react/src/components/Card/CardContent.jsx
import React from 'react'
import './style.css'

export const CardContent = ({
  children,
  disablePadding = false,
  padding = 'normal',
  className = '',
  ...props
}) => {
  const paddingMap = {
    'none': '',
    'dense': 'wc-padding-dense',
    'normal': 'wc-padding-normal',
    'comfortable': 'wc-padding-comfortable'
  }

  const classes = [
    'wc-card-content',
    !disablePadding && paddingMap[padding],
    className
  ].filter(Boolean).join(' ')

  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}

CardContent.displayName = 'CardContent'

export default CardContent
