// packages/vue/src/components/Card/Card.vue
<template>
  <div
    :class="cardClasses"
    :role="attrs.onClick ? 'button' : undefined"
    :tabindex="attrs.onClick ? 0 : undefined"
    @keydown="handleKeydown"
  >
    <div
      v-if="title || $slots.header"
      class="wc-card-header"
    >
      <slot name="header">
        <h3
          v-if="title"
          class="wc-card__title"
        >
          {{ title }}
        </h3>
      </slot>
    </div>
    
    <div class="wc-card-content">
      <slot />
    </div>
    
    <div
      v-if="$slots.footer"
      class="wc-card-footer"
    >
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup>
import { computed, useAttrs } from 'vue'
import { getCardClasses } from './utils.js'
import { validVariants, validColors, validSizes } from './utils.js'
import './style.css'

const props = defineProps({
  title: {
    type: String,
    default: ''
  },
  variant: {
    type: String,
    default: 'minimal',
    validator: (value) => validVariants.includes(value)
  },
  color: {
    type: String,
    default: 'default',
    validator: (value) => validColors.includes(value)
  },
  size: {
    type: String,
    default: 'medium',
    validator: (value) => validSizes.includes(value)
  },
  interactive: {
    type: Boolean,
    default: false
  },
  noBorder: {
    type: Boolean,
    default: true
  },
  className: {
    type: String,
    default: ''
  }
})

const attrs = useAttrs()
const isInteractive = computed(() => props.interactive || Boolean(attrs.onClick))

const cardClasses = computed(() => 
  getCardClasses(props.className, props.variant, props.color, props.size, isInteractive.value, props.noBorder)
)

const handleKeydown = (event) => {
  if (!attrs.onClick || !['Enter', ' '].includes(event.key)) return
  event.preventDefault()
  attrs.onClick(event)
}
</script>

// packages/react/src/components/Card/Card.jsx
import React from 'react'
import './style.css'
import { getCardClasses } from './utils.js'

const Card = ({
  children,
  title = '',
  variant = 'minimal',
  color = 'default',
  size = 'medium',
  interactive = false,
  noBorder = true,
  className = '',
  header = null,
  footer = null,
  style = {},
  onClick,
  onMouseEnter,
  onMouseLeave,
  onKeyDown,
  ...props
}) => {
  const isInteractive = interactive || Boolean(onClick)
  const cardClasses = getCardClasses(className, variant, color, size, isInteractive, noBorder)

  const handleClick = (e) => {
    if (isInteractive && onClick) {
      onClick(e)
    }
  }

  const handleKeyDown = (event) => {
    onKeyDown?.(event)
    if (!onClick || event.defaultPrevented || !['Enter', ' '].includes(event.key)) return
    event.preventDefault()
    onClick(event)
  }

  return (
    <div
      className={cardClasses}
      style={style}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      role={onClick ? 'button' : undefined}
      tabIndex={onClick ? 0 : undefined}
      {...props}
    >
      {header && (
        <div className="wc-card-header">
          {header}
        </div>
      )}

      {title && (
        <div className="wc-card-header">
          <h3 className="wc-card__title">{title}</h3>
        </div>
      )}

      <div className="wc-card-content">
        {children}
      </div>

      {footer && (
        <div className="wc-card-footer">
          {footer}
        </div>
      )}
    </div>
  )
}

Card.displayName = 'Card'

export default Card
