// packages/vue/src/components/Pagination/Pagination.vue
<template>
  <nav
    v-if="pageCount > 1"
    :class="paginationClasses"
    aria-label="分页导航"
  >
    <!-- 上一页按钮 -->
    <button 
      class="page-btn wc-page-btn wc-page-btn--prev wc-page-btn--nav"
      :disabled="currentPageInternal === 1" 
      aria-label="上一页"
      @click="select(currentPageInternal - 1)"
    >
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="m15 18-6-6 6-6" />
      </svg>
    </button>

    <!-- 页面按钮 -->
    <template
      v-for="page in pageItems"
      :key="page.key"
    >
      <button 
        v-if="!page.ellipsis" 
        :class="['page-btn', 'wc-page-btn', { active: page.num === currentPageInternal, 'wc-page-btn--active': page.num === currentPageInternal }]" 
        :aria-current="page.num === currentPageInternal ? 'page' : undefined"
        :aria-label="`第 ${page.num} 页`"
        @click="select(page.num)"
      >
        {{ page.num }}
      </button>
      <span
        v-else
        class="page-ellipsis wc-page-ellipsis"
      >…</span>
    </template>

    <!-- 下一页按钮 -->
    <button 
      class="page-btn wc-page-btn wc-page-btn--next wc-page-btn--nav" 
      :disabled="currentPageInternal === pageCount" 
      aria-label="下一页"
      @click="select(currentPageInternal + 1)"
    >
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="m9 18 6-6-6-6" />
      </svg>
    </button>

    <!-- 页面大小选择器 -->
    <div
      v-if="showSizeChanger"
      class="wc-pagination-size-selector"
    >
      <select aria-label="每页条数" @change="handleSizeChange">
        <option
          v-for="size in pageSizeOptions"
          :key="size"
          :value="size"
          :selected="size === pageSize"
        >
          {{ size }} / 页
        </option>
      </select>
    </div>

    <!-- 快速跳转器 -->
    <div
      v-if="showQuickJumper"
      class="wc-pagination-quick-jumper"
    >
      <span>跳转到</span>
      <input 
        type="number" 
        :min="1" 
        :max="pageCount"
        placeholder="页码"
        aria-label="跳转页码"
        @keyup.enter="handleQuickJump"
      >
    </div>
  </nav>
</template>

<script>
import { ref, computed, watch } from 'vue'
import './style.css'

export default {
  name: 'Pagination',
  props: {
    modelValue: {
      type: Number,
      default: 1
    },
    currentPage: {
      type: Number,
      default: 1
    },
    total: {
      type: Number,
      required: true
    },
    pageSize: {
      type: Number,
      default: 10
    },
    siblingCount: {
      type: Number,
      default: 1
    },
    boundaryCount: {
      type: Number,
      default: 1
    },
    showSizeChanger: {
      type: Boolean,
      default: false
    },
    showQuickJumper: {
      type: Boolean,
      default: false
    },
    pageSizeOptions: {
      type: Array,
      default: () => [10, 20, 50, 100]
    },
    size: {
      type: String,
      default: 'md',
      validator: (value) => ['sm', 'md', 'lg', 'xl'].includes(value)
    }
  },
  emits: ['update:modelValue', 'change', 'page-change', 'size-change'],
  setup(props, { emit }) {
    const currentPageInternal = ref(props.currentPage || props.modelValue)

    watch(() => props.modelValue, (val) => {
      currentPageInternal.value = val
    })

    watch(() => props.currentPage, (val) => {
      currentPageInternal.value = val
    })

    const paginationClasses = computed(() => {
      const classes = ['pagination', 'wc-pagination']
      if (props.size !== 'md') {
        classes.push(`wc-pagination--${props.size}`)
      }
      return classes
    })

    const pageCount = computed(() => Math.max(1, Math.ceil(props.total / props.pageSize)))

    const range = (start, end) => {
      const arr = []
      for (let i = start; i <= end; i++) arr.push(i)
      return arr
    }

    const pageItems = computed(() => {
      const totalPages = pageCount.value
      const current = currentPageInternal.value
      const { siblingCount, boundaryCount } = props

      const totalNumbers = siblingCount * 2 + 3 + boundaryCount * 2
      if (totalPages <= totalNumbers) {
        return range(1, totalPages).map(n => ({ key: n, num: n }))
      }

      const leftSibling = Math.max(current - siblingCount, boundaryCount + 2)
      const rightSibling = Math.min(current + siblingCount, totalPages - boundaryCount - 1)

      const showLeftEllipsis = leftSibling > boundaryCount + 2
      const showRightEllipsis = rightSibling < totalPages - boundaryCount - 1

      const items = []
      // left boundary
      for (let i = 1; i <= boundaryCount; i++) items.push({ key: 'b' + i, num: i })
      if (showLeftEllipsis) items.push({ key: 'l-ellipsis', ellipsis: true })
      // middle
      for (let i = leftSibling; i <= rightSibling; i++) items.push({ key: 'm' + i, num: i })
      if (showRightEllipsis) items.push({ key: 'r-ellipsis', ellipsis: true })
      // right boundary
      for (let i = totalPages - boundaryCount + 1; i <= totalPages; i++) items.push({ key: 'e' + i, num: i })

      return items
    })

    const select = (page) => {
      if (page < 1 || page > pageCount.value || page === currentPageInternal.value) return
      currentPageInternal.value = page
      emit('update:modelValue', page)
      emit('change', page)
      emit('page-change', page)
    }

    const handleSizeChange = (event) => {
      const newSize = parseInt(event.target.value)
      emit('size-change', newSize)
    }

    const handleQuickJump = (event) => {
      const page = parseInt(event.target.value)
      if (page >= 1 && page <= pageCount.value) {
        select(page)
        event.target.value = ''
      }
    }

    return { 
      currentPageInternal, 
      pageCount, 
      pageItems, 
      select, 
      paginationClasses,
      handleSizeChange,
      handleQuickJump
    }
  }
}
</script>

// packages/react/src/components/Pagination/Pagination.jsx
import React, { useState, useMemo, useEffect, useCallback } from 'react'
import './style.css'

/**
 * Pagination component – React version
 * Props:
 *   value        当前页码（受控）
 *   onChange     (page:number)=>void  页码变化回调
 *   total        数据总数
 *   pageSize     每页条数
 *   siblingCount 同级页码数量
 *   boundaryCount 边界页码数量
 *   size         尺寸
 */
export default function Pagination({
  value = 1,
  onChange,
  total,
  pageSize = 10,
  siblingCount = 1,
  boundaryCount = 1,
  size = 'md', // sm | md | lg | xl
  className = '',
  ...rest
}) {
  const [currentPage, setCurrentPage] = useState(value)

  // 同步外部 value
  useEffect(() => {
    setCurrentPage(value)
  }, [value])

  const pageCount = useMemo(() => Math.max(1, Math.ceil(total / pageSize)), [total, pageSize])

  const range = (start, end) => {
    const arr = []
    for (let i = start; i <= end; i++) arr.push(i)
    return arr
  }

  const pageItems = useMemo(() => {
    const totalNumbers = siblingCount * 2 + 3 + boundaryCount * 2
    if (pageCount <= totalNumbers) {
      return range(1, pageCount).map((n) => ({ key: n, num: n }))
    }

    const leftSibling = Math.max(currentPage - siblingCount, boundaryCount + 2)
    const rightSibling = Math.min(currentPage + siblingCount, pageCount - boundaryCount - 1)

    const showLeftEllipsis = leftSibling > boundaryCount + 2
    const showRightEllipsis = rightSibling < pageCount - boundaryCount - 1

    const items = []

    for (let i = 1; i <= boundaryCount; i++) items.push({ key: 'b' + i, num: i })
    if (showLeftEllipsis) items.push({ key: 'l-ellipsis', ellipsis: true })

    for (let i = leftSibling; i <= rightSibling; i++) items.push({ key: 'm' + i, num: i })
    if (showRightEllipsis) items.push({ key: 'r-ellipsis', ellipsis: true })

    for (let i = pageCount - boundaryCount + 1; i <= pageCount; i++) items.push({ key: 'e' + i, num: i })

    return items
  }, [currentPage, pageCount, siblingCount, boundaryCount])

  const select = useCallback(
    (page) => {
      if (page < 1 || page > pageCount || page === currentPage) return
      setCurrentPage(page)
      onChange?.(page)
    },
    [currentPage, pageCount, onChange]
  )

  if (pageCount <= 1) return null

  // 组装根元素类
  const rootClasses = [
    'pagination',
    'wc-pagination',
    size !== 'md' ? `wc-pagination--${size}` : '',
    className
  ].filter(Boolean).join(' ')

  return (
    <nav className={rootClasses} aria-label="分页导航" {...rest}>
      <button
        className="page-btn wc-page-btn wc-page-btn--prev wc-page-btn--nav"
        disabled={currentPage === 1}
        onClick={() => select(currentPage - 1)}
        aria-label="上一页"
      >
        <svg viewBox="0 0 24 24" aria-hidden="true">
          <path d="m15 18-6-6 6-6" />
        </svg>
      </button>

      {pageItems.map((page) =>
        page.ellipsis ? (
          <span key={page.key} className="page-ellipsis">
            …
          </span>
        ) : (
          <button
            key={page.key}
            className={`page-btn wc-page-btn${page.num === currentPage ? ' active wc-page-btn--active' : ''}`}
            onClick={() => select(page.num)}
            aria-current={page.num === currentPage ? 'page' : undefined}
            aria-label={`第 ${page.num} 页`}
          >
            {page.num}
          </button>
        )
      )}

      <button
        className="page-btn wc-page-btn wc-page-btn--next wc-page-btn--nav"
        disabled={currentPage === pageCount}
        onClick={() => select(currentPage + 1)}
        aria-label="下一页"
      >
        <svg viewBox="0 0 24 24" aria-hidden="true">
          <path d="m9 18 6-6-6-6" />
        </svg>
      </button>
    </nav>
  )
}

// 样式通过同名 Vue 组件的 scoped style 复用
