// packages/vue/src/components/Popover/Popover.vue
<template>
  <div
    ref="triggerWrapper"
    class="wc-popover-container"
  >
    <slot
      name="trigger"
      :open="open"
      :close="close"
    >
      <button
        class="wc-popover-trigger"
        type="button"
        :aria-expanded="isOpen.toString()"
        aria-haspopup="dialog"
        :aria-controls="popoverId"
        @click="toggle"
      >
        {{ triggerText }}
      </button>
    </slot>

    <teleport to="body">
      <transition name="wc-popover-fade">
        <div
          v-if="isOpen"
          ref="popoverRef"
          class="wc-popover-content"
          :class="[`wc-popover-content--${resolvedPlacement}`]"
          :id="popoverId"
          role="dialog"
          :aria-label="messages.closePopover"
          tabindex="-1"
        >
          <slot>
            这是默认的弹出内容。
          </slot>
        </div>
      </transition>
    </teleport>
  </div>
</template>

<script>
import { computed, ref, nextTick, useId, watch } from 'vue'
import { useFloatingPosition, useOverlayLayer } from '../../interactions'
import { useLocale } from '../../LocaleVUE'
import './style.css'

export default {
  name: 'Popover',
  props: {
    modelValue: {
      type: Boolean,
      default: false,
    },
    triggerText: {
      type: String,
      default: '打开弹窗',
    },
    placement: {
      type: String,
      default: 'bottom',
      validator: (v) => ['top', 'bottom', 'left', 'right'].includes(v),
    },
    offset: {
      type: Number,
      default: 8,
    },
  },
  emits: ['update:modelValue', 'open', 'close'],
  setup(props, { emit }) {
    const { messages } = useLocale()
    const isOpen = ref(props.modelValue)
    const triggerWrapper = ref(null)
    const popoverRef = ref(null)
    const popoverId = useId()

    const open = () => {
      if (isOpen.value) return
      isOpen.value = true
      emit('update:modelValue', true)
      emit('open')
      nextTick(update)
    }

    const close = () => {
      if (!isOpen.value) return
      isOpen.value = false
      emit('update:modelValue', false)
      emit('close')
    }

    const toggle = () => {
      isOpen.value ? close() : open()
    }

    const placementRef = computed(() => props.placement)
    const offsetRef = computed(() => props.offset)
    const { resolvedPlacement, update } = useFloatingPosition({
      open: isOpen,
      anchorRef: triggerWrapper,
      floatingRef: popoverRef,
      placement: placementRef,
      offset: offsetRef
    })

    useOverlayLayer({
      open: isOpen,
      elementRef: popoverRef,
      refs: [triggerWrapper],
      closeOnEscape: true,
      closeOnPointerDownOutside: true,
      onEscapeKeyDown: close,
      onPointerDownOutside: close,
      zIndex: 2000
    })

    watch(() => props.modelValue, value => {
      isOpen.value = value
      if (value) nextTick(update)
    })

    return { isOpen, open, close, toggle, triggerWrapper, popoverRef, popoverId, resolvedPlacement, messages }
  },
}
</script>

// packages/react/src/components/Popover/Popover.jsx
import React, { useState, useRef, useId } from 'react'
import { Portal, useFloatingPosition, useOverlayLayer } from '../../interactions.jsx'
import { useLocale } from '../../LocaleReact'
import './style.css'

/**
 * Popover – React 组件
 * Props
 *  open        受控布尔
 *  onOpenChange (open:boolean)=>void
 *  trigger     React 节点（可选）
 *  placement   top | bottom | left | right
 *  offset      number px
 */
export default function Popover({
  open,
  onOpenChange,
  triggerText = '打开弹窗',
  trigger,
  placement = 'bottom',
  offset = 8,
  children,
  className = '',
}) {
  const { messages } = useLocale()
  const popoverId = useId()
  const [internalOpen, setInternalOpen] = useState(false)
  const isControlled = open !== undefined && open !== null

  const triggerRef = useRef(null)
  const popoverRef = useRef(null)

  const actualOpen = isControlled ? open : internalOpen

  const setOpen = (state) => {
    if (!isControlled) {
      setInternalOpen(state)
    }
    onOpenChange?.(state)
  }

  const closePopover = () => setOpen(false)
  const togglePopover = () => {
    setOpen(!actualOpen)
  }

  const resolvedPlacement = useFloatingPosition({
    open: actualOpen,
    anchorRef: triggerRef,
    floatingRef: popoverRef,
    placement,
    offset,
  })

  useOverlayLayer({
    open: actualOpen,
    elementRef: popoverRef,
    refs: [triggerRef],
    closeOnEscape: true,
    closeOnPointerDownOutside: true,
    onEscapeKeyDown: closePopover,
    onPointerDownOutside: closePopover,
    zIndex: 2000,
  })

  // Render
  const triggerNode = trigger ? (
    React.cloneElement(trigger, {
      ref: triggerRef,
      onClick: togglePopover,
      'aria-expanded': actualOpen,
      'aria-haspopup': 'dialog',
      'aria-controls': popoverId,
    })
  ) : (
    <button
      ref={triggerRef}
      type="button"
      className="wc-popover-trigger"
      onClick={togglePopover}
      aria-expanded={actualOpen}
      aria-haspopup="dialog"
      aria-controls={popoverId}
    >
      {triggerText}
    </button>
  )

  return (
    <div className={`wc-popover-container ${className}`.trim()}>
      {triggerNode}
      {actualOpen &&
        <Portal>
          <div
            ref={popoverRef}
            id={popoverId}
            className={`wc-popover-content wc-popover-content--${resolvedPlacement}`.trim()}
            role="dialog"
            aria-label={messages.closePopover}
            tabIndex={-1}
          >
            {children}
          </div>
        </Portal>}
    </div>
  )
}
