// src/components/Container/Container.vue
<template>
  <div :class="containerClasses">
    <slot />
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { isValidMaxWidth, getContainerClasses } from './utils.js'
import './style.css'

const props = defineProps({
  maxWidth: {
    type: String,
    default: 'lg',
    validator: isValidMaxWidth
  },
  fluid: {
    type: Boolean,
    default: false
  },
  fixed: {
    type: Boolean,
    default: false
  }
})

const containerClasses = computed(() => 
  getContainerClasses(props).join(' ')
)
</script>

// src/components/Container/Container.jsx
import React from 'react'
import { getTailwindContainerClasses } from './utils.js'
import './style.css'

export function Container({
  maxWidth = 'lg',
  fluid = false,
  fixed = false,
  className = '',
  children,
}) {
  const containerClasses = getTailwindContainerClasses({
    maxWidth,
    fluid,
    fixed,
    className
  }).join(' ')

  return <div className={containerClasses}>{children}</div>
}

export default Container
