// packages/vue/src/components/Breadcrumb/Breadcrumb.vue
<template>
  <nav
    :class="breadcrumbClasses"
    :aria-label="messages.breadcrumb"
    role="navigation"
  >
    <ol class="wc-breadcrumb-list">
      <li
        v-for="(item, index) in processedItems"
        :key="index"
        :class="getBreadcrumbItemClasses(index, processedItems.length)"
      >
        <component
          :is="getComponent(item, index)"
          :class="getBreadcrumbLinkClasses(item.disabled)"
          :href="getHref(item, index)"
          :aria-current="index === processedItems.length - 1 ? 'page' : undefined"
          @click="handleClick($event, item, index)"
        >
          <span
            v-if="item.icon"
            class="wc-breadcrumb-icon"
            v-html="item.icon"
          />
          {{ item.label }}
        </component>
        <span
          v-if="index < processedItems.length - 1"
          class="wc-breadcrumb-separator"
          aria-hidden="true"
        >
          {{ separator }}
        </span>
      </li>
    </ol>
  </nav>
</template>

<script setup>
import { computed } from 'vue'
import { useLocale } from '../../LocaleVUE'
import { 
  isValidVariant,
  processBreadcrumbItems,
  getBreadcrumbClasses,
  getBreadcrumbItemClasses,
  getBreadcrumbLinkClasses,
  handleBreadcrumbClick,
  shouldRenderAsLink
} from './utils.js'
import './style.css'

const props = defineProps({
  items: {
    type: Array,
    required: true,
    default: () => []
  },
  separator: {
    type: String,
    default: '/'
  },
  maxItems: {
    type: Number,
    default: 0
  },
  showHome: {
    type: Boolean,
    default: false
  },
  homeIcon: {
    type: String,
    default: '🏠'
  },
  variant: {
    type: String,
    default: 'default',
    validator: isValidVariant
  }
})

const emit = defineEmits(['click'])
const { messages } = useLocale()

const breadcrumbClasses = computed(() => getBreadcrumbClasses(props.variant))

const processedItems = computed(() => 
  processBreadcrumbItems(props.items, props.showHome, props.homeIcon, props.maxItems)
)

const getComponent = (item, index) => {
  if (!shouldRenderAsLink(index, processedItems.value.length, item.disabled, item.isEllipsis)) {
    return 'span'
  }
  if (item.href) {
    return 'a'
  }
  if (item.to) {
    return 'router-link'
  }
  return 'button'
}

const getHref = (item, index) => {
  if (!shouldRenderAsLink(index, processedItems.value.length, item.disabled, item.isEllipsis)) {
    return undefined
  }
  return item.href
}

const handleClick = (event, item, index) => {
  const shouldContinue = handleBreadcrumbClick(
    event, 
    item, 
    index, 
    processedItems.value.length, 
    (e, item, idx) => emit('click', { event: e, item, index: idx })
  )
  
  if (!shouldContinue) {
    return
  }
}
</script>

// packages/react/src/components/Breadcrumb/Breadcrumb.jsx
import React from 'react'
import { useLocale } from '../../LocaleReact'
import './style.css'
import { 
  processBreadcrumbItems,
  getBreadcrumbClasses,
  getBreadcrumbItemClasses,
  getBreadcrumbLinkClasses,
  handleBreadcrumbClick,
  shouldRenderAsLink
} from './utils.js'

export default function Breadcrumb({ 
  items = [], 
  separator = '/', 
  variant = 'default', 
  showHome = false, 
  homeIcon = '🏠', 
  maxItems = 0, 
  onItemClick 
}) {
  const { messages } = useLocale()
  // 处理 items 与截断逻辑
  const processed = React.useMemo(() => 
    processBreadcrumbItems(items, showHome, homeIcon, maxItems),
    [items, showHome, homeIcon, maxItems]
  )

  const handleClick = (e, item, idx) => {
    handleBreadcrumbClick(e, item, idx, processed.length, onItemClick)
  }

  const breadcrumbClasses = getBreadcrumbClasses(variant)

  return (
    <nav className={breadcrumbClasses} aria-label={messages.breadcrumb} role="navigation">
      <ol className="wc-breadcrumb-list">
        {processed.map((item, idx) => (
          <li key={idx} className={getBreadcrumbItemClasses(idx, processed.length)}>          
            {shouldRenderAsLink(idx, processed.length, item.disabled, item.isEllipsis) ? (
              item.href ? (
                <a
                  href={item.href}
                  className={getBreadcrumbLinkClasses(item.disabled)}
                  onClick={(e) => handleClick(e, item, idx)}
                >
                  {item.icon && <span className="wc-breadcrumb-icon" dangerouslySetInnerHTML={{ __html: item.icon }} />}
                  {item.label}
                </a>
              ) : (
                <button
                  type="button"
                  onClick={(e) => handleClick(e, item, idx)}
                  className={getBreadcrumbLinkClasses(item.disabled)}
                >
                  {item.icon && <span className="wc-breadcrumb-icon" dangerouslySetInnerHTML={{ __html: item.icon }} />}
                  {item.label}
                </button>
              )
            ) : (
              <span className={getBreadcrumbLinkClasses(true)} aria-current="page">
                {item.icon && <span className="wc-breadcrumb-icon" dangerouslySetInnerHTML={{ __html: item.icon }} />}
                {item.label}
              </span>
            )}
            {idx < processed.length - 1 && (
              <span className="wc-breadcrumb-separator">{separator}</span>
            )}
          </li>
        ))}
      </ol>
    </nav>
  )
}
