// packages/react/src/components/List/ListItem.jsx
import React, { useContext } from 'react'
import { ListContext } from './List.jsx'
import { getListItemClasses } from './utils.js'
import './style.css'

/**
 * React 版本的 ListItem
 */
const ListItem = ({
  children,
  button = false,
  disabled = false,
  divider = false,
  selected = false,
  disableGutters = false,
  multiselect = false,
  component: ComponentProp,
  className = '',
  ...rest
}) => {
  const { dense } = useContext(ListContext) || { dense: false }

  const itemClasses = getListItemClasses({
    button,
    disabled,
    divider,
    dense,
    selected,
    disableGutters,
    multiselect,
    className
  }).join(' ')

  const Component = ComponentProp || (button ? 'button' : 'div')

  return (
    <Component
      role="listitem"
      className={itemClasses}
      disabled={button && disabled}
      {...rest}
    >
      {children}
    </Component>
  )
}

export default ListItem

// packages/vue/src/components/List/ListItem.vue
<template>
  <component
    :is="componentTag"
    :class="itemClasses"
    role="listitem"
    :disabled="button && disabled"
    v-bind="$attrs"
  >
    <!-- 可选插槽：图标、主要内容、操作区 -->
    <slot name="icon" />
    <slot />
    <slot name="action" />
  </component>
</template>

<script setup>
import { computed, inject } from 'vue'
import { getListItemClasses } from './utils.js'
import './style.css'

const props = defineProps({
  button: Boolean,
  disabled: Boolean,
  divider: Boolean,
  selected: Boolean,
  disableGutters: Boolean,
  multiselect: Boolean,
  className: {
    type: String,
    default: ''
  },
  component: {
    type: String,
    default: ''
  }
})

// 从父级 List 提供的上下文中获取 dense 信息
const listContext = inject('listContext', { dense: false })

// 计算实际渲染的标签：显式 component > button? 'button' : 'li'
const componentTag = computed(() => props.component || (props.button ? 'button' : 'li'))

// 计算样式类
const itemClasses = computed(() => getListItemClasses({
  button: props.button,
  disabled: props.disabled,
  divider: props.divider,
  dense: listContext.dense,
  selected: props.selected,
  disableGutters: props.disableGutters,
  multiselect: props.multiselect,
  className: props.className
}).join(' '))
</script>
