// src/components/Spinner/Spinner.jsx
import React, { useEffect } from 'react'

/**
 * Spinner (React)
 * 旋转加载指示器，使用主题系统变量，支持尺寸、颜色、粗细自定义。
 */
const Spinner = ({ size = 40, thickness = 4, color = 'var(--wc-primary-500)', style = {}, className = '', ...rest }) => {
  useEffect(() => {
    // 注入一次 keyframes（若已存在则跳过）
    if (!document.getElementById('wc-spinner-keyframes')) {
      const styleEl = document.createElement('style')
      styleEl.id = 'wc-spinner-keyframes'
      styleEl.innerHTML = `@keyframes wc-spin { to { transform: rotate(360deg); } }`
      document.head.appendChild(styleEl)
    }
  }, [])

  const spinnerStyle = {
    width: size,
    height: size,
    borderWidth: thickness,
    borderStyle: 'solid',
    borderColor: 'var(--wc-neutral-200)',
    borderTopColor: color,
    borderRadius: '50%',
    animation: 'wc-spin 1s linear infinite',
    ...style
  }

  return <div className={`wc-spinner ${className}`} style={spinnerStyle} {...rest} />
}

export default Spinner

// src/components/Spinner/Spinner.vue
<template>
  <div class="wc-spinner" :style="style"></div>
</template>

<script>
export default {
  name: 'Spinner',
  props: {
    size: { type: Number, default: 40 },
    color: { type: String, default: 'var(--wc-primary-500)' },
    thickness: { type: Number, default: 4 },
  },
  computed: {
    style () {
      return {
        width: this.size + 'px',
        height: this.size + 'px',
        borderWidth: this.thickness + 'px',
        borderTopColor: this.color
      }
    }
  }
}
</script>

<style scoped>
.wc-spinner {
  border: 4px solid var(--wc-neutral-200);
  border-top-color: var(--wc-primary-500);
  border-radius: 50%;
  animation: wc-spin 1s linear infinite;
}

@keyframes wc-spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
