// src/components/Select/Select.vue
<template>
  <div class="wc-select">
    <!-- Label -->
    <label 
      v-if="label" 
      :for="selectId" 
      :class="labelClasses"
    >
      {{ label }}
      <span
        v-if="required"
        class="wc-select__required"
      >*</span>
    </label>
    
    <!-- Select Container -->
    <div
      :class="selectContainerClasses"
      @click="toggleDropdown"
    >
      <!-- Display Value -->
      <div class="wc-select__value">
        <span v-if="displayValue">{{ displayValue }}</span>
        <span
          v-else
          class="wc-select__placeholder"
        >{{ placeholder }}</span>
      </div>
      
      <!-- Arrow Icon -->
      <div class="wc-select__indicators">
        <div :class="['wc-select__arrow', { 'wc-select__arrow--open': open }]">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="6,9 12,15 18,9" />
          </svg>
        </div>
      </div>
    </div>
    
    <!-- Dropdown -->
    <div
      v-if="open"
      class="wc-select__dropdown"
    >
      <div
        v-if="searchable"
        class="wc-select__search"
      >
        <input
          v-model="searchQuery"
          class="wc-select__search-input"
          placeholder="搜索..."
          @click.stop
        >
      </div>
      
      <div class="wc-select__options">
        <div
          v-for="option in filteredOptions"
          :key="getOptionValue(option)"
          :class="getOptionClasses(option)"
          @click="selectOption(option)"
        >
          <span class="wc-select__option-text">{{ getOptionLabel(option) }}</span>
          <svg
            v-if="isSelected(option)"
            class="wc-select__option-check"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="20,6 9,17 4,12" />
          </svg>
        </div>
        
        <div
          v-if="filteredOptions.length === 0"
          class="wc-select__no-options"
        >
          没有找到选项
        </div>
      </div>
    </div>
    
    <!-- Helper Text -->
    <div v-if="error || helperText">
      <p
        v-if="error"
        class="wc-select__error"
      >
        {{ error }}
      </p>
      <p
        v-else-if="helperText"
        class="wc-select__helper"
      >
        {{ helperText }}
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, getCurrentInstance, onMounted, onUnmounted } from 'vue'
import './style.css'

const props = defineProps({
  modelValue: {
    type: [String, Number, Array],
    default: null
  },
  options: {
    type: Array,
    default: () => []
  },
  label: {
    type: String,
    default: ''
  },
  placeholder: {
    type: String,
    default: '请选择...'
  },
  disabled: {
    type: Boolean,
    default: false
  },
  required: {
    type: Boolean,
    default: false
  },
  error: {
    type: String,
    default: ''
  },
  helperText: {
    type: String,
    default: ''
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  },
  variant: {
    type: String,
    default: 'outlined',
    validator: (value) => ['outlined', 'filled', 'standard'].includes(value)
  },
  multiple: {
    type: Boolean,
    default: false
  },
  searchable: {
    type: Boolean,
    default: false
  },
  valueKey: {
    type: String,
    default: 'value'
  },
  labelKey: {
    type: String,
    default: 'label'
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const instance = getCurrentInstance()
const selectId = ref(`select-${instance?.uid || Math.random().toString(36).substr(2, 9)}`)
const open = ref(false)
const searchQuery = ref('')

const labelClasses = computed(() => {
  const classes = ['wc-select__label']
  
  classes.push(`wc-select__label--${props.size}`)
  
  if (props.error) {
    classes.push('wc-select__label--error')
  }
  
  return classes
})

const selectContainerClasses = computed(() => {
  const classes = ['wc-select__container']
  
  classes.push(`wc-select__container--${props.variant}`)
  classes.push(`wc-select__container--${props.size}`)
  
  if (props.disabled) {
    classes.push('wc-select__container--disabled')
  }
  
  if (props.error) {
    classes.push('wc-select__container--error')
  }
  
  if (open.value) {
    classes.push('wc-select__container--open')
  }
  
  return classes
})

const filteredOptions = computed(() => {
  if (!props.searchable || !searchQuery.value) {
    return props.options
  }
  
  return props.options.filter(option => {
    const label = getOptionLabel(option).toLowerCase()
    return label.includes(searchQuery.value.toLowerCase())
  })
})

const displayValue = computed(() => {
  if (props.multiple && Array.isArray(props.modelValue)) {
    if (props.modelValue.length === 0) return ''
    if (props.modelValue.length === 1) {
      const option = props.options.find(opt => getOptionValue(opt) === props.modelValue[0])
      return option ? getOptionLabel(option) : ''
    }
    return `已选择 ${props.modelValue.length} 项`
  } else {
    const option = props.options.find(opt => getOptionValue(opt) === props.modelValue)
    return option ? getOptionLabel(option) : ''
  }
})

const getOptionValue = (option) => {
  return typeof option === 'object' ? option[props.valueKey] : option
}

const getOptionLabel = (option) => {
  return typeof option === 'object' ? option[props.labelKey] : option
}

const isSelected = (option) => {
  const value = getOptionValue(option)
  if (props.multiple && Array.isArray(props.modelValue)) {
    return props.modelValue.includes(value)
  }
  return props.modelValue === value
}

const getOptionClasses = (option) => {
  const classes = ['wc-select__option']
  
  if (isSelected(option)) {
    classes.push('wc-select__option--selected')
  }
  
  return classes
}

const toggleDropdown = () => {
  if (props.disabled) return
  open.value = !open.value
  if (open.value) {
    searchQuery.value = ''
  }
}

const selectOption = (option) => {
  const value = getOptionValue(option)
  
  if (props.multiple) {
    const currentValue = Array.isArray(props.modelValue) ? [...props.modelValue] : []
    const index = currentValue.indexOf(value)
    
    if (index > -1) {
      currentValue.splice(index, 1)
    } else {
      currentValue.push(value)
    }
    
    emit('update:modelValue', currentValue)
    emit('change', currentValue)
  } else {
    emit('update:modelValue', value)
    emit('change', value)
    open.value = false
  }
}

const handleClickOutside = (event) => {
  if (!event.target.closest('.wc-select')) {
    open.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

// src/components/Select/Select.jsx
import React, { useState, useRef, useEffect } from 'react'
import './style.css'

const Select = ({
  value = '',
  onChange,
  options = [],
  placeholder = 'Select an option',
  label = '',
  helperText = '',
  error = false,
  errorMessage = '',
  required = false,
  disabled = false,
  multiple = false,
  searchable = false,
  clearable = false,
  fullWidth = false,
  size = 'md',
  variant = 'filled',
  color = 'primary',
  maxHeight = 200,
  name = '',
  id = '',
  className = '',
  style = {},
  onFocus,
  onBlur,
  onSearch,
  renderOption,
  renderValue,
  ...props
}) => {
  const [isOpen, setIsOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [isFocused, setIsFocused] = useState(false)
  const selectRef = useRef(null)
  const optionsRef = useRef(null)

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (selectRef.current && !selectRef.current.contains(event.target)) {
        setIsOpen(false)
        setIsFocused(false)
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [])

  const filteredOptions = searchable && searchQuery
    ? options.filter(option => 
        (option.label || option.value).toLowerCase().includes(searchQuery.toLowerCase())
      )
    : options

  const selectedOption = multiple 
    ? options.filter(option => value.includes(option.value))
    : options.find(option => option.value === value)

  const getSelectClasses = () => {
    const classes = ['wc-select']
    
    classes.push(`wc-select--${variant}`)
    classes.push(`wc-select--${size}`)
    
    if (error) classes.push('wc-select--error')
    if (disabled) classes.push('wc-select--disabled')
    if (isOpen) classes.push('wc-select--open')
    if (isFocused) classes.push('wc-select--focused')
    if (fullWidth) classes.push('wc-select--full-width')
    if (multiple) classes.push('wc-select--multiple')
    
    return classes.concat(className).filter(Boolean).join(' ')
  }

  const getSelectStyles = () => {
    const styles = { ...style }
    
    // Use CSS variables for theming
    if (variant === 'outlined') {
      styles.borderColor = error ? 'var(--wc-error-500)' : `var(--wc-${color}-500)`
    } else if (variant === 'filled') {
      styles.backgroundColor = 'var(--wc-neutral-50)'
    }
    
    return styles
  }

  const handleToggle = () => {
    if (!disabled) {
      setIsOpen(!isOpen)
      setIsFocused(!isOpen)
    }
  }

  const handleOptionClick = (option) => {
    if (option.disabled) return

    let newValue
    if (multiple) {
      const currentValues = Array.isArray(value) ? value : []
      if (currentValues.includes(option.value)) {
        newValue = currentValues.filter(v => v !== option.value)
      } else {
        newValue = [...currentValues, option.value]
      }
    } else {
      newValue = option.value
      setIsOpen(false)
      setIsFocused(false)
    }

    onChange?.({ target: { name, value: newValue } })
  }

  const handleClear = (e) => {
    e.stopPropagation()
    const newValue = multiple ? [] : ''
    onChange?.({ target: { name, value: newValue } })
  }

  const handleSearchChange = (e) => {
    const query = e.target.value
    setSearchQuery(query)
    onSearch?.(query)
  }

  const handleFocus = (e) => {
    setIsFocused(true)
    onFocus?.(e)
  }

  const handleBlur = (e) => {
    // Don't blur immediately if clicking on options
    setTimeout(() => {
      if (!selectRef.current?.contains(document.activeElement)) {
        setIsFocused(false)
        onBlur?.(e)
      }
    }, 100)
  }

  const renderSelectedValue = () => {
    if (multiple && Array.isArray(selectedOption)) {
      if (selectedOption.length === 0) {
        return <span className="wc-select__placeholder">{placeholder}</span>
      }
      return (
        <div className="wc-select__chips">
          {selectedOption.map(option => (
            <span key={option.value} className="wc-select__chip">
              {renderValue ? renderValue(option) : (option.label || option.value)}
            </span>
          ))}
        </div>
      )
    } else if (selectedOption) {
      return renderValue ? renderValue(selectedOption) : (selectedOption.label || selectedOption.value)
    } else {
      return <span className="wc-select__placeholder">{placeholder}</span>
    }
  }

  const getLabelClasses = () => {
    const classes = ['wc-select__label']
    classes.push(`wc-select__label--${size}`)
    if (error) classes.push('wc-select__label--error')
    if (isFocused || selectedOption) classes.push('wc-select__label--active')
    return classes.join(' ')
  }
  const getContainerClasses = () => {
    const classes = ['wc-select__container']
    classes.push(`wc-select__container--${variant}`)
    classes.push(`wc-select__container--${size}`)
    if (disabled) classes.push('wc-select__container--disabled')
    if (error) classes.push('wc-select__container--error')
    if (isFocused) classes.push('wc-select__container--focused')
    if (isOpen) classes.push('wc-select__container--open')
    return classes.join(' ')
  }
  const getOptionClasses = (option, isSelected) => {
    const classes = ['wc-select__option']
    if (isSelected) classes.push('wc-select__option--selected')
    if (option.disabled) classes.push('wc-select__option--disabled')
    return classes.join(' ')
  }

  const selectId = id || name || `select-${Math.random().toString(36).substr(2, 9)}`

  return (
    <div className="wc-select" ref={selectRef}>
      {label && (
        <label
          htmlFor={selectId}
          className={getLabelClasses()}
        >
          {label}
          {required && <span className="wc-select__required">*</span>}
        </label>
      )}
      <div className={getContainerClasses()}>
        <div
          className="wc-select__control"
          style={getSelectStyles()}
          onClick={handleToggle}
          onFocus={handleFocus}
          onBlur={handleBlur}
          tabIndex={disabled ? -1 : 0}
          role="combobox"
          aria-expanded={isOpen}
          aria-haspopup="listbox"
          aria-labelledby={label ? `${selectId}-label` : undefined}
        >
          <div className="wc-select__value">
            {renderSelectedValue()}
          </div>
          <div className="wc-select__indicators">
            {clearable && (selectedOption || (multiple && value?.length > 0)) && (
              <button
                type="button"
                className="wc-select__clear"
                onClick={handleClear}
                tabIndex={-1}
              >
                ×
              </button>
            )}
            <div className={`wc-select__arrow${isOpen ? ' wc-select__arrow--open' : ''}`}>
              ▼
            </div>
          </div>
        </div>
        {isOpen && (
          <div
            className="wc-select__dropdown"
            style={{ maxHeight }}
            ref={optionsRef}
          >
            {searchable && (
              <div className="wc-select__search">
                <input
                  type="text"
                  className="wc-select__search-input"
                  placeholder="搜索..."
                  value={searchQuery}
                  onChange={handleSearchChange}
                  autoFocus
                />
              </div>
            )}
            <div className="wc-select__options" role="listbox">
              {filteredOptions.length === 0 ? (
                <div className="wc-select__no-options">没有找到选项</div>
              ) : (
                filteredOptions.map((option, index) => {
                  const isSelected = multiple
                    ? Array.isArray(value) && value.includes(option.value)
                    : value === option.value
                  return (
                    <div
                      key={option.value || index}
                      className={getOptionClasses(option, isSelected)}
                      onClick={() => handleOptionClick(option)}
                      role="option"
                      aria-selected={isSelected}
                    >
                      <span className="wc-select__option-text">
                        {renderOption ? renderOption(option) : (option.label || option.value)}
                      </span>
                      {isSelected && (
                        <svg className="wc-select__option-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <polyline points="20,6 9,17 4,12" />
                        </svg>
                      )}
                    </div>
                  )
                })
              )}
            </div>
          </div>
        )}
      </div>
      {(error || helperText) && (
        <div>
          {error ? (
            <p className="wc-select__error">{errorMessage || error}</p>
          ) : (
            <p className="wc-select__helper">{helperText}</p>
          )}
        </div>
      )}
    </div>
  )
}

Select.displayName = 'Select'

export default Select
