// src/components/FileInput/FileInput.vue
<template>
  <label
    :class="wrapperClasses"
    @dragover.prevent
    @drop.prevent="onDrop"
  >
    <input
      type="file"
      class="file-input"
      :multiple="multiple"
      :accept="accept"
      @change="onChange"
    />
    <div v-if="variant==='block'" class="file-input-content">
      <slot>{{ label }}</slot>
    </div>
    <span v-else-if="variant==='button'" class="file-button">{{ label }}</span>
    <span v-else-if="variant==='icon'" class="file-icon">⬆️</span>
  </label>
</template>

<script>
export default {
  name: 'FileInput',
  props: {
    multiple: { type: Boolean, default: false },
    variant: { type: String, default: 'block' }, // block | button | icon
    accept: { type: String, default: '' },
    label: { type: String, default: '选择文件' },
  },
  emits: ['change', 'invalid'],
  computed: {
    wrapperClasses() {
      return [
        'file-input-wrapper',
        `variant-${this.variant}`,
      ]
    },
  },
  methods: {
    validateFiles(files) {
      if (!this.accept) return true
      const acceptList = this.accept.split(',').map((a) => a.trim())
      const invalids = [...files].filter((file) => {
        return !acceptList.some((rule) => {
          if (rule.startsWith('.')) {
            return file.name.endsWith(rule)
          }
          return file.type === rule
        })
      })
      if (invalids.length) {
        this.$emit('invalid', invalids)
        return false
      }
      return true
    },
    onChange(e) {
      const files = e.target.files
      if (this.validateFiles(files)) this.$emit('change', files)
    },
    onDrop(e) {
      const files = e.dataTransfer.files
      if (this.validateFiles(files)) this.$emit('change', files)
    },
  }
}
</script>

<style scoped>
/* 基础隐藏 */
.file-input{display:none;}
/* block 变体 */
.file-input-wrapper{display:flex;align-items:center;justify-content:center;padding:32px;border:2px dashed var(--color-border,#d1d5db);border-radius:8px;background:var(--color-gray-50,#f9fafb);cursor:pointer;text-align:center;transition:background 0.2s;}
.file-input-content strong{font-weight:600;}
.file-input-content .link{color:var(--color-primary,#3b82f6);text-decoration:underline;}
.file-input-wrapper:hover{background:var(--color-gray-100,#eef2f7);} 
/* button 变体 */
.variant-button{display:inline-flex;padding:8px 16px;border-radius:6px;background:var(--color-primary,#3b82f6);color:#fff;border:none;font-weight:500;}
.variant-button:hover{background:#2563eb;}
/* icon 变体 */
.variant-icon{display:inline-flex;width:40px;height:40px;align-items:center;justify-content:center;border:1px solid var(--color-border,#d1d5db);border-radius:50%;background:var(--color-gray-50,#f9fafb);} 

@media(prefers-color-scheme:dark){
  .file-input-wrapper{background:var(--color-dark-surface,#1f2937);border-color:var(--color-dark-border,#374151);} 
  .variant-icon{background:var(--color-dark-surface,#1f2937);} 
}
</style>

// src/components/FileInput/FileInput.jsx
import React, { useRef } from 'react'

const FileInput = ({
  multiple = false,
  variant = 'block', // block | button | icon
  accept = '',
  label = '选择文件',
  onChange,
  onInvalid,
  className = '',
  style = {},
}) => {
  const inputRef = useRef(null)

  const validateFiles = (files) => {
    if (!accept) return true
    const acceptList = accept.split(',').map((a) => a.trim())
    const invalids = [...files].filter((file) => {
      return !acceptList.some((rule) => {
        if (rule.startsWith('.')) return file.name.endsWith(rule)
        return file.type === rule
      })
    })
    if (invalids.length) {
      onInvalid && onInvalid(invalids)
      return false
    }
    return true
  }

  const handleFiles = (files) => {
    if (validateFiles(files)) {
      onChange && onChange(files)
    }
  }

  const handleInputChange = (e) => {
    handleFiles(e.target.files)
  }

  const handleDrop = (e) => {
    e.preventDefault()
    handleFiles(e.dataTransfer.files)
  }

  const triggerSelect = () => {
    inputRef.current?.click()
  }

  const baseWrapperStyle = {
    cursor: 'pointer',
    ...style,
  }

  const variantStyles = {
    block: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 32,
      border: '2px dashed var(--color-border,#d1d5db)',
      borderRadius: 8,
      background: 'var(--color-gray-50,#f9fafb)',
      textAlign: 'center',
    },
    button: {
      display: 'inline-flex',
      padding: '8px 16px',
      borderRadius: 6,
      background: 'var(--color-primary,#3b82f6)',
      color: '#fff',
      border: 'none',
      fontWeight: 500,
      alignItems: 'center',
      justifyContent: 'center',
    },
    icon: {
      display: 'inline-flex',
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      border: '1px solid var(--color-border,#d1d5db)',
      borderRadius: '50%',
      background: 'var(--color-gray-50,#f9fafb)',
      fontSize: 18,
    },
  }

  const wrapperStyle = { ...baseWrapperStyle, ...variantStyles[variant] }

  const renderContent = () => {
    switch (variant) {
      case 'button':
        return label
      case 'icon':
        return '⬆️'
      default:
        return <strong>{label}</strong>
    }
  }

  return (
    <label
      className={`wc-file-input-wrapper variant-${variant} ${className}`}
      style={wrapperStyle}
      onDragOver={(e) => e.preventDefault()}
      onDrop={handleDrop}
      onClick={variant !== 'block' ? triggerSelect : undefined}
    >
      <input
        ref={inputRef}
        type="file"
        multiple={multiple}
        accept={accept}
        style={{ display: 'none' }}
        onChange={handleInputChange}
      />
      {variant === 'block' ? (
        <div className="wc-file-input-content">{renderContent()}</div>
      ) : (
        renderContent()
      )}
    </label>
  )
}

FileInput.displayName = 'FileInput'

export default FileInput
