// src/components/Paradox/Paradox.vue
<template>
  <div
    :class="paradoxClasses"
    :title="tooltip"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <slot>{{ content }}</slot>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'

const props = defineProps({
  /** 显示的悖论文本 */
  content: {
    type: String,
    default: '这句话是假。'
  },
  /** 鼠标悬停提示 */
  tooltip: {
    type: String,
    default: '若此句为真，则为假；若此句为假，则为真。'
  },
  /** 是否启用动画 */
  animated: {
    type: Boolean,
    default: false
  },
  /** 变换类型 */
  transform: {
    type: String,
    default: 'none',
    validator: (value: string) => ['none', 'rotate', 'scale', 'skew'].includes(value)
  },
  /** 动画速度 */
  speed: {
    type: String,
    default: 'normal',
    validator: (value: string) => ['slow', 'normal', 'fast'].includes(value)
  },
  /** 是否启用悬停效果 */
  hoverEffect: {
    type: Boolean,
    default: false
  },
  /** 是否无限循环 */
  infinite: {
    type: Boolean,
    default: false
  },
  /** 尺寸变体 */
  size: {
    type: String,
    default: 'md',
    validator: (value: string) => ['sm', 'md', 'lg', 'xl'].includes(value)
  },
  /** 样式变体 */
  variant: {
    type: String,
    default: 'primary',
    validator: (value: string) => ['primary', 'success', 'warning', 'error', 'info'].includes(value)
  },
  /** 边框样式 */
  borderStyle: {
    type: String,
    default: 'left',
    validator: (value: string) => ['left', 'top', 'bottom', 'right', 'all'].includes(value)
  },
  /** 是否显示引用符号 */
  withQuotes: {
    type: Boolean,
    default: false
  },
  /** 是否启用发光效果 */
  glow: {
    type: Boolean,
    default: false
  },
  /** 是否启用渐变背景 */
  gradient: {
    type: Boolean,
    default: false
  },
  /** 自定义CSS类名 */
  className: {
    type: String,
    default: ''
  }
})

const isHovered = ref(false)
const isPaused = ref(false)
const currentFrame = ref(0)
let animationId: number | null = null

const paradoxClasses = computed(() => {
  const classes = ['wc-paradox']
  
  if (props.animated) {
    classes.push('wc-paradox--animated')
  }
  
  if (props.transform !== 'none') {
    classes.push(`wc-paradox--${props.transform}`)
  }
  
  if (props.speed !== 'normal') {
    classes.push(`wc-paradox--${props.speed}`)
  }
  
  if (props.hoverEffect && isHovered.value) {
    classes.push('wc-paradox--hover')
  }
  
  if (props.size !== 'md') {
    classes.push(`wc-paradox--${props.size}`)
  }
  
  if (props.variant !== 'primary') {
    classes.push(`wc-paradox--${props.variant}`)
  }
  
  if (props.borderStyle !== 'left') {
    classes.push(`wc-paradox--border-${props.borderStyle}`)
  }
  
  if (props.withQuotes) {
    classes.push('wc-paradox--with-quotes')
  }
  
  if (props.glow) {
    classes.push('wc-paradox--glow')
  }
  
  if (props.gradient) {
    classes.push('wc-paradox--gradient')
  }
  
  if (props.className) {
    classes.push(props.className)
  }
  
  return classes.join(' ')
})

const handleMouseEnter = () => {
  if (props.hoverEffect) {
    isHovered.value = true
  }
}

const handleMouseLeave = () => {
  if (props.hoverEffect) {
    isHovered.value = false
  }
}

const startAnimation = () => {
  if (props.animated && !isPaused.value && props.infinite) {
    const animate = () => {
      currentFrame.value = (currentFrame.value + 1) % 360
      if (!isPaused.value) {
        animationId = requestAnimationFrame(animate)
      }
    }
    animationId = requestAnimationFrame(animate)
  }
}

const pause = () => {
  isPaused.value = true
  if (animationId) {
    cancelAnimationFrame(animationId)
    animationId = null
  }
}

const resume = () => {
  isPaused.value = false
  startAnimation()
}

const reset = () => {
  currentFrame.value = 0
  if (animationId) {
    cancelAnimationFrame(animationId)
    animationId = null
  }
}

// 暴露方法给测试
defineExpose({
  pause,
  resume,
  reset,
  isPaused,
  currentFrame,
  infinite: computed(() => props.infinite)
})

onMounted(() => {
  if (props.animated && props.infinite) {
    startAnimation()
  }
})

onUnmounted(() => {
  if (animationId) {
    cancelAnimationFrame(animationId)
  }
})
</script>

<style>
/* 引入外部样式文件 */
@import './style.css';
</style>

// src/components/Paradox/Paradox.jsx
import React, { useState, useEffect, useRef } from 'react'

/**
 * Paradox – 显示悖论文本
 * Props
 *  content       string  悖论文本
 *  tooltip       string  悬停提示
 *  animated      boolean 是否启用动画
 *  transform     string  变换类型 (none, rotate, scale, skew)
 *  speed         string  动画速度 (slow, normal, fast)
 *  hoverEffect   boolean 是否启用悬停效果
 *  infinite      boolean 是否无限循环
 *  size          string  尺寸变体 (sm, md, lg, xl)
 *  variant       string  样式变体 (primary, success, warning, error, info)
 *  borderStyle   string  边框样式 (left, top, bottom, right, all)
 *  withQuotes    boolean 是否显示引用符号
 *  glow          boolean 是否启用发光效果
 *  gradient      boolean 是否启用渐变背景
 *  className     string  自定义CSS类名
 */
export default function Paradox({ 
  content = '这句话是假。', 
  tooltip = '若此句为真，则为假；若此句为假，则为真。',
  animated = false,
  transform = 'none',
  speed = 'normal',
  hoverEffect = false,
  infinite = false,
  size = 'md',
  variant = 'primary',
  borderStyle = 'left',
  withQuotes = false,
  glow = false,
  gradient = false,
  className = '',
  children
}) {
  const [isHovered, setIsHovered] = useState(false)
  const [isPaused, setIsPaused] = useState(false)
  const [currentFrame, setCurrentFrame] = useState(0)
  const animationRef = useRef(null)

  const paradoxClasses = [
    'wc-paradox',
    animated && 'wc-paradox--animated',
    transform !== 'none' && `wc-paradox--${transform}`,
    speed !== 'normal' && `wc-paradox--${speed}`,
    hoverEffect && isHovered && 'wc-paradox--hover',
    size !== 'md' && `wc-paradox--${size}`,
    variant !== 'primary' && `wc-paradox--${variant}`,
    borderStyle !== 'left' && `wc-paradox--border-${borderStyle}`,
    withQuotes && 'wc-paradox--with-quotes',
    glow && 'wc-paradox--glow',
    gradient && 'wc-paradox--gradient',
    className
  ].filter(Boolean).join(' ')

  const handleMouseEnter = () => {
    if (hoverEffect) {
      setIsHovered(true)
    }
  }

  const handleMouseLeave = () => {
    if (hoverEffect) {
      setIsHovered(false)
    }
  }

  const startAnimation = () => {
    if (animated && !isPaused && infinite) {
      const animate = () => {
        setCurrentFrame(prev => (prev + 1) % 360)
        if (!isPaused) {
          animationRef.current = requestAnimationFrame(animate)
        }
      }
      animationRef.current = requestAnimationFrame(animate)
    }
  }

  const pause = () => {
    setIsPaused(true)
    if (animationRef.current) {
      cancelAnimationFrame(animationRef.current)
      animationRef.current = null
    }
  }

  const resume = () => {
    setIsPaused(false)
    startAnimation()
  }

  const reset = () => {
    setCurrentFrame(0)
    if (animationRef.current) {
      cancelAnimationFrame(animationRef.current)
      animationRef.current = null
    }
  }

  useEffect(() => {
    if (animated && infinite) {
      startAnimation()
    }

    return () => {
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current)
      }
    }
  }, [animated, infinite])

  return (
    <div
      className={paradoxClasses}
      title={tooltip}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      {children || content}
    </div>
  )
}
