// src/components/Divider/Divider.vue
<template>
  <component
    :is="children ? 'div' : 'hr'"
    :class="[dividerClasses, { 'wc-divider--with-text': children }]"
  >
    <span v-if="children" class="wc-divider__text">
      <slot />
    </span>
  </component>
</template>

<script setup>
import { computed, useSlots } from 'vue'
import { getDividerClasses, validVariants, validOrientations } from './utils.js'
import './style.css'

const props = defineProps({
  variant: {
    type: String,
    default: 'solid',
    validator: (value) => validVariants.includes(value)
  },
  orientation: {
    type: String,
    default: 'horizontal',
    validator: (value) => validOrientations.includes(value)
  },
  flexItem: {
    type: Boolean,
    default: false
  }
})

const slots = useSlots()
const children = computed(() => !!slots.default)

const dividerClasses = computed(() =>
  getDividerClasses({
    variant: props.variant,
    orientation: props.orientation,
    flexItem: props.flexItem,
    className: ''
  })
)
</script>

<style scoped>
</style>

// src/components/Divider/Divider.jsx
import React from 'react'
import './style.css'
import { getDividerClasses } from './utils.js'

const Divider = ({
  variant = 'solid',
  orientation = 'horizontal',
  className = '',
  children = '',
  flexItem = false,
  ...props
}) => {
  const dividerClasses = getDividerClasses({
    variant,
    orientation,
    flexItem,
    className
  })

  // 如果有 children，使用 flex 布局来居中文字
  if (children) {
    return (
      <div className={`${dividerClasses} wc-divider--with-text`} {...props}>
        <span className="wc-divider__text">{children}</span>
      </div>
    )
  }

  return <hr className={dividerClasses} {...props} />
}

Divider.displayName = 'Divider'

export default Divider
