// src/components/Modal/Modal.jsx
import React, { useState, useEffect } from 'react'
import { createPortal } from 'react-dom'

const Modal = ({
  visible = false,
  title = '',
  size = 'md',
  closable = true,
  maskClosable = true,
  centered = false,
  onClose,
  children,
  header,
  footer,
  className = '',
  ...props
}) => {
  const [isVisible, setIsVisible] = useState(visible)

  useEffect(() => {
    setIsVisible(visible)
  }, [visible])

  const modalClasses = [
    'wc-modal',
    `wc-modal--${size}`,
    centered ? 'wc-modal--centered' : '',
    className
  ].filter(Boolean).join(' ')

  const handleClose = () => {
    setIsVisible(false)
    if (onClose) {
      setTimeout(() => {
        onClose()
      }, 300)
    }
  }

  const handleOverlayClick = () => {
    if (maskClosable) {
      handleClose()
    }
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Escape' && closable) {
      handleClose()
    }
  }

  useEffect(() => {
    if (isVisible) {
      document.addEventListener('keydown', handleKeyDown)
      return () => {
        document.removeEventListener('keydown', handleKeyDown)
      }
    }
  }, [isVisible, closable])

  if (!isVisible) return null

  const modalContent = (
    <div 
      className="wc-modal-overlay" 
      onClick={handleOverlayClick}
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
        padding: '20px'
      }}
    >
      <div
        className={modalClasses}
        onClick={(e) => e.stopPropagation()}
        style={{
          backgroundColor: '#ffffff',
          borderRadius: '16px',
          boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
          width: '100%',
          position: 'relative',
          maxHeight: '90vh',
          overflowY: 'auto',
          maxWidth: size === 'sm' ? '400px' : 
                   size === 'md' ? '500px' : 
                   size === 'lg' ? '700px' : 
                   size === 'xl' ? '900px' : '500px'
        }}
        {...props}
      >
        {/* 头部 */}
        {(title || header || closable) && (
          <div 
            className="wc-modal__header"
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '24px 24px 0 24px',
              borderBottom: '1px solid #e4e4e7',
              marginBottom: '24px',
              paddingBottom: '16px'
            }}
          >
            {header || (
              title && (
                <h3 
                  className="wc-modal__title"
                  style={{
                    fontSize: '20px',
                    fontWeight: '600',
                    color: '#18181b',
                    margin: 0
                  }}
                >
                  {title}
                </h3>
              )
            )}
            {closable && (
              <button
                className="wc-modal__close"
                onClick={handleClose}
                style={{
                  background: 'none',
                  border: 'none',
                  fontSize: '24px',
                  cursor: 'pointer',
                  color: '#71717a',
                  transition: 'color 0.2s ease',
                  padding: 0,
                  lineHeight: 1
                }}
              >
                ×
              </button>
            )}
          </div>
        )}

        {/* 内容 */}
        <div 
          className="wc-modal__body"
          style={{
            padding: '0 24px',
            color: '#3f3f46',
            lineHeight: 1.6
          }}
        >
          {children}
        </div>

        {/* 底部 */}
        {footer && (
          <div 
            className="wc-modal__footer"
            style={{
              display: 'flex',
              justifyContent: 'flex-end',
              gap: '12px',
              padding: '24px 24px 24px 24px',
              borderTop: '1px solid #e4e4e7',
              marginTop: '24px',
              paddingTop: '16px'
            }}
          >
            {footer}
          </div>
        )}
      </div>
    </div>
  )

  return createPortal(modalContent, document.body)
}

Modal.displayName = 'Modal'

export default Modal

// src/components/Modal/Modal.vue
<template>
  <Teleport to="body">
    <Transition name="modal" appear>
      <div v-if="modelValue" class="wc-modal-overlay" @click="handleOverlayClick">
        <div :class="modalClasses" :style="modalStyles" @click.stop>
          <!-- 头部 -->
          <div v-if="title || $slots.header || closable" class="wc-modal__header">
            <slot name="header">
              <h3 v-if="title" class="wc-modal__title">{{ title }}</h3>
            </slot>
            <button
              v-if="closable"
              class="wc-modal__close"
              @click="handleClose"
            >
              ×
            </button>
          </div>

          <!-- 内容 -->
          <div class="wc-modal__body">
            <slot />
          </div>

          <!-- 底部 -->
          <div v-if="$slots.footer" class="wc-modal__footer">
            <slot name="footer" />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
import { computed, watch } from 'vue'

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  },
  title: {
    type: String,
    default: ''
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg', 'xl'].includes(value)
  },
  closable: {
    type: Boolean,
    default: true
  },
  maskClosable: {
    type: Boolean,
    default: true
  },
  centered: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['update:modelValue', 'close'])

const modalClasses = computed(() => {
  return ['wc-modal', `wc-modal--${props.size}`, {
    'wc-modal--centered': props.centered
  }]
})

const modalStyles = computed(() => ({
  maxHeight: '90vh',
  overflowY: 'auto'
}))

const handleClose = () => {
  emit('update:modelValue', false)
  emit('close')
}

const handleOverlayClick = () => {
  if (props.maskClosable) {
    handleClose()
  }
}

// 监听 Escape 键
watch(() => props.modelValue, (newVal) => {
  if (newVal) {
    const handleEscape = (e) => {
      if (e.key === 'Escape' && props.closable) {
        handleClose()
      }
    }
    document.addEventListener('keydown', handleEscape)
    
    // 清理监听器
    return () => {
      document.removeEventListener('keydown', handleEscape)
    }
  }
})
</script>

<style scoped>
.wc-modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.wc-modal {
  background-color: #ffffff;
  border-radius: 16px;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
  width: 100%;
  position: relative;
}

.wc-modal--sm {
  max-width: 400px;
}

.wc-modal--md {
  max-width: 500px;
}

.wc-modal--lg {
  max-width: 700px;
}

.wc-modal--xl {
  max-width: 900px;
}

.wc-modal--centered {
  margin: auto;
}

.wc-modal__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 24px 24px 16px 24px;
  border-bottom: 1px solid #e4e4e7;
}

.wc-modal__title {
  font-size: 20px;
  font-weight: 600;
  color: #18181b;
  margin: 0;
}

.wc-modal__close {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  color: #71717a;
  transition: color 0.2s ease;
  padding: 0;
  line-height: 1;
}

.wc-modal__close:hover {
  color: #3f3f46;
}

.wc-modal__body {
  padding: 24px;
  color: #3f3f46;
  line-height: 1.6;
  min-height: 40px;
}

.wc-modal__footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 16px 24px 24px 24px;
  border-top: 1px solid #e4e4e7;
}

/* 动画效果 */
.modal-enter-active,
.modal-leave-active {
  transition: all 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-from .wc-modal,
.modal-leave-to .wc-modal {
  transform: scale(0.9) translateY(-20px);
}

/* 深色模式 */
@media (prefers-color-scheme: dark) {
  .wc-modal {
    background-color: #18181b;
  }
  
  .wc-modal__header {
    border-bottom-color: #3f3f46;
  }
  
  .wc-modal__title {
    color: #fafafa;
  }
  
  .wc-modal__close {
    color: #a1a1aa;
  }
  
  .wc-modal__close:hover {
    color: #d4d4d8;
  }
  
  .wc-modal__body {
    color: #d4d4d8;
  }
  
  .wc-modal__footer {
    border-top-color: #3f3f46;
  }
}
</style>
