// packages/vue/src/components/AppBar/AppBar.vue
<template>
  <div :class="['wc-appbar', `wc-appbar--${props.position}`, `wc-appbar--${props.color}`, `wc-appbar--elevation-${props.elevation}`, `wc-appbar--${props.variant}`, props.class]" :style="style">
    <slot />
  </div>
</template>

<script setup>
import './style.css'

const props = defineProps({
  position: {
    type: String,
    default: 'fixed',
    validator: (v) => ['fixed', 'absolute', 'sticky', 'static', 'relative'].includes(v)
  },
  color: {
    type: String,
    default: 'default',
    validator: (v) => ['default', 'primary', 'secondary', 'transparent', 'inherit'].includes(v)
  },
  elevation: {
    type: Number,
    default: 0,
  },
  variant: {
    type: String,
    default: 'elevation',
    validator: (v) => ['elevation', 'outlined'].includes(v)
  },
  class: {
    type: [String, Array, Object],
    default: ''
  },
  style: {
    type: [String, Object],
    default: () => ({})
  }
})
</script>

// packages/react/src/components/AppBar/AppBar.jsx
import React from 'react'
import './style.css'

const AppBar = ({
  children,
  position = 'fixed',
  color = 'default',
  elevation = 4,
  variant = 'elevation',
  className = '',
  style = {},
  ...rest
}) => {
  const classes = `wc-appbar wc-appbar--${position} wc-appbar--${color} wc-appbar--elevation-${elevation} wc-appbar--${variant} ${className}`

  return (
    <div className={classes} style={style} {...rest}>
      {children}
    </div>
  )
}

export default AppBar
