// packages/react/src/components/Autocomplete/Autocomplete.jsx
import React, { useState, useRef, useEffect, useId } from 'react'
import { useOverlayLayer } from '../../interactions.jsx'
import './style.css'

const Autocomplete = ({
  value = null,
  onChange,
  options = [],
  placeholder = 'Type to search...',
  label = '',
  helperText = '',
  error = false,
  errorMessage = '',
  required = false,
  disabled = false,
  readonly = false,
  multiple = false,
  freeSolo = false,
  clearable = true,
  fullWidth = false,
  size = 'md',
  variant = 'filled',
  minSearchLength = 0,
  noOptionsText = 'No options found',
  name = '',
  id = '',
  className = '',
  style = {},
  onFocus,
  onBlur,
  onInputChange,
  filterOptions,
  renderOption,
  renderInput,
  getOptionLabel,
  getOptionValue,
  ...props
}) => {
  const [isOpen, setIsOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [highlightedIndex, setHighlightedIndex] = useState(-1)
  const autocompleteRef = useRef(null)
  const inputRef = useRef(null)
  const dropdownRef = useRef(null)

  // Default functions
  const defaultGetOptionLabel = (option) => {
    if (!option) return ''
    return typeof option === 'object' ? (option.label || option.value || '') : String(option)
  }

  const defaultGetOptionValue = (option) => {
    if (!option) return null
    return typeof option === 'object' ? (option.value !== undefined ? option.value : option) : option
  }

  const getLabel = getOptionLabel || defaultGetOptionLabel
  const getValue = getOptionValue || defaultGetOptionValue

  // Initialize search query from value
  useEffect(() => {
    if (!multiple && value) {
      setSearchQuery(getLabel(value))
    } else if (!value) {
      setSearchQuery('')
    }
  }, [value, multiple])

  const closeDropdown = () => {
    setIsOpen(false)
    setHighlightedIndex(-1)
  }

  useOverlayLayer({
    open: isOpen,
    elementRef: dropdownRef,
    refs: [autocompleteRef],
    closeOnEscape: true,
    closeOnPointerDownOutside: true,
    onEscapeKeyDown: closeDropdown,
    onPointerDownOutside: closeDropdown,
    zIndex: 1000,
  })

  const defaultFilterOptions = (options, query) => {
    if (!query || query.length < minSearchLength) {
      return options
    }
    return options.filter(option => 
      getLabel(option).toLowerCase().includes(query.toLowerCase())
    )
  }

  const filteredOptions = filterOptions 
    ? filterOptions(options, searchQuery)
    : defaultFilterOptions(options, searchQuery)

  const isSelected = (option) => {
    const optionValue = getValue(option)
    if (multiple && Array.isArray(value)) {
      return value.some(v => getValue(v) === optionValue)
    }
    return getValue(value) === optionValue
  }

  const getAutocompleteClasses = () => {
    const classes = ['wc-autocomplete']
    if (fullWidth) classes.push('wc-autocomplete--full-width')
    return classes.concat(className).filter(Boolean).join(' ')
  }

  const getLabelClasses = () => {
    const classes = ['wc-autocomplete__label']
    classes.push(`wc-autocomplete__label--${size}`)
    if (error) classes.push('wc-autocomplete__label--error')
    return classes.join(' ')
  }

  const getContainerClasses = () => {
    const classes = ['wc-autocomplete__container']
    classes.push(`wc-autocomplete__container--${variant}`)
    classes.push(`wc-autocomplete__container--${size}`)
    if (disabled) classes.push('wc-autocomplete__container--disabled')
    if (error) classes.push('wc-autocomplete__container--error')
    if (isOpen) classes.push('wc-autocomplete__container--open')
    return classes.join(' ')
  }

  const getOptionClasses = (option, index) => {
    const classes = ['wc-autocomplete__option']
    if (isSelected(option)) classes.push('wc-autocomplete__option--selected')
    if (index === highlightedIndex) classes.push('wc-autocomplete__option--highlighted')
    if (option.disabled) classes.push('wc-autocomplete__option--disabled')
    return classes.join(' ')
  }

  const handleFocus = (e) => {
    setIsOpen(true)
    onFocus?.(e)
  }

  const handleBlur = (e) => {
    setTimeout(() => {
      setIsOpen(false)
      onBlur?.(e)
    }, 200)
  }

  const handleInputChange = (e) => {
    const query = e.target.value
    setSearchQuery(query)
    setIsOpen(true)
    setHighlightedIndex(-1)
    onInputChange?.(query)

    if (freeSolo) {
      onChange?.({ target: { name, value: query } })
    }
  }

  const handleClear = (e) => {
    e.stopPropagation()
    setSearchQuery('')
    closeDropdown()
    const newValue = multiple ? [] : null
    onChange?.({ target: { name, value: newValue } })
  }

  const handleOptionClick = (option) => {
    if (option.disabled) return

    const optionValue = getValue(option)
    let newValue

    if (multiple) {
      const currentValues = Array.isArray(value) ? [...value] : []
      const index = currentValues.findIndex(v => getValue(v) === optionValue)
      
      if (index > -1) {
        currentValues.splice(index, 1)
      } else {
        currentValues.push(option)
      }
      newValue = currentValues
      setSearchQuery('')
    } else {
      newValue = option
      setSearchQuery(getLabel(option))
      closeDropdown()
    }

    setHighlightedIndex(-1)
    onChange?.({ target: { name, value: newValue } })
  }

  const handleKeyDown = (e) => {
    if (!isOpen && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
      setIsOpen(true)
      e.preventDefault()
      return
    }

    if (!isOpen || filteredOptions.length === 0) return

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault()
        setHighlightedIndex(prev => 
          Math.min(prev + 1, filteredOptions.length - 1)
        )
        break
      case 'ArrowUp':
        e.preventDefault()
        setHighlightedIndex(prev => Math.max(prev - 1, 0))
        break
      case 'Enter':
        e.preventDefault()
        if (highlightedIndex >= 0 && highlightedIndex < filteredOptions.length) {
          handleOptionClick(filteredOptions[highlightedIndex])
        }
        break
      case 'Escape':
        closeDropdown()
        inputRef.current?.blur()
        break
      default:
        break
    }
  }

  const generatedId = useId()
  const autocompleteId = id || name || generatedId

  return (
    <div className={getAutocompleteClasses()} ref={autocompleteRef} style={style}>
      {label && (
        <label
          htmlFor={autocompleteId}
          className={getLabelClasses()}
        >
          {label}
          {required && <span className="wc-autocomplete__required">*</span>}
        </label>
      )}
      
      <div className={getContainerClasses()}>
        {renderInput ? (
          renderInput({
            id: autocompleteId,
            value: searchQuery,
            onChange: handleInputChange,
            onFocus: handleFocus,
            onBlur: handleBlur,
            onKeyDown: handleKeyDown,
            placeholder,
            disabled,
            readonly,
            ref: inputRef,
            role: 'combobox',
            'aria-autocomplete': 'list',
            'aria-expanded': isOpen,
            'aria-controls': `${autocompleteId}-options`,
            'aria-activedescendant': highlightedIndex >= 0 ? `${autocompleteId}-option-${highlightedIndex}` : undefined
          })
        ) : (
          <input
            id={autocompleteId}
            ref={inputRef}
            type="text"
            className="wc-autocomplete__input"
            placeholder={placeholder}
            value={searchQuery}
            onChange={handleInputChange}
            onFocus={handleFocus}
            onBlur={handleBlur}
            onKeyDown={handleKeyDown}
            disabled={disabled}
            readOnly={readonly}
            autoComplete="off"
            role="combobox"
            aria-autocomplete="list"
            aria-expanded={isOpen}
            aria-controls={`${autocompleteId}-options`}
            aria-activedescendant={highlightedIndex >= 0 ? `${autocompleteId}-option-${highlightedIndex}` : undefined}
          />
        )}
        
        <div className="wc-autocomplete__indicators">
          {clearable && searchQuery && (
            <button
              type="button"
              className="wc-autocomplete__clear"
              onClick={handleClear}
              tabIndex={-1}
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
            </button>
          )}
          <div className={`wc-autocomplete__arrow${isOpen && filteredOptions.length > 0 ? ' wc-autocomplete__arrow--open' : ''}`}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="6,9 12,15 18,9" />
            </svg>
          </div>
        </div>
      </div>

      {isOpen && searchQuery.length >= minSearchLength && (
        <div ref={dropdownRef} className="wc-autocomplete__dropdown" id={`${autocompleteId}-options`} role="listbox">
          {filteredOptions.length === 0 ? (
            <div className="wc-autocomplete__no-options">
              {noOptionsText}
            </div>
          ) : (
            <div className="wc-autocomplete__options">
              {filteredOptions.map((option, index) => (
                <div
                  key={getValue(option) || index}
                  id={`${autocompleteId}-option-${index}`}
                  className={getOptionClasses(option, index)}
                  role="option"
                  aria-selected={isSelected(option)}
                  onClick={() => handleOptionClick(option)}
                  onMouseEnter={() => setHighlightedIndex(index)}
                >
                  {renderOption ? (
                    renderOption(option, { selected: isSelected(option) })
                  ) : (
                    <span className="wc-autocomplete__option-text">
                      {getLabel(option)}
                    </span>
                  )}
                  {isSelected(option) && (
                    <svg 
                      className="wc-autocomplete__option-check" 
                      viewBox="0 0 24 24" 
                      fill="none" 
                      stroke="currentColor" 
                      strokeWidth="2"
                    >
                      <polyline points="20,6 9,17 4,12" />
                    </svg>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {(error || helperText) && (
        <div>
          {error ? (
            <p className="wc-autocomplete__error">{errorMessage || error}</p>
          ) : (
            <p className="wc-autocomplete__helper">{helperText}</p>
          )}
        </div>
      )}
    </div>
  )
}

Autocomplete.displayName = 'Autocomplete'

export default Autocomplete

// packages/vue/src/components/Autocomplete/Autocomplete.vue
<template>
  <div ref="autocompleteRef" class="wc-autocomplete">
    <!-- Label -->
    <label 
      v-if="label" 
      :for="autocompleteId" 
      :class="labelClasses"
    >
      {{ label }}
      <span
        v-if="required"
        class="wc-autocomplete__required"
      >*</span>
    </label>
    
    <!-- Input Container -->
    <div
      :class="inputContainerClasses"
    >
      <!-- Input -->
      <input
        :id="autocompleteId"
        v-model="searchQuery"
        type="text"
        :placeholder="placeholder"
        :disabled="disabled"
        :readonly="readonly"
        class="wc-autocomplete__input"
        autocomplete="off"
        role="combobox"
        aria-autocomplete="list"
        :aria-expanded="open"
        :aria-controls="`${autocompleteId}-options`"
        :aria-activedescendant="highlightedIndex >= 0 ? `${autocompleteId}-option-${highlightedIndex}` : undefined"
        @focus="handleFocus"
        @blur="handleBlur"
        @input="handleInput"
        @keydown="handleKeydown"
      >
      
      <!-- Clear Button -->
      <button
        v-if="clearable && searchQuery"
        type="button"
        class="wc-autocomplete__clear"
        @click="handleClear"
        tabindex="-1"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="10" />
          <line x1="15" y1="9" x2="9" y2="15" />
          <line x1="9" y1="9" x2="15" y2="15" />
        </svg>
      </button>
      
      <!-- Arrow Icon -->
      <div class="wc-autocomplete__indicators">
        <div :class="['wc-autocomplete__arrow', { 'wc-autocomplete__arrow--open': open && filteredOptions.length > 0 }]">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <polyline points="6,9 12,15 18,9" />
          </svg>
        </div>
      </div>
    </div>
    
    <!-- Dropdown -->
    <div
      v-if="open && filteredOptions.length > 0"
      ref="dropdownRef"
      class="wc-autocomplete__dropdown"
      :id="`${autocompleteId}-options`"
      role="listbox"
    >
      <div class="wc-autocomplete__options">
        <div
          v-for="(option, index) in filteredOptions"
          :key="getOptionValue(option)"
          :id="`${autocompleteId}-option-${index}`"
          :class="getOptionClasses(option, index)"
          role="option"
          :aria-selected="isSelected(option)"
          @click="selectOption(option)"
          @mouseenter="highlightedIndex = index"
        >
          <slot name="option" :option="option">
            <span class="wc-autocomplete__option-text">{{ getOptionLabel(option) }}</span>
          </slot>
          <svg
            v-if="isSelected(option)"
            class="wc-autocomplete__option-check"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="20,6 9,17 4,12" />
          </svg>
        </div>
      </div>
    </div>
    
    <!-- No Results -->
    <div
      v-if="open && searchQuery && filteredOptions.length === 0"
      ref="dropdownRef"
      class="wc-autocomplete__dropdown"
      role="status"
    >
      <div class="wc-autocomplete__no-options">
        <slot name="no-options">
          {{ noOptionsText }}
        </slot>
      </div>
    </div>
    
    <!-- Helper Text / Error -->
    <div v-if="error || helperText">
      <p
        v-if="error"
        class="wc-autocomplete__error"
      >
        {{ error }}
      </p>
      <p
        v-else-if="helperText"
        class="wc-autocomplete__helper"
      >
        {{ helperText }}
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, getCurrentInstance, watch } from 'vue'
import { useOverlayLayer } from '../../interactions'
import './style.css'

const props = defineProps({
  modelValue: {
    type: [String, Number, Object, Array],
    default: null
  },
  options: {
    type: Array,
    default: () => []
  },
  label: {
    type: String,
    default: ''
  },
  placeholder: {
    type: String,
    default: '请输入或选择...'
  },
  disabled: {
    type: Boolean,
    default: false
  },
  readonly: {
    type: Boolean,
    default: false
  },
  required: {
    type: Boolean,
    default: false
  },
  error: {
    type: String,
    default: ''
  },
  helperText: {
    type: String,
    default: ''
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  },
  variant: {
    type: String,
    default: 'filled',
    validator: (value) => ['outlined', 'filled', 'standard'].includes(value)
  },
  multiple: {
    type: Boolean,
    default: false
  },
  clearable: {
    type: Boolean,
    default: true
  },
  freeSolo: {
    type: Boolean,
    default: false
  },
  valueKey: {
    type: String,
    default: 'value'
  },
  labelKey: {
    type: String,
    default: 'label'
  },
  filterOptions: {
    type: Function,
    default: null
  },
  noOptionsText: {
    type: String,
    default: '没有找到选项'
  },
  minSearchLength: {
    type: Number,
    default: 0
  }
})

const emit = defineEmits(['update:modelValue', 'change', 'input-change', 'focus', 'blur'])

const instance = getCurrentInstance()
const autocompleteId = ref(`autocomplete-${instance?.uid || Math.random().toString(36).substr(2, 9)}`)
const open = ref(false)
const searchQuery = ref('')
const highlightedIndex = ref(-1)
const autocompleteRef = ref(null)
const dropdownRef = ref(null)

const closeDropdown = () => {
  open.value = false
  highlightedIndex.value = -1
}

const labelClasses = computed(() => {
  const classes = ['wc-autocomplete__label']
  
  classes.push(`wc-autocomplete__label--${props.size}`)
  
  if (props.error) {
    classes.push('wc-autocomplete__label--error')
  }
  
  return classes
})

const inputContainerClasses = computed(() => {
  const classes = ['wc-autocomplete__container']
  
  classes.push(`wc-autocomplete__container--${props.variant}`)
  classes.push(`wc-autocomplete__container--${props.size}`)
  
  if (props.disabled) {
    classes.push('wc-autocomplete__container--disabled')
  }
  
  if (props.error) {
    classes.push('wc-autocomplete__container--error')
  }
  
  if (open.value) {
    classes.push('wc-autocomplete__container--open')
  }
  
  return classes
})

const filteredOptions = computed(() => {
  if (searchQuery.value.length < props.minSearchLength) {
    return []
  }
  
  if (props.filterOptions) {
    return props.filterOptions(props.options, searchQuery.value)
  }
  
  if (!searchQuery.value) {
    return props.options
  }
  
  return props.options.filter(option => {
    const label = getOptionLabel(option).toLowerCase()
    return label.includes(searchQuery.value.toLowerCase())
  })
})

const getOptionValue = (option) => {
  if (!option) return null
  return typeof option === 'object' ? option[props.valueKey] : option
}

const getOptionLabel = (option) => {
  if (!option) return ''
  return typeof option === 'object' ? option[props.labelKey] : option
}

const isSelected = (option) => {
  const value = getOptionValue(option)
  if (props.multiple && Array.isArray(props.modelValue)) {
    return props.modelValue.some(v => 
      (typeof v === 'object' ? getOptionValue(v) : v) === value
    )
  }
  if (!props.modelValue) return false
  const currentValue = typeof props.modelValue === 'object' 
    ? getOptionValue(props.modelValue) 
    : props.modelValue
  return currentValue === value
}

const getOptionClasses = (option, index) => {
  const classes = ['wc-autocomplete__option']
  
  if (isSelected(option)) {
    classes.push('wc-autocomplete__option--selected')
  }
  
  if (index === highlightedIndex.value) {
    classes.push('wc-autocomplete__option--highlighted')
  }
  
  return classes
}

const handleFocus = (e) => {
  open.value = true
  emit('focus', e)
}

const handleBlur = (e) => {
  setTimeout(() => {
    closeDropdown()
    emit('blur', e)
  }, 200)
}

const handleInput = (e) => {
  open.value = true
  highlightedIndex.value = -1
  emit('input-change', searchQuery.value)
  
  if (props.freeSolo) {
    emit('update:modelValue', searchQuery.value)
    emit('change', searchQuery.value)
  }
}

const handleClear = () => {
  searchQuery.value = ''
  closeDropdown()
  emit('update:modelValue', props.multiple ? [] : null)
  emit('change', props.multiple ? [] : null)
}

const selectOption = (option) => {
  const value = getOptionValue(option)
  const label = getOptionLabel(option)
  
  if (props.multiple) {
    const currentValue = Array.isArray(props.modelValue) ? [...props.modelValue] : []
    const index = currentValue.findIndex(v => 
      (typeof v === 'object' ? getOptionValue(v) : v) === value
    )
    
    if (index > -1) {
      currentValue.splice(index, 1)
    } else {
      currentValue.push(option)
    }
    
    emit('update:modelValue', currentValue)
    emit('change', currentValue)
    searchQuery.value = ''
  } else {
    emit('update:modelValue', option)
    emit('change', option)
    searchQuery.value = label
    closeDropdown()
  }
  
  highlightedIndex.value = -1
}

const handleKeydown = (e) => {
  if (!open.value && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
    open.value = true
    e.preventDefault()
    return
  }
  
  if (!open.value || filteredOptions.value.length === 0) return
  
  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault()
      highlightedIndex.value = Math.min(
        highlightedIndex.value + 1,
        filteredOptions.value.length - 1
      )
      break
    case 'ArrowUp':
      e.preventDefault()
      highlightedIndex.value = Math.max(highlightedIndex.value - 1, 0)
      break
    case 'Enter':
      e.preventDefault()
      if (highlightedIndex.value >= 0 && highlightedIndex.value < filteredOptions.value.length) {
        selectOption(filteredOptions.value[highlightedIndex.value])
      }
      break
    case 'Escape':
      closeDropdown()
      break
  }
}

// Watch modelValue changes to update searchQuery
watch(() => props.modelValue, (newValue) => {
  if (!props.multiple && newValue) {
    if (typeof newValue === 'object') {
      searchQuery.value = getOptionLabel(newValue)
    } else {
      const option = props.options.find(opt => getOptionValue(opt) === newValue)
      searchQuery.value = option ? getOptionLabel(option) : String(newValue)
    }
  } else if (!newValue) {
    searchQuery.value = ''
  }
}, { immediate: true })

useOverlayLayer({
  open,
  elementRef: dropdownRef,
  refs: [autocompleteRef],
  closeOnEscape: true,
  closeOnPointerDownOutside: true,
  onEscapeKeyDown: closeDropdown,
  onPointerDownOutside: closeDropdown,
  zIndex: 1000
})
</script>
