// packages/react/src/components/Menu/Menu.jsx
import React, { useEffect, useId, useRef, useState } from 'react'
import { Portal, useFloatingPosition, useOverlayLayer } from '../../interactions.jsx'
import './style.css'
import {
  getMenuClasses,
  getMenuMenuClasses,
  getMenuButtonClasses,
  getMenuItemClasses,
  getArrowClasses,
  handleMenuToggle,
  handleItemClick,
} from './utils.js'

const normalizePlacement = (placement) => placement.startsWith('top') ? 'top' : 'bottom'

const Menu = ({
  items = [],
  triggerText = '选择选项',
  placement = 'bottom-start',
  size = 'md',
  variant = 'default',
  disabled = false,
  trigger = 'click',
  illustration = '',
  illustrationAlt = '示意图',
  cardTitle = '',
  cardDescription = '',
  onSelect,
  onOpen,
  onClose,
  children,
  triggerContent,
  menuContent,
  className = '',
  ...props
}) => {
  const [isOpen, setIsOpen] = useState(false)
  const menuId = useId()
  const rootRef = useRef(null)
  const panelRef = useRef(null)
  const triggerRef = useRef(null)

  const menuClasses = getMenuClasses({ size, variant, disabled, className }).join(' ')
  const panelClasses = getMenuMenuClasses(placement, variant === 'card' ? 'wc-menu__menu--card' : '').join(' ')
  const buttonClasses = getMenuButtonClasses({ disabled }).join(' ')
  const arrowClasses = getArrowClasses(isOpen).join(' ')

  const menuStyles = variant === 'card' ? { minWidth: '320px', maxWidth: '450px' } : { minWidth: '120px' }

  const handleToggle = () => {
    handleMenuToggle(isOpen, disabled, setIsOpen, onOpen, onClose)
  }

  const handleItemSelect = (item, index) => {
    handleItemClick(item, index, onSelect, setIsOpen, onClose)
  }

  const closeMenu = () => {
    if (!isOpen) return
    setIsOpen(false)
    onClose?.()
  }

  const focusMenuItem = (target = 'first') => {
    const items = Array.from(panelRef.current?.querySelectorAll('[role="menuitem"]:not(:disabled)') || [])
    if (!items.length) return
    const activeIndex = items.indexOf(document.activeElement)
    let nextIndex = target === 'last' ? items.length - 1 : 0
    if (target === 'next') nextIndex = activeIndex < 0 ? 0 : (activeIndex + 1) % items.length
    if (target === 'previous') nextIndex = activeIndex <= 0 ? items.length - 1 : activeIndex - 1
    items[nextIndex]?.focus()
  }

  useEffect(() => {
    if (isOpen) {
      queueMicrotask(() => focusMenuItem('first'))
    }
  }, [isOpen])

  const resolvedPlacement = useFloatingPosition({
    open: isOpen,
    anchorRef: triggerRef,
    floatingRef: panelRef,
    placement: normalizePlacement(placement),
    offset: 6,
  })

  useOverlayLayer({
    open: isOpen,
    elementRef: panelRef,
    refs: [triggerRef],
    closeOnEscape: true,
    closeOnPointerDownOutside: true,
    onEscapeKeyDown: () => {
      closeMenu()
      triggerRef.current?.focus()
    },
    onPointerDownOutside: closeMenu,
    zIndex: 1000,
  })

  const handleTriggerKeyDown = (event) => {
    if (disabled) return
    if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      if (!isOpen) {
        setIsOpen(true)
        onOpen?.()
      } else {
        focusMenuItem('next')
      }
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      if (!isOpen) {
        setIsOpen(true)
        onOpen?.()
        queueMicrotask(() => focusMenuItem('last'))
      } else {
        focusMenuItem('previous')
      }
    }
  }

  const handlePanelKeyDown = (event) => {
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      focusMenuItem('next')
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      focusMenuItem('previous')
    } else if (event.key === 'Home') {
      event.preventDefault()
      focusMenuItem('first')
    } else if (event.key === 'End') {
      event.preventDefault()
      focusMenuItem('last')
    } else if (event.key === 'Tab') {
      closeMenu()
    }
  }

  const menuPanel = isOpen ? (
    <Portal>
      <div
        ref={panelRef}
        className={`${panelClasses} wc-menu__menu--resolved-${resolvedPlacement}`.trim()}
        id={menuId}
        style={menuStyles}
        role="menu"
        onKeyDown={handlePanelKeyDown}
      >
        {menuContent || (
          variant === 'card' ? (
            <div className="wc-menu__card">
              <div className="wc-menu__card-illustration">
                {illustration ? (
                  <img
                    src={illustration}
                    alt={illustrationAlt}
                    className="wc-menu__illustration-image"
                  />
                ) : (
                  <div className="wc-menu__illustration-placeholder">
                    <span>🎨</span>
                  </div>
                )}
                {(cardTitle || cardDescription) && (
                  <div className="wc-menu__card-info">
                    {cardTitle && <h4 className="wc-menu__card-title">{cardTitle}</h4>}
                    {cardDescription && <p className="wc-menu__card-description">{cardDescription}</p>}
                  </div>
                )}
              </div>

              <div className="wc-menu__card-list">
                {items.map((item, index) => {
                  if (item.divider) {
                    return <div key={item.key || index} className="wc-menu__divider" role="separator" />
                  }

                  const itemClasses = getMenuItemClasses(item).join(' ')

                  return (
                    <button
                      type="button"
                      role="menuitem"
                      key={item.key || index}
                      className={itemClasses}
                      disabled={item.disabled}
                      onClick={() => handleItemSelect(item, index)}
                    >
                      {item.icon && (
                        <span className="wc-menu__icon">
                          {item.icon}
                        </span>
                      )}
                      <span className="wc-menu__label">
                        {item.label}
                      </span>
                    </button>
                  )
                })}
              </div>
            </div>
          ) : (
            items.map((item, index) => {
              if (item.divider) {
                return <div key={item.key || index} className="wc-menu__divider" role="separator" />
              }

              const itemClasses = getMenuItemClasses(item).join(' ')

              return (
                <button
                  type="button"
                  role="menuitem"
                  key={item.key || index}
                  className={itemClasses}
                  disabled={item.disabled}
                  onClick={() => handleItemSelect(item, index)}
                >
                  {item.icon && (
                    <span className="wc-menu__icon">
                      {item.icon}
                    </span>
                  )}
                  <span className="wc-menu__label">
                    {item.label}
                  </span>
                </button>
              )
            })
          )
        )}
      </div>
    </Portal>
  ) : null

  return (
    <div className={menuClasses} ref={rootRef} {...props}>
      <div
        className="wc-menu__trigger"
        onClick={handleToggle}
        onKeyDown={handleTriggerKeyDown}
        ref={triggerRef}
      >
        {triggerContent || children || (
          <button
            type="button"
            className={buttonClasses}
            disabled={disabled}
            aria-haspopup="menu"
            aria-expanded={isOpen}
            aria-controls={isOpen ? menuId : undefined}
          >
            {triggerText}
            <span className={arrowClasses}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="6,9 12,15 18,9" />
              </svg>
            </span>
          </button>
        )}
      </div>

      {menuPanel}
    </div>
  )
}

Menu.displayName = 'Menu'

export default Menu

// packages/vue/src/components/Menu/Menu.vue
<template>
  <div
    ref="menuRef"
    class="wc-menu"
  >
    <div
      ref="triggerRef"
      class="wc-menu__trigger"
      @click="handleToggle"
      @keydown="handleTriggerKeydown"
    >
      <slot name="trigger">
        <button
          type="button"
          class="wc-menu__button"
          :disabled="disabled"
          aria-haspopup="menu"
          :aria-expanded="isOpen"
        >
          {{ triggerText }}
          <span :class="['wc-menu__arrow', { 'wc-menu__arrow--open': isOpen }]">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polyline points="6,9 12,15 18,9" />
            </svg>
          </span>
        </button>
      </slot>
    </div>

    <Transition name="menu">
      <div
        v-if="isOpen"
        ref="panelRef"
        :class="menuClasses"
        :style="menuStyles"
        role="menu"
        @keydown="handlePanelKeydown"
      >
        <slot name="content">
          <div v-if="variant === 'card'" class="wc-menu__card">
            <!-- 左侧示意图区域 -->
            <div class="wc-menu__card-illustration">
              <slot name="illustration">
                <img
                  v-if="illustration"
                  :src="illustration"
                  :alt="illustrationAlt"
                  class="wc-menu__illustration-image"
                />
                <div v-else class="wc-menu__illustration-placeholder">
                  <span>🎨</span>
                </div>
              </slot>
              <div v-if="cardTitle || cardDescription" class="wc-menu__card-info">
                <h4 v-if="cardTitle" class="wc-menu__card-title">{{ cardTitle }}</h4>
                <p v-if="cardDescription" class="wc-menu__card-description">{{ cardDescription }}</p>
              </div>
            </div>

            <!-- 右侧列表区域 -->
            <div class="wc-menu__card-list">
              <template
                v-for="(item, index) in items"
                :key="item.key || index"
              >
                <div v-if="item.divider" class="wc-menu__divider" role="separator" />
                <button
                  v-else
                  type="button"
                  role="menuitem"
                  :disabled="item.disabled"
                  :class="itemClasses(item)"
                  @click="handleItemClick(item, index)"
                >
                  <span v-if="item.icon" class="wc-menu__icon">{{ item.icon }}</span>
                  <span class="wc-menu__label">{{ item.label }}</span>
                </button>
              </template>
            </div>
          </div>

          <!-- 默认样式 -->
          <div v-else>
            <template
              v-for="(item, index) in items"
              :key="item.key || index"
            >
              <div v-if="item.divider" class="wc-menu__divider" role="separator" />
              <button
                v-else
                type="button"
                role="menuitem"
                :disabled="item.disabled"
                :class="itemClasses(item)"
                @click="handleItemClick(item, index)"
              >
                <span v-if="item.icon" class="wc-menu__icon">{{ item.icon }}</span>
                <span class="wc-menu__label">{{ item.label }}</span>
              </button>
            </template>
          </div>
        </slot>
      </div>
    </Transition>
  </div>
</template>

<script setup>
import { ref, computed, nextTick, watch } from 'vue'
import { useFloatingPosition, useOverlayLayer } from '../../interactions'
import './style.css'

const normalizePlacement = (placement) => placement.startsWith('top') ? 'top' : 'bottom'

const props = defineProps({
  items: {
    type: Array,
    default: () => []
  },
  triggerText: {
    type: String,
    default: '选择选项'
  },
  placement: {
    type: String,
    default: 'bottom-start',
    validator: (value) => ['bottom-start', 'bottom-end', 'top-start', 'top-end'].includes(value)
  },
  disabled: {
    type: Boolean,
    default: false
  },
  trigger: {
    type: String,
    default: 'click',
    validator: (value) => ['click', 'hover'].includes(value)
  },
  variant: {
    type: String,
    default: 'default',
    validator: (value) => ['default', 'card'].includes(value)
  },
  illustration: {
    type: String,
    default: ''
  },
  illustrationAlt: {
    type: String,
    default: '示意图'
  },
  cardTitle: {
    type: String,
    default: ''
  },
  cardDescription: {
    type: String,
    default: ''
  }
})

const emit = defineEmits(['select', 'open', 'close'])

const isOpen = ref(false)
const menuRef = ref(null)
const triggerRef = ref(null)
const panelRef = ref(null)
const requestedPlacement = computed(() => normalizePlacement(props.placement))
const offset = ref(6)

const menuClasses = computed(() => {
  const classes = ['wc-menu__menu', `wc-menu__menu--${props.placement}`]
  if (props.variant === 'card') {
    classes.push('wc-menu__menu--card')
  }
  return classes
})

const menuStyles = computed(() => {
  if (props.variant === 'card') {
    return {
      minWidth: '320px',
      maxWidth: '450px'
    }
  }
  return {
    minWidth: '120px'
  }
})

const itemClasses = (item) => [
  'wc-menu__item',
  {
    'wc-menu__item--disabled': item.disabled,
    'wc-menu__item--selected': item.selected,
    'wc-menu__item--danger': item.danger
  }
]

const handleToggle = () => {
  if (props.disabled) return

  isOpen.value = !isOpen.value

  if (isOpen.value) {
    emit('open')
  } else {
    emit('close')
  }
}

const closeMenu = () => {
  if (!isOpen.value) return
  isOpen.value = false
  emit('close')
}

const focusMenuItem = async (target = 'first') => {
  await nextTick()
  const items = Array.from(panelRef.value?.querySelectorAll('[role="menuitem"]:not(:disabled)') || [])
  if (!items.length) return
  const activeIndex = items.indexOf(document.activeElement)
  let nextIndex = target === 'last' ? items.length - 1 : 0
  if (target === 'next') nextIndex = activeIndex < 0 ? 0 : (activeIndex + 1) % items.length
  if (target === 'previous') nextIndex = activeIndex <= 0 ? items.length - 1 : activeIndex - 1
  items[nextIndex]?.focus()
}

watch(isOpen, (open) => {
  if (open) focusMenuItem('first')
})

const handleItemClick = (item, index) => {
  if (item.disabled || item.divider) return

  emit('select', item, index)
  closeMenu()
}

const handleClickOutside = (event) => {
  if (menuRef.value && !menuRef.value.contains(event.target)) {
    closeMenu()
  }
}

const handleTriggerKeydown = async (event) => {
  if (props.disabled) return
  if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    if (!isOpen.value) {
      isOpen.value = true
      emit('open')
    } else {
      focusMenuItem('next')
    }
  } else if (event.key === 'ArrowUp') {
    event.preventDefault()
    if (!isOpen.value) {
      isOpen.value = true
      emit('open')
      focusMenuItem('last')
    } else {
      focusMenuItem('previous')
    }
  }
}

const handlePanelKeydown = (event) => {
  if (event.key === 'ArrowDown') {
    event.preventDefault()
    focusMenuItem('next')
  } else if (event.key === 'ArrowUp') {
    event.preventDefault()
    focusMenuItem('previous')
  } else if (event.key === 'Home') {
    event.preventDefault()
    focusMenuItem('first')
  } else if (event.key === 'End') {
    event.preventDefault()
    focusMenuItem('last')
  } else if (event.key === 'Tab') {
    closeMenu()
  }
}

useFloatingPosition({
  open: isOpen,
  anchorRef: triggerRef,
  floatingRef: panelRef,
  placement: requestedPlacement,
  offset
})

useOverlayLayer({
  open: isOpen,
  elementRef: panelRef,
  refs: [triggerRef],
  closeOnEscape: true,
  closeOnPointerDownOutside: true,
  onEscapeKeyDown: () => {
    closeMenu()
    triggerRef.value?.querySelector('button')?.focus()
  },
  onPointerDownOutside: closeMenu,
  zIndex: 1000
})
</script>
