// src/components/ColorPicker/ColorPicker.jsx
import React from 'react'
import './style.css'
import { getColorPickerClasses, handleColorChange, getPreviewStyles } from './utils.js'

export default function ColorPicker({ 
  value = '#ffffff', 
  onChange,
  size = 'md',
  shape = 'circle',
  disabled = false,
  className = ''
}) {
  const colorPickerClasses = getColorPickerClasses({
    size,
    shape,
    disabled,
    className
  }).join(' ')

  const previewStyles = getPreviewStyles(value)

  const handleInput = (e) => {
    handleColorChange(e, disabled, onChange)
  }

  return (
    <label className={colorPickerClasses}>
      <input
        type="color"
        value={value}
        onChange={handleInput}
        disabled={disabled}
        className="wc-color-picker__input"
      />
      <span
        className="wc-color-picker__preview"
        style={previewStyles}
      />
    </label>
  )
}

// packages/vue/src/components/ColorPicker/ColorPicker.vue
<template>
  <label :class="colorPickerClasses">
    <input
      class="wc-color-picker__input"
      type="color"
      :value="modelValue"
      :disabled="disabled"
      @input="handleInput"
    >
    <span
      class="wc-color-picker__preview"
      :style="previewStyles"
    />
  </label>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { getColorPickerClasses, getPreviewStyles } from './utils.js'
import './style.css'

interface Props {
  modelValue?: string
  size?: 'sm' | 'md' | 'lg'
  shape?: 'circle' | 'square' | 'rounded'
  disabled?: boolean
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '#ffffff',
  size: 'md',
  shape: 'circle',
  disabled: false,
  className: ''
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const colorPickerClasses = computed(() => {
  return getColorPickerClasses({
    size: props.size,
    shape: props.shape,
    disabled: props.disabled,
    className: props.className
  }).join(' ')
})

const previewStyles = computed(() => {
  return getPreviewStyles(props.modelValue) as any
})

function handleInput(e: Event) {
  const target = e.target as HTMLInputElement
  if (!props.disabled) {
    emit('update:modelValue', target.value)
  }
}
</script>
