// src/components/CircularProgress/CircularProgress.vue
<template>
  <div
    :class="progressClasses"
    role="progressbar"
    :aria-valuenow="value"
    :aria-valuemin="0"
    :aria-valuemax="100"
  >
    <svg
      :width="size"
      :height="size"
      :viewBox="viewBox"
      class="wc-circular-progress-svg"
    >
      <!-- Background circle -->
      <circle
        :cx="center"
        :cy="center"
        :r="radius"
        :stroke-width="thickness"
        stroke="currentColor"
        fill="none"
        class="wc-circular-progress-bg"
      />
      
      <!-- Progress circle -->
      <circle
        :cx="center"
        :cy="center"
        :r="radius"
        :stroke-width="thickness"
        stroke="currentColor"
        fill="none"
        :stroke-dasharray="circumference"
        :stroke-dashoffset="strokeDashoffset"
        :class="circleClasses"
        class="wc-circular-progress-circle"
      />
    </svg>
    
    <!-- Value text -->
    <div
      v-if="showValue"
      class="wc-circular-progress-value"
    >
      {{ Math.round(value) }}%
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import './style.css'

const props = defineProps({
  value: {
    type: Number,
    default: 0,
    validator: (value) => value >= 0 && value <= 100
  },
  size: {
    type: [Number, String],
    default: 40
  },
  thickness: {
    type: Number,
    default: 3.6
  },
  variant: {
    type: String,
    default: 'indeterminate',
    validator: (value) => ['determinate', 'indeterminate'].includes(value)
  },
  color: {
    type: String,
    default: 'primary',
    validator: (value) => ['primary', 'secondary', 'success', 'warning', 'error', 'inherit'].includes(value)
  },
  showValue: {
    type: Boolean,
    default: false
  }
})

const sizeNumber = computed(() => (typeof props.size === 'string' ? parseInt(props.size) : props.size))
const center = computed(() => sizeNumber.value / 2)
const radius = computed(() => (sizeNumber.value - props.thickness) / 2)
const circumference = computed(() => 2 * Math.PI * radius.value)
const viewBox = computed(() => `0 0 ${sizeNumber.value} ${sizeNumber.value}`)

const strokeDashoffset = computed(() => {
  if (props.variant === 'determinate') {
    return circumference.value - (props.value / 100) * circumference.value
  }
  return 0
})

const progressClasses = computed(() => {
  const baseClasses = 'wc-circular-progress inline-flex relative items-center justify-center'
  const classes = [baseClasses]
  classes.push(`wc-circular-progress--${props.color}`)
  if (props.variant === 'indeterminate') classes.push('wc-circular-progress--indeterminate')
  return classes
})

const circleClasses = computed(() => (props.variant === 'indeterminate' ? ['wc-circular-progress-circle--indeterminate'] : []))
</script>

// src/components/CircularProgress/CircularProgress.jsx
import React from 'react'

export default function CircularProgress({
  value = 0,
  size = 40,
  thickness = 3.6,
  variant = 'indeterminate', // 'determinate' | 'indeterminate'
  color = 'primary', // tailwind 颜色 key
  showValue = false,
  className = '',
  ...rest
}) {
  const sizeNumber = typeof size === 'string' ? parseInt(size, 10) : size
  const center = sizeNumber / 2
  const radius = (sizeNumber - thickness) / 2
  const circumference = 2 * Math.PI * radius
  const strokeDashoffset =
    variant === 'determinate' ? circumference - (value / 100) * circumference : 0

  const progressClasses = [
    'wc-circular-progress inline-flex relative items-center justify-center',
    `wc-circular-progress--${color}`,
    variant === 'indeterminate' && 'wc-circular-progress--indeterminate',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  const circleClasses = [
    'wc-circular-progress-circle',
    variant === 'indeterminate' && 'wc-circular-progress-circle--indeterminate',
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div
      role="progressbar"
      aria-valuemin={0}
      aria-valuemax={100}
      aria-valuenow={value}
      className={progressClasses}
      {...rest}
    >
      <svg
        width={sizeNumber}
        height={sizeNumber}
        viewBox={`0 0 ${sizeNumber} ${sizeNumber}`}
        className="wc-circular-progress-svg"
      >
        <circle
          cx={center}
          cy={center}
          r={radius}
          strokeWidth={thickness}
          stroke="currentColor"
          fill="none"
          className="wc-circular-progress-bg"
        />
        <circle
          cx={center}
          cy={center}
          r={radius}
          strokeWidth={thickness}
          stroke="currentColor"
          fill="none"
          strokeDasharray={circumference}
          strokeDashoffset={strokeDashoffset}
          className={circleClasses}
        />
      </svg>
      {showValue && (
        <div className="wc-circular-progress-value">{Math.round(value)}%</div>
      )}
    </div>
  )
}
