// src/components/VideoPlayer/VideoPlayer.vue
<template>
  <div class="video-wrapper">
    <video ref="video" class="video-el" :src="src" @timeupdate="updateProgress" @ended="onEnded"></video>
    <div class="controls">
      <button class="ctrl-btn" @click="togglePlay">{{ playing ? '❚❚' : '▶️' }}</button>
      <div class="progress" @click="seek($event)">
        <div class="progress-bar" :style="{ width: progress + '%' }"></div>
      </div>
      <span class="time">{{ formattedCurrent }} / {{ formattedDuration }}</span>
      <button class="ctrl-btn" @click="toggleMute">{{ muted ? '🔇' : '🔊' }}</button>
      <input class="volume" type="range" min="0" max="1" step="0.05" v-model.number="volume" />
      <button class="ctrl-btn" @click="toggleFullscreen">⛶</button>
    </div>
  </div>
</template>

<script>
import { ref, computed, onMounted, watch } from 'vue'
export default {
  name: 'VideoPlayer',
  props: {
    src: { type: String, required: true },
    autoplay: { type: Boolean, default: false },
    loop: { type: Boolean, default: false },
  },
  setup(props) {
    const video = ref(null)
    const playing = ref(false)
    const progress = ref(0)
    const volume = ref(0.7)
    const muted = ref(false)
    const duration = ref(0)
    const current = ref(0)

    const formattedTime = (s) => {
      const m = Math.floor(s / 60)
      const sec = Math.floor(s % 60).toString().padStart(2, '0')
      return `${m}:${sec}`
    }
    const formattedCurrent = computed(() => formattedTime(current.value))
    const formattedDuration = computed(() => formattedTime(duration.value))

    const togglePlay = () => {
      if (!video.value) return
      if (video.value.paused) {
        video.value.play()
      } else {
        video.value.pause()
      }
    }
    const updateProgress = () => {
      if (!video.value) return
      duration.value = video.value.duration || 0
      current.value = video.value.currentTime
      progress.value = duration.value ? (current.value / duration.value) * 100 : 0
      playing.value = !video.value.paused
    }
    const seek = (e) => {
      const rect = e.currentTarget.getBoundingClientRect()
      const percent = (e.clientX - rect.left) / rect.width
      if (video.value) video.value.currentTime = percent * duration.value
    }
    const toggleMute = () => {
      muted.value = !muted.value
      if (video.value) video.value.muted = muted.value
    }
    const toggleFullscreen = () => {
      const el = video.value.parentElement
      if (!document.fullscreenElement) {
        el.requestFullscreen?.()
      } else {
        document.exitFullscreen?.()
      }
    }

    watch(volume, (v) => { if (video.value) video.value.volume = v })
    const onEnded = () => { playing.value = false }

    onMounted(() => {
      if (video.value) {
        video.value.volume = volume.value
        video.value.muted = muted.value
        video.value.loop = props.loop
        if (props.autoplay) video.value.play()
      }
    })

    return { video, playing, progress, togglePlay, updateProgress, seek, volume, muted, toggleMute, toggleFullscreen, formattedCurrent, formattedDuration, onEnded }
  }
}
</script>

<style scoped>
.video-wrapper { width: 100%; max-width: 640px; margin: 0 auto; }
.video-el { width: 100%; border-radius: 8px; background: black; }
.controls { display: flex; align-items: center; gap: 6px; margin-top: 4px; font-size: 0.875rem; color: var(--wc-neutral-700); }
.ctrl-btn { background: none; border: none; cursor: pointer; font-size: 1rem; }
.progress { flex: 1 1 auto; height: 6px; background: var(--wc-neutral-300); border-radius: 3px; cursor: pointer; position: relative; }
.progress-bar { height: 100%; background: var(--wc-primary-500); border-radius: 3px; }
.volume { width: 80px; }
.time { min-width: 60px; text-align: center; }

/* Dark mode */
.dark .controls { color: var(--wc-neutral-200); }
.dark .progress { background: var(--wc-neutral-600); }
.dark .progress-bar { background: var(--wc-primary-400); }
</style>

// src/components/VideoPlayer/VideoPlayer.jsx
import React, { useRef, useState, useEffect, useCallback } from 'react'

const VideoPlayer = ({
  src,
  autoplay = false,
  loop = false,
  className = '',
  style = {},
  ...rest
}) => {
  const videoRef = useRef(null)
  const [playing, setPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [volume, setVolume] = useState(0.7)
  const [muted, setMuted] = useState(false)
  const [duration, setDuration] = useState(0)
  const [current, setCurrent] = useState(0)

  const formattedTime = useCallback((s) => {
    const m = Math.floor(s / 60)
    const sec = Math.floor(s % 60).toString().padStart(2, '0')
    return `${m}:${sec}`
  }, [])

  const formattedCurrent = formattedTime(current)
  const formattedDuration = formattedTime(duration)

  const togglePlay = () => {
    const v = videoRef.current
    if (!v) return
    if (v.paused) {
      v.play()
    } else {
      v.pause()
    }
  }

  const updateProgress = () => {
    const v = videoRef.current
    if (!v) return
    setDuration(v.duration || 0)
    setCurrent(v.currentTime)
    setProgress(v.duration ? (v.currentTime / v.duration) * 100 : 0)
    setPlaying(!v.paused)
  }

  const seek = (e) => {
    const rect = e.currentTarget.getBoundingClientRect()
    const percent = (e.clientX - rect.left) / rect.width
    const v = videoRef.current
    if (v) v.currentTime = percent * duration
  }

  const toggleMute = () => {
    setMuted((prev) => {
      const next = !prev
      if (videoRef.current) videoRef.current.muted = next
      return next
    })
  }

  const toggleFullscreen = () => {
    const el = videoRef.current?.parentElement
    if (!el) return
    if (!document.fullscreenElement) {
      el.requestFullscreen?.()
    } else {
      document.exitFullscreen?.()
    }
  }

  // sync volume
  useEffect(() => {
    if (videoRef.current) videoRef.current.volume = volume
  }, [volume])

  useEffect(() => {
    const v = videoRef.current
    if (!v) return
    v.muted = muted
    v.loop = loop
    if (autoplay) v.play()
  }, [autoplay, loop, muted])

  return (
    <div className={`video-wrapper ${className}`} style={style} {...rest}>
      <video
        ref={videoRef}
        className="video-el"
        src={src}
        onTimeUpdate={updateProgress}
        onEnded={() => setPlaying(false)}
      />
      <div className="controls">
        <button className="ctrl-btn" onClick={togglePlay}>{playing ? '❚❚' : '▶️'}</button>
        <div className="progress" onClick={seek}>
          <div className="progress-bar" style={{ width: `${progress}%` }} />
        </div>
        <span className="time">{formattedCurrent} / {formattedDuration}</span>
        <button className="ctrl-btn" onClick={toggleMute}>{muted ? '🔇' : '🔊'}</button>
        <input className="volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={(e)=>setVolume(Number(e.target.value))} />
        <button className="ctrl-btn" onClick={toggleFullscreen}>⛶</button>
      </div>
      <style>{`
        .video-wrapper { width: 100%; max-width: 640px; margin: 0 auto; }
        .video-el { width: 100%; border-radius: 8px; background: black; }
        .controls { display: flex; align-items: center; gap: 6px; margin-top: 4px; font-size: 0.875rem; color: var(--wc-neutral-700); }
        .ctrl-btn { background: none; border: none; cursor: pointer; font-size: 1rem; }
        .progress { flex: 1 1 auto; height: 6px; background: var(--wc-neutral-300); border-radius: 3px; cursor: pointer; position: relative; }
        .progress-bar { height: 100%; background: var(--wc-primary-500); border-radius: 3px; }
        .volume { width: 80px; }
        .time { min-width: 60px; text-align: center; }
        .dark .controls { color: var(--wc-neutral-200); }
        .dark .progress { background: var(--wc-neutral-600); }
        .dark .progress-bar { background: var(--wc-primary-400); }
      `}</style>
    </div>
  )
}

VideoPlayer.displayName = 'VideoPlayer'
export default VideoPlayer
