// packages/svelte/src/components/DatePicker/DatePicker.svelte
<script lang="ts">
  import { useLocale } from '../../hooks.js'

  interface CalendarDay {
    day: number
    month: 'prev' | 'current' | 'next'
    date: Date
  }

  let {
    value = $bindable(null),
    placeholder = '请选择日期',
    format = 'YYYY-MM-DD',
    disabled = false,
    showToday = true,
    minDate = null,
    maxDate = null,
    size = 'md',
    variant = 'default',
    onchange,
  }: {
    value?: Date | string | null
    placeholder?: string
    format?: string
    disabled?: boolean
    showToday?: boolean
    minDate?: Date | string | null
    maxDate?: Date | string | null
    size?: 'sm' | 'md' | 'lg'
    variant?: 'default' | 'outlined' | 'filled'
    onchange?: (value: Date | null) => void
  } = $props()

  const localeStore = useLocale()
  const inputId = `wc-datepicker-${Math.random().toString(36).slice(2, 11)}`

  let isOpen = $state(false)
  let currentDate = $state(new Date())
  let rootEl: HTMLElement | null = $state(null)

  const weekdays = ['日', '一', '二', '三', '四', '五', '六']

  const selectedDate = $derived.by(() => {
    if (!value) return null
    return value instanceof Date ? value : new Date(value)
  })

  const displayValue = $derived(selectedDate ? formatDate(selectedDate, format) : '')

  const currentMonthYear = $derived(`${currentDate.getFullYear()}年${currentDate.getMonth() + 1}月`)

  const calendarDays = $derived.by(() => {
    const year = currentDate.getFullYear()
    const month = currentDate.getMonth()
    const firstDayWeekday = new Date(year, month, 1).getDay()
    const daysInMonth = new Date(year, month + 1, 0).getDate()
    const days: CalendarDay[] = []
    const prevMonthLastDay = new Date(year, month, 0).getDate()
    for (let i = firstDayWeekday - 1; i >= 0; i--) {
      days.push({ day: prevMonthLastDay - i, month: 'prev', date: new Date(year, month - 1, prevMonthLastDay - i) })
    }
    for (let day = 1; day <= daysInMonth; day++) {
      days.push({ day, month: 'current', date: new Date(year, month, day) })
    }
    const remainingDays = 42 - days.length
    for (let day = 1; day <= remainingDays; day++) {
      days.push({ day, month: 'next', date: new Date(year, month + 1, day) })
    }
    return days
  })

  function formatDate(date: Date, fmt: string): string {
    const year = String(date.getFullYear())
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    return fmt.replace('YYYY', year).replace('MM', month).replace('DD', day)
  }

  function isDateSelected(date: Date): boolean {
    if (!selectedDate) return false
    return date.toDateString() === selectedDate.toDateString()
  }

  function isToday(date: Date): boolean {
    return date.toDateString() === new Date().toDateString()
  }

  function isDateDisabled(day: CalendarDay): boolean {
    if (minDate) {
      const min = minDate instanceof Date ? minDate : new Date(minDate)
      if (day.date < min) return true
    }
    if (maxDate) {
      const max = maxDate instanceof Date ? maxDate : new Date(maxDate)
      if (day.date > max) return true
    }
    return false
  }

  function togglePicker() {
    if (disabled) return
    isOpen = !isOpen
  }

  function handleInputKeydown(event: KeyboardEvent) {
    if (disabled) return
    if (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown') {
      event.preventDefault()
      isOpen = true
    } else if (event.key === 'Escape') {
      isOpen = false
    }
  }

  function changeMonth(delta: number) {
    const newDate = new Date(currentDate)
    newDate.setMonth(newDate.getMonth() + delta)
    currentDate = newDate
  }

  function commit(next: Date | null) {
    value = next
    onchange?.(next)
    isOpen = false
  }

  function selectDate(day: CalendarDay) {
    if (isDateDisabled(day)) return
    commit(new Date(day.date))
  }

  $effect(() => {
    if (value) {
      const date = value instanceof Date ? value : new Date(value)
      currentDate = new Date(date.getFullYear(), date.getMonth(), 1)
    }
  })

  $effect(() => {
    if (!isOpen || typeof document === 'undefined') return
    const handlePointerDown = (e: PointerEvent) => {
      if (rootEl && !rootEl.contains(e.target as Node)) isOpen = false
    }
    const handleKeydown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') isOpen = false
    }
    document.addEventListener('pointerdown', handlePointerDown)
    document.addEventListener('keydown', handleKeydown)
    return () => {
      document.removeEventListener('pointerdown', handlePointerDown)
      document.removeEventListener('keydown', handleKeydown)
    }
  })
</script>

<div bind:this={rootEl} class="wc-datepicker">
  <div
    class="wc-datepicker-wrapper wc-datepicker-wrapper--{variant} wc-datepicker-wrapper--{size}"
    class:wc-datepicker-wrapper--disabled={disabled}
    class:wc-datepicker-wrapper--open={isOpen}
    onclick={togglePicker}
    role="presentation"
  >
    <input
      id={inputId}
      type="text"
      value={displayValue}
      {placeholder}
      {disabled}
      readonly
      class="wc-datepicker-input"
      role="combobox"
      aria-haspopup="dialog"
      aria-expanded={isOpen}
      aria-controls="{inputId}-calendar"
      onkeydown={handleInputKeydown}
    />
    <span class="wc-datepicker-icon" aria-hidden="true">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M16 3v4M8 3v4M3 10h18" /></svg>
    </span>
  </div>

  {#if isOpen}
    <div id="{inputId}-calendar" class="wc-datepicker-dropdown" role="dialog" aria-label={localeStore.messages.openCalendar}>
      <div class="wc-datepicker-header">
        <button type="button" class="wc-datepicker-nav" aria-label={localeStore.messages.previousMonth} onclick={() => changeMonth(-1)}>‹</button>
        <span class="wc-datepicker-title">{currentMonthYear}</span>
        <button type="button" class="wc-datepicker-nav" aria-label={localeStore.messages.nextMonth} onclick={() => changeMonth(1)}>›</button>
      </div>

      <div class="wc-datepicker-weekdays">
        {#each weekdays as weekday (weekday)}
          <div class="wc-datepicker-weekday">{weekday}</div>
        {/each}
      </div>

      <div class="wc-datepicker-days">
        {#each calendarDays as day (`${day.month}-${day.day}`)}
          <button
            type="button"
            class="wc-datepicker-day wc-datepicker-day--{day.month}"
            class:wc-datepicker-day--selected={isDateSelected(day.date)}
            class:wc-datepicker-day--today={isToday(day.date)}
            class:wc-datepicker-day--disabled={isDateDisabled(day)}
            disabled={isDateDisabled(day)}
            aria-label={formatDate(day.date, 'YYYY-MM-DD')}
            aria-pressed={isDateSelected(day.date)}
            aria-current={isToday(day.date) ? 'date' : undefined}
            onclick={() => selectDate(day)}
          >
            {day.day}
          </button>
        {/each}
      </div>

      {#if showToday}
        <div class="wc-datepicker-footer">
          <button type="button" class="wc-datepicker-today" onclick={() => commit(new Date())}>今天</button>
          <button type="button" class="wc-datepicker-clear" onclick={() => commit(null)}>清除</button>
        </div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .wc-datepicker {
    position: relative;
    display: inline-block;
  }
  .wc-datepicker-wrapper {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    border: 1px solid var(--wc-border-default, rgba(0, 0, 0, 0.15));
    border-radius: 8px;
    background: var(--wc-surface-canvas, #fff);
    cursor: pointer;
    transition: border-color 0.15s ease;
  }
  .wc-datepicker-wrapper--filled {
    background: var(--wc-surface-muted, rgba(0, 0, 0, 0.04));
  }
  .wc-datepicker-wrapper--sm { padding: 5px 10px; }
  .wc-datepicker-wrapper--lg { padding: 11px 14px; }
  .wc-datepicker-wrapper--open,
  .wc-datepicker-wrapper:hover:not(.wc-datepicker-wrapper--disabled) {
    border-color: var(--wc-color-primary, #3b82f6);
  }
  .wc-datepicker-wrapper--disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .wc-datepicker-input {
    border: none;
    outline: none;
    background: transparent;
    font-size: 0.9rem;
    width: 120px;
    color: var(--wc-text-primary, #1a1a1a);
    cursor: inherit;
  }
  .wc-datepicker-icon {
    display: inline-flex;
    width: 18px;
    height: 18px;
    color: var(--wc-text-secondary, #6b7280);
  }
  .wc-datepicker-icon svg {
    width: 100%;
    height: 100%;
  }
  .wc-datepicker-dropdown {
    position: absolute;
    top: calc(100% + 6px);
    left: 0;
    z-index: 1000;
    width: 280px;
    padding: 12px;
    background: var(--wc-surface-canvas, #fff);
    border: 1px solid var(--wc-border-default, rgba(0, 0, 0, 0.1));
    border-radius: 12px;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
  }
  .wc-datepicker-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 8px;
  }
  .wc-datepicker-nav {
    background: none;
    border: none;
    font-size: 1.2rem;
    cursor: pointer;
    padding: 2px 10px;
    border-radius: 6px;
    color: var(--wc-text-primary, #1a1a1a);
  }
  .wc-datepicker-nav:hover {
    background: var(--wc-surface-hover, rgba(0, 0, 0, 0.06));
  }
  .wc-datepicker-title {
    font-weight: 600;
    font-size: 0.9rem;
    color: var(--wc-text-primary, #1a1a1a);
  }
  .wc-datepicker-weekdays,
  .wc-datepicker-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 2px;
  }
  .wc-datepicker-weekday {
    text-align: center;
    font-size: 0.75rem;
    color: var(--wc-text-secondary, #6b7280);
    padding: 4px 0;
  }
  .wc-datepicker-day {
    aspect-ratio: 1;
    border: none;
    background: none;
    border-radius: 6px;
    font-size: 0.8rem;
    cursor: pointer;
    color: var(--wc-text-primary, #1a1a1a);
  }
  .wc-datepicker-day--prev,
  .wc-datepicker-day--next {
    color: var(--wc-text-disabled, #9ca3af);
  }
  .wc-datepicker-day:hover:not(:disabled) {
    background: var(--wc-surface-hover, rgba(0, 0, 0, 0.06));
  }
  .wc-datepicker-day--today {
    font-weight: 700;
    color: var(--wc-color-primary, #3b82f6);
  }
  .wc-datepicker-day--selected {
    background: var(--wc-color-primary, #3b82f6);
    color: #fff;
  }
  .wc-datepicker-day--selected:hover:not(:disabled) {
    background: var(--wc-color-primary, #3b82f6);
  }
  .wc-datepicker-day--disabled {
    cursor: not-allowed;
    opacity: 0.4;
  }
  .wc-datepicker-footer {
    display: flex;
    justify-content: space-between;
    margin-top: 8px;
    padding-top: 8px;
    border-top: 1px solid var(--wc-border-default, rgba(0, 0, 0, 0.08));
  }
  .wc-datepicker-today,
  .wc-datepicker-clear {
    background: none;
    border: none;
    font-size: 0.8rem;
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 6px;
    color: var(--wc-color-primary, #3b82f6);
  }
  .wc-datepicker-clear {
    color: var(--wc-text-secondary, #6b7280);
  }
  .wc-datepicker-today:hover,
  .wc-datepicker-clear:hover {
    background: var(--wc-surface-hover, rgba(0, 0, 0, 0.06));
  }
</style>

// src/components/DatePicker/DatePicker.vue
<template>
  <div class="wc-datepicker" ref="datePickerRef">
    <div
      :class="inputClasses"
      @click="togglePicker"
    >
      <input
        ref="inputRef"
        type="text"
        :value="displayValue"
        :placeholder="placeholder"
        :disabled="disabled"
        readonly
        class="wc-datepicker-input"
      />
      <span class="wc-datepicker-icon">📅</span>
    </div>
    
    <div
      v-if="isOpen"
      class="wc-datepicker-dropdown"
      :style="dropdownStyles"
    >
      <div class="wc-datepicker-header">
        <button
          type="button"
          class="wc-datepicker-nav"
          @click="changeMonth(-1)"
        >
          ‹
        </button>
        <span class="wc-datepicker-title">
          {{ currentMonthYear }}
        </span>
        <button
          type="button"
          class="wc-datepicker-nav"
          @click="changeMonth(1)"
        >
          ›
        </button>
      </div>
      
      <div class="wc-datepicker-weekdays">
        <div
          v-for="weekday in weekdays"
          :key="weekday"
          class="wc-datepicker-weekday"
        >
          {{ weekday }}
        </div>
      </div>
      
      <div class="wc-datepicker-days">
        <button
          v-for="day in calendarDays"
          :key="`${day.month}-${day.day}`"
          type="button"
          :class="getDayClasses(day)"
          @click="selectDate(day)"
          :disabled="isDateDisabled(day)"
        >
          {{ day.day }}
        </button>
      </div>
      
      <div v-if="showToday" class="wc-datepicker-footer">
        <button
          type="button"
          class="wc-datepicker-today"
          @click="selectToday"
        >
          今天
        </button>
        <button
          type="button"
          class="wc-datepicker-clear"
          @click="clearDate"
        >
          清除
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

const props = defineProps({
  modelValue: {
    type: [Date, String],
    default: null
  },
  placeholder: {
    type: String,
    default: '请选择日期'
  },
  format: {
    type: String,
    default: 'YYYY-MM-DD'
  },
  disabled: {
    type: Boolean,
    default: false
  },
  showToday: {
    type: Boolean,
    default: true
  },
  minDate: {
    type: [Date, String],
    default: null
  },
  maxDate: {
    type: [Date, String],
    default: null
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  },
  variant: {
    type: String,
    default: 'default',
    validator: (value) => ['default', 'outlined', 'filled'].includes(value)
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const datePickerRef = ref(null)
const inputRef = ref(null)
const isOpen = ref(false)
const currentDate = ref(new Date())

const weekdays = ['日', '一', '二', '三', '四', '五', '六']

const inputClasses = computed(() => [
  'wc-datepicker-wrapper',
  `wc-datepicker-wrapper--${props.variant}`,
  `wc-datepicker-wrapper--${props.size}`,
  {
    'wc-datepicker-wrapper--disabled': props.disabled,
    'wc-datepicker-wrapper--open': isOpen.value
  }
])

const dropdownStyles = computed(() => ({
  zIndex: 1000
}))

const selectedDate = computed(() => {
  if (!props.modelValue) return null
  return props.modelValue instanceof Date ? props.modelValue : new Date(props.modelValue)
})

const displayValue = computed(() => {
  if (!selectedDate.value) return ''
  return formatDate(selectedDate.value, props.format)
})

const currentMonthYear = computed(() => {
  const year = currentDate.value.getFullYear()
  const month = currentDate.value.getMonth() + 1
  return `${year}年${month}月`
})

const calendarDays = computed(() => {
  const year = currentDate.value.getFullYear()
  const month = currentDate.value.getMonth()
  
  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  const firstDayWeekday = firstDay.getDay()
  const daysInMonth = lastDay.getDate()
  
  const days = []
  
  // 添加上个月的日期
  const prevMonth = new Date(year, month - 1, 0)
  for (let i = firstDayWeekday - 1; i >= 0; i--) {
    days.push({
      day: prevMonth.getDate() - i,
      month: 'prev',
      date: new Date(year, month - 1, prevMonth.getDate() - i)
    })
  }
  
  // 添加当月的日期
  for (let day = 1; day <= daysInMonth; day++) {
    days.push({
      day,
      month: 'current',
      date: new Date(year, month, day)
    })
  }
  
  // 添加下个月的日期
  const remainingDays = 42 - days.length
  for (let day = 1; day <= remainingDays; day++) {
    days.push({
      day,
      month: 'next',
      date: new Date(year, month + 1, day)
    })
  }
  
  return days
})

const getDayClasses = (day) => [
  'wc-datepicker-day',
  {
    'wc-datepicker-day--prev': day.month === 'prev',
    'wc-datepicker-day--next': day.month === 'next',
    'wc-datepicker-day--current': day.month === 'current',
    'wc-datepicker-day--selected': isDateSelected(day.date),
    'wc-datepicker-day--today': isToday(day.date),
    'wc-datepicker-day--disabled': isDateDisabled(day)
  }
]

const isDateSelected = (date) => {
  if (!selectedDate.value) return false
  return date.toDateString() === selectedDate.value.toDateString()
}

const isToday = (date) => {
  const today = new Date()
  return date.toDateString() === today.toDateString()
}

const isDateDisabled = (day) => {
  const { date } = day
  
  if (props.minDate) {
    const minDate = props.minDate instanceof Date ? props.minDate : new Date(props.minDate)
    if (date < minDate) return true
  }
  
  if (props.maxDate) {
    const maxDate = props.maxDate instanceof Date ? props.maxDate : new Date(props.maxDate)
    if (date > maxDate) return true
  }
  
  return false
}

const formatDate = (date, format) => {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  
  return format
    .replace('YYYY', year)
    .replace('MM', month)
    .replace('DD', day)
}

const togglePicker = () => {
  if (props.disabled) return
  isOpen.value = !isOpen.value
}

const changeMonth = (delta) => {
  const newDate = new Date(currentDate.value)
  newDate.setMonth(newDate.getMonth() + delta)
  currentDate.value = newDate
}

const selectDate = (day) => {
  if (isDateDisabled(day)) return
  
  const newDate = new Date(day.date)
  emit('update:modelValue', newDate)
  emit('change', newDate)
  isOpen.value = false
}

const selectToday = () => {
  const today = new Date()
  emit('update:modelValue', today)
  emit('change', today)
  isOpen.value = false
}

const clearDate = () => {
  emit('update:modelValue', null)
  emit('change', null)
  isOpen.value = false
}

const handleClickOutside = (event) => {
  if (datePickerRef.value && !datePickerRef.value.contains(event.target)) {
    isOpen.value = false
  }
}

watch(() => props.modelValue, (newValue) => {
  if (newValue) {
    const date = newValue instanceof Date ? newValue : new Date(newValue)
    currentDate.value = new Date(date.getFullYear(), date.getMonth(), 1)
  }
})

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<style scoped>
.wc-datepicker {
  position: relative;
  display: inline-block;
  font-family: var(--wc-font-family);
}

.wc-datepicker-wrapper {
  position: relative;
  display: flex;
  align-items: center;
  border: 1px solid var(--wc-neutral-200);
  border-radius: 8px;
  background-color: var(--wc-neutral-0);
  cursor: pointer;
  transition: all 0.2s ease;
}

.wc-datepicker-wrapper:hover:not(.wc-datepicker-wrapper--disabled) {
  border-color: var(--wc-primary-500);
}

.wc-datepicker-wrapper--open {
  border-color: var(--wc-primary-500);
  box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.05);
}

.wc-datepicker-wrapper--disabled {
  opacity: 0.5;
  cursor: not-allowed;
  background-color: var(--wc-neutral-50);
}

.wc-datepicker-wrapper--sm {
  padding: 6px 12px;
}

.wc-datepicker-wrapper--md {
  padding: 8px 14px;
}

.wc-datepicker-wrapper--lg {
  padding: 12px 16px;
}

.wc-datepicker-input {
  flex: 1;
  border: none;
  outline: none;
  background: none;
  font-size: 14px;
  color: var(--wc-neutral-800);
  cursor: pointer;
}

.wc-datepicker-input::placeholder {
  color: var(--wc-neutral-400);
}

.wc-datepicker-input:disabled {
  cursor: not-allowed;
}

.wc-datepicker-icon {
  flex-shrink: 0;
  margin-left: 8px;
  font-size: 16px;
  color: var(--wc-neutral-600);
}

.wc-datepicker-dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  margin-top: 4px;
  background: var(--wc-neutral-0);
  border: 1px solid var(--wc-neutral-200);
  border-radius: 12px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
  padding: 16px;
  min-width: 280px;
}

.wc-datepicker-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}

.wc-datepicker-nav {
  background: none;
  border: none;
  width: 32px;
  height: 32px;
  border-radius: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  font-size: 18px;
  color: var(--wc-neutral-600);
  transition: all 0.2s ease;
}

.wc-datepicker-nav:hover {
  background-color: var(--wc-neutral-100);
  color: var(--wc-primary-500);
}

.wc-datepicker-title {
  font-weight: 600;
  font-size: 16px;
  color: var(--wc-neutral-900);
}

.wc-datepicker-weekdays {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 4px;
  margin-bottom: 8px;
}

.wc-datepicker-weekday {
  text-align: center;
  font-size: 12px;
  font-weight: 500;
  color: var(--wc-neutral-600);
  padding: 8px 4px;
}

.wc-datepicker-days {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 4px;
}

.wc-datepicker-day {
  width: 32px;
  height: 32px;
  border: none;
  border-radius: 6px;
  background: none;
  cursor: pointer;
  font-size: 14px;
  color: var(--wc-neutral-800);
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
}

.wc-datepicker-day:hover:not(.wc-datepicker-day--disabled) {
  background-color: var(--wc-neutral-100);
}

.wc-datepicker-day--prev,
.wc-datepicker-day--next {
  color: var(--wc-neutral-400);
}

.wc-datepicker-day--today {
  background-color: var(--wc-primary-500);
  color: var(--wc-neutral-0);
}

.wc-datepicker-day--selected {
  background-color: var(--wc-primary-500);
}

.wc-datepicker-day--disabled {
  color: var(--wc-neutral-300);
  cursor: not-allowed;
}

.wc-datepicker-footer {
  display: flex;
  justify-content: space-between;
  gap: 8px;
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid var(--wc-neutral-200);
}

.wc-datepicker-today,
.wc-datepicker-clear {
  padding: 6px 12px;
  border: none;
  border-radius: 6px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.wc-datepicker-today {
  background-color: var(--wc-primary-500);
}

.wc-datepicker-today:hover {
  background-color: var(--wc-primary-600);
}

.wc-datepicker-clear {
  background-color: var(--wc-neutral-100);
  color: var(--wc-neutral-600);
}

.wc-datepicker-clear:hover {
  background-color: var(--wc-neutral-200);
}

/* 变体样式 */
.wc-datepicker-wrapper--outlined {
  border: 2px solid #d1d5db;
}

.wc-datepicker-wrapper--filled {
  background-color: #f9fafb;
  border: 1px solid transparent;
}

/* 深色模式 */
@media (prefers-color-scheme: dark) {
  .wc-datepicker-wrapper {
    background-color: #374151;
    border-color: #4b5563;
  }
  
  .wc-datepicker-wrapper:hover:not(.wc-datepicker-wrapper--disabled) {
    border-color: #60a5fa;
  }
  
  .wc-datepicker-wrapper--open {
    border-color: #60a5fa;
    box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.1);
  }
  
  .wc-datepicker-wrapper--disabled {
    background-color: #4b5563;
  }
  
  .wc-datepicker-input {
    color: #f9fafb;
  }
  
  .wc-datepicker-input::placeholder {
    color: #9ca3af;
  }
  
  .wc-datepicker-icon {
    color: #d1d5db;
  }
  
  .wc-datepicker-dropdown {
    background: #1f2937;
    border-color: #374151;
  }
  
  .wc-datepicker-nav {
    color: #d1d5db;
  }
  
  .wc-datepicker-nav:hover {
    background-color: #374151;
    color: #60a5fa;
  }
  
  .wc-datepicker-title {
    color: #f9fafb;
  }
  
  .wc-datepicker-weekday {
    color: #9ca3af;
  }
  
  .wc-datepicker-day {
    color: #f9fafb;
  }
  
  .wc-datepicker-day:hover:not(.wc-datepicker-day--disabled) {
    background-color: #374151;
  }
  
  .wc-datepicker-day--prev,
  .wc-datepicker-day--next {
    color: #6b7280;
  }
  
  .wc-datepicker-day--today {
    background-color: #60a5fa;
  }
  
  .wc-datepicker-day--selected {
    background-color: #60a5fa;
  }
  
  .wc-datepicker-day--disabled {
    color: #4b5563;
  }
  
  .wc-datepicker-footer {
    border-top-color: #374151;
  }
  
  .wc-datepicker-today {
    background-color: #60a5fa;
  }
  
  .wc-datepicker-today:hover {
    background-color: #3b82f6;
  }
  
  .wc-datepicker-clear {
    background-color: #374151;
    color: #d1d5db;
  }
  
  .wc-datepicker-clear:hover {
    background-color: #4b5563;
  }
  
  .wc-datepicker-wrapper--filled {
    background-color: #4b5563;
  }
}

/* 响应式设计 */
@media (max-width: 480px) {
  .wc-datepicker-dropdown {
    position: fixed;
    top: 50% !important;
    left: 50% !important;
    right: auto !important;
    transform: translate(-50%, -50%);
    margin: 0;
    max-width: 320px;
    width: 90vw;
  }
}
</style>
