// src/components/TypingText/TypingText.vue
<template>
  <span class="typing-wrapper">
    <span class="typing-text">{{ displayText }}</span><span v-if="showCursor" class="typing-cursor"></span>
  </span>
</template>

<script>
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'

export default {
  name: 'TypingText',
  props: {
    text: { type: String, default: 'Hello, Watercolor UI!' },
    speed: { type: Number, default: 100 }, // ms per char
    pause: { type: Number, default: 1500 }, // pause before delete/retype
    loop: { type: Boolean, default: false },
    erase: { type: Boolean, default: false }, // if true, erase then loop
    showCursor: { type: Boolean, default: true },
  },
  setup(props) {
    const displayText = ref('')
    const index = ref(0)
    const direction = ref(1) // 1 typing, -1 deleting
    let timer

    const start = () => {
      stop()
      timer = setInterval(step, props.speed)
    }
    const stop = () => {
      if (timer) clearInterval(timer)
    }
    const step = () => {
      if (direction.value === 1) {
        // typing
        if (index.value < props.text.length) {
          index.value++
          displayText.value = props.text.slice(0, index.value)
        } else if (props.loop) {
          if (props.erase) {
            direction.value = -1
          } else {
            stop()
            setTimeout(() => {
              index.value = 0
              displayText.value = ''
              start()
            }, props.pause)
          }
        } else {
          stop()
        }
      } else {
        // deleting
        if (index.value > 0) {
          index.value--
          displayText.value = props.text.slice(0, index.value)
        } else {
          direction.value = 1
        }
      }
    }

    onMounted(start)
    onBeforeUnmount(stop)
    watch(() => props.text, () => {
      index.value = 0
      displayText.value = ''
      direction.value = 1
      start()
    })
    watch(() => props.speed, () => start())

    return { displayText }
  }
}
</script>

<style scoped>
.typing-wrapper { display: inline-flex; align-items: center; }
.typing-cursor {
  display: inline-block;
  width: 1px;
  height: 1em;
  background: currentColor;
  margin-left: 2px;
  animation: blink 1s steps(1) infinite;
}
@keyframes blink { 0%, 50% { opacity: 1;} 51%,100% { opacity: 0; }}
</style>

// packages/svelte/src/components/TypingText/TypingText.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'

  let {
    text = 'Hello, Watercolor UI!',
    speed = 100,
    pause = 1500,
    loop = false,
    erase = false,
    showCursor = true,
  }: {
    text?: string
    speed?: number
    pause?: number
    loop?: boolean
    erase?: boolean
    showCursor?: boolean
  } = $props()

  let displayText = $state('')
  let timer: ReturnType<typeof setTimeout> | null = null

  function stop() {
    if (timer) {
      clearTimeout(timer)
      timer = null
    }
  }

  function run(currentText: string) {
    stop()
    displayText = ''
    let index = 0
    let deleting = false

    const step = () => {
      if (!deleting) {
        index += 1
        displayText = currentText.slice(0, index)
        if (index >= currentText.length) {
          if (erase && loop) {
            deleting = true
            timer = setTimeout(step, pause)
          } else if (loop) {
            timer = setTimeout(() => {
              index = 0
              displayText = ''
              timer = setTimeout(step, speed)
            }, pause)
          }
          return
        }
        timer = setTimeout(step, speed)
      } else {
        index -= 1
        displayText = currentText.slice(0, index)
        if (index <= 0) {
          deleting = false
          timer = setTimeout(step, speed)
          return
        }
        timer = setTimeout(step, speed / 2)
      }
    }

    timer = setTimeout(step, speed)
  }

  $effect(() => {
    // re-run when any option changes
    void speed
    void pause
    void loop
    void erase
    run(text)
    return stop
  })

  onDestroy(stop)
</script>

<span class="typing-wrapper">
  <span class="typing-text">{displayText}</span>
  {#if showCursor}<span class="typing-cursor"></span>{/if}
</span>

<style>
  .typing-wrapper {
    display: inline-flex;
    align-items: center;
  }
  .typing-cursor {
    display: inline-block;
    width: 1px;
    height: 1em;
    background: currentColor;
    margin-left: 2px;
    animation: blink 1s steps(1) infinite;
  }
  @keyframes blink {
    0%, 50% { opacity: 1; }
    51%, 100% { opacity: 0; }
  }
</style>
