// packages/react/src/components/Tabs/Tabs.jsx
import React, { useState, useEffect, useId } from 'react'
import './style.css'

const Tabs = ({
  tabs = [],
  activeIndex: controlledActiveIndex,
  onChange,
  variant = 'default',
  children,
  className = '',
  ...props
}) => {
  const tabsId = useId()
  const [internalActiveIndex, setInternalActiveIndex] = useState(controlledActiveIndex || 0)
  
  const isControlled = controlledActiveIndex !== undefined
  const activeIndex = isControlled ? controlledActiveIndex : internalActiveIndex
  
  useEffect(() => {
    if (isControlled) {
      setInternalActiveIndex(controlledActiveIndex)
    }
  }, [controlledActiveIndex, isControlled])
  
  const tabsClasses = [
    'wc-tabs',
    variant === 'pills' && 'wc-tabs--pills',
    variant === 'underline' && 'wc-tabs--underline',
    (variant === 'default' || !['pills', 'underline'].includes(variant)) && 'wc-tabs--default',
    className,
  ]
    .filter(Boolean)
    .join(' ')
  
  const getTabClasses = (index, disabled) => {
    const classes = ['wc-tab']
    if (activeIndex === index) classes.push('wc-tab--active')
    return classes.join(' ')
  }
  
  const handleTabClick = (index, tab) => {
    if (tab.disabled) return
    
    if (!isControlled) {
      setInternalActiveIndex(index)
    }
    
    if (onChange) {
      onChange(index, tab)
    }
  }
  
  const activeTab = tabs[activeIndex]

  const handleTabKeyDown = (event, index) => {
    if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return

    event.preventDefault()
    const enabledIndexes = tabs
      .map((tab, tabIndex) => (!tab.disabled ? tabIndex : -1))
      .filter((tabIndex) => tabIndex >= 0)
    if (!enabledIndexes.length) return

    const position = enabledIndexes.indexOf(index)
    let nextIndex
    if (event.key === 'Home') nextIndex = enabledIndexes[0]
    else if (event.key === 'End') nextIndex = enabledIndexes[enabledIndexes.length - 1]
    else if (event.key === 'ArrowRight') nextIndex = enabledIndexes[(position + 1) % enabledIndexes.length]
    else nextIndex = enabledIndexes[(position - 1 + enabledIndexes.length) % enabledIndexes.length]

    handleTabClick(nextIndex, tabs[nextIndex])
    event.currentTarget.parentElement?.querySelectorAll('[role="tab"]')[nextIndex]?.focus()
  }
  
  return (
    <div className="wc-tabs-wrapper" {...props}>
      <div className={tabsClasses} role="tablist" aria-label="内容分组">
        {tabs.map((tab, index) => (
          <button
            key={tab.key || index}
            className={getTabClasses(index, tab.disabled)}
            onClick={() => handleTabClick(index, tab)}
            onKeyDown={(event) => handleTabKeyDown(event, index)}
            disabled={tab.disabled}
            id={`${tabsId}-tab-${index}`}
            role="tab"
            aria-selected={activeIndex === index}
            aria-controls={`${tabsId}-panel`}
            tabIndex={activeIndex === index ? 0 : -1}
            type="button"
          >
            {tab.title}
          </button>
        ))}
      </div>
      
      <div
        id={`${tabsId}-panel`}
        className="wc-tab-content"
        role="tabpanel"
        aria-labelledby={`${tabsId}-tab-${activeIndex}`}
      >
        {typeof children === 'function' 
          ? children({ activeTab, activeIndex })
          : children
        }
      </div>
    </div>
  )
}

Tabs.displayName = 'Tabs'

export default Tabs

// packages/vue/src/components/Tabs/Tabs.vue
<template>
  <div class="wc-tabs-wrapper">
    <div
      :class="tabsClasses"
      role="tablist"
      aria-label="内容分组"
    >
      <button
        v-for="(tab, index) in tabs"
        :key="tab.key || index"
        :class="getTabClasses(index)"
        :disabled="tab.disabled"
        :id="`${tabsId}-tab-${index}`"
        role="tab"
        :aria-selected="activeIndex === index"
        :aria-controls="`${tabsId}-panel`"
        :tabindex="activeIndex === index ? 0 : -1"
        type="button"
        @click="handleTabClick(index)"
        @keydown="handleTabKeydown($event, index)"
      >
        {{ tab.title }}
      </button>
    </div>
    
    <div
      :id="`${tabsId}-panel`"
      class="wc-tab-content"
      role="tabpanel"
      :aria-labelledby="`${tabsId}-tab-${activeIndex}`"
    >
      <slot
        :active-tab="activeTab"
        :active-index="activeIndex"
      />
    </div>
  </div>
</template>

<script setup>
import './style.css'
import { computed, ref, useId, watch } from 'vue'

const props = defineProps({
  tabs: {
    type: Array,
    required: true,
    validator: (tabs) => tabs.every(tab => tab.title)
  },
  modelValue: {
    type: Number,
    default: 0
  },
  variant: {
    type: String,
    default: 'default',
    validator: (value) => ['default', 'pills', 'underline'].includes(value)
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const tabsId = useId()
const activeIndex = ref(props.modelValue)

const activeTab = computed(() => props.tabs[activeIndex.value])

const tabsClasses = computed(() => {
  const classes = ['wc-tabs']

  switch (props.variant) {
    case 'pills':
      classes.push('wc-tabs--pills')
      break
    case 'underline':
      classes.push('wc-tabs--underline')
      break
    default:
      classes.push('wc-tabs--default')
  }

  return classes
})

const getTabClasses = (index) => {
  return ['wc-tab', { 'wc-tab--active': activeIndex.value === index }]
}

const handleTabClick = (index) => {
  if (props.tabs[index]?.disabled) return
  
  activeIndex.value = index
  emit('update:modelValue', index)
  emit('change', index, props.tabs[index])
}

const handleTabKeydown = (event, index) => {
  if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return

  event.preventDefault()
  const enabledIndexes = props.tabs
    .map((tab, tabIndex) => (!tab.disabled ? tabIndex : -1))
    .filter(tabIndex => tabIndex >= 0)
  if (!enabledIndexes.length) return

  const position = enabledIndexes.indexOf(index)
  let nextIndex
  if (event.key === 'Home') nextIndex = enabledIndexes[0]
  else if (event.key === 'End') nextIndex = enabledIndexes[enabledIndexes.length - 1]
  else if (event.key === 'ArrowRight') nextIndex = enabledIndexes[(position + 1) % enabledIndexes.length]
  else nextIndex = enabledIndexes[(position - 1 + enabledIndexes.length) % enabledIndexes.length]

  handleTabClick(nextIndex)
  event.currentTarget.parentElement?.querySelectorAll('[role="tab"]')[nextIndex]?.focus()
}

watch(
  () => props.modelValue,
  (newValue) => {
    activeIndex.value = newValue
  }
)
</script>
