// packages/angular/src/components/Button/Fab.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  input,
  output,
} from '@angular/core'

@Component({
  selector: 'wc-fab',
  standalone: true,
  template: `
    <button [class]="buttonClasses()" [disabled]="disabled()" type="button" (click)="handleClick($event)">
      <span class="fab-icon">
        @if (icon()) {
          <span [innerHTML]="icon()"></span>
        }
        @if (variant() !== 'extended') {
          <ng-content />
        }
      </span>
      @if (variant() === 'extended') {
        <span class="fab-label">{{ label() }}<ng-content /></span>
      }
    </button>
  `,
  styleUrl: './style.css',
  styles: [':host{display:contents}'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Fab {
  readonly variant = input<'circular' | 'extended'>('circular')
  readonly size = input<'sm' | 'md' | 'lg'>('md')
  readonly color = input<'primary' | 'secondary' | 'inherit'>('primary')
  readonly disabled = input(false)
  readonly label = input('')
  readonly icon = input('')
  readonly clicked = output<MouseEvent>()

  readonly buttonClasses = computed(() =>
    [
      'wc-fab',
      `wc-fab--${this.variant()}`,
      `wc-fab--${this.size()}`,
      `wc-fab--${this.color()}`,
      this.disabled() && 'wc-fab--disabled',
    ]
      .filter(Boolean)
      .join(' ')
  )

  handleClick(event: MouseEvent): void {
    if (!this.disabled()) this.clicked.emit(event)
  }
}

// packages/solid/src/components/Button/Fab.tsx
import { createSignal } from 'solid-js'

import './style.css'

const Fab = ({
  variant = 'circular',
  size = 'md',
  color = 'primary',
  disabled = false,
  label = '',
  icon = '',
  children,
  onClick,
  onFocus,
  onBlur,
  className = '',
  style = {},
  ...props
}) => {
  const [focused, setFocused] = createSignal(false)

  // 验证props
  const validVariants = ['circular', 'extended']
  const validSizes = ['sm', 'md', 'lg']
  const validColors = ['primary', 'secondary', 'inherit']

  if (!validVariants.includes(variant)) {
    console.warn(`Invalid variant "${variant}" for Fab component. Valid variants are: ${validVariants.join(', ')}`)
  }
  if (!validSizes.includes(size)) {
    console.warn(`Invalid size "${size}" for Fab component. Valid sizes are: ${validSizes.join(', ')}`)
  }
  if (!validColors.includes(color)) {
    console.warn(`Invalid color "${color}" for Fab component. Valid colors are: ${validColors.join(', ')}`)
  }

  // 构建CSS类名
  const buttonClasses = [
    'wc-fab',
    `wc-fab--${variant}`,
    `wc-fab--${size}`,
    `wc-fab--${color}`,
    disabled && 'wc-fab--disabled',
    focused && 'wc-fab--focused',
    className
  ].filter(Boolean).join(' ')

  const handleClick = (event) => {
    if (!disabled && onClick) {
      onClick(event)
    }
  }

  const handleFocus = (event) => {
    setFocused(true)
    onFocus?.(event)
  }

  const handleBlur = (event) => {
    setFocused(false)
    onBlur?.(event)
  }

  return (
    <button
      class={buttonClasses}
      disabled={disabled}
      onClick={handleClick}
      onFocus={handleFocus}
      onBlur={handleBlur}
      style={style}
      {...props}
    >
      {/* Icon */}
      {(icon || children) && (
        <span class="fab-icon">
          {icon ? (
            <span innerHTML={icon} />
          ) : (
            children
          )}
        </span>
      )}
      
      {/* Label (for extended variant) */}
      {variant === 'extended' && label && (
        <span class="fab-label">
          {label}
        </span>
      )}
    </button>
  )
}

Fab.displayName = 'Fab'

export default Fab
