// packages/react/src/components/Stack/Stack.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { COMPOSITION_ALIGNS, COMPOSITION_GAPS } from '../../composition.js'
import './style.css'

const Stack = ({
  as: Component = 'div',
  gap = 'md',
  align = 'stretch',
  className = '',
  children,
  ...props
}) => (
  <Component
    className={['wc-stack', className].filter(Boolean).join(' ')}
    data-gap={gap}
    data-align={align}
    {...props}
  >
    {children}
  </Component>
)

Stack.displayName = 'Stack'
Stack.propTypes = {
  as: PropTypes.elementType,
  gap: PropTypes.oneOf(COMPOSITION_GAPS),
  align: PropTypes.oneOf(COMPOSITION_ALIGNS),
  className: PropTypes.string,
  children: PropTypes.node,
}
export default Stack

// packages/vue/src/components/Stack/Stack.vue
<template>
  <component
    :is="as"
    class="wc-stack"
    :data-gap="gap"
    :data-align="align"
    v-bind="$attrs"
  >
    <slot />
  </component>
</template>

<script setup lang="ts">
import { COMPOSITION_ALIGNS, COMPOSITION_GAPS } from '../../composition'
import type { CompositionAlign, CompositionGap } from '@zeturn/watercolor-core'
import type { PropType } from 'vue'
import './style.css'

defineOptions({ inheritAttrs: false })
defineProps({
  as: { type: String, default: 'div' },
  gap: {
    type: String as PropType<CompositionGap>,
    default: 'md',
    validator: (value: string) => COMPOSITION_GAPS.includes(value as CompositionGap)
  },
  align: {
    type: String as PropType<CompositionAlign>,
    default: 'stretch',
    validator: (value: string) => COMPOSITION_ALIGNS.includes(value as CompositionAlign)
  }
})
</script>
