// src/components/Avatar/Avatar.vue
<template>
  <div :class="avatarClasses" :style="avatarStyles">
    <img v-if="src && !imgError" :src="src" :alt="alt" @error="handleImgError" @load="handleImgLoad" />
    <span v-else-if="!src && children" class="wc-avatar-text">
      {{ avatarText }}
    </span>
    <slot v-else />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { 
  isValidSize, 
  isValidVariant, 
  isValidColor,
  getAvatarClasses,
  getAvatarStyles,
  generateAvatarText,
  handleImageError,
  handleImageLoad
} from './utils.js'
import './style.css'

const props = defineProps({
  src: {
    type: String,
    default: ''
  },
  alt: {
    type: String,
    default: ''
  },
  size: {
    type: [String, Number],
    default: 'md',
    validator: isValidSize
  },
  variant: {
    type: String,
    default: 'circular',
    validator: isValidVariant
  },
  color: {
    type: String,
    default: 'default',
    validator: isValidColor
  },
  children: {
    type: String,
    default: ''
  }
})

const imgError = ref(false)

const avatarClasses = computed(() => 
  getAvatarClasses({
    size: props.size,
    variant: props.variant,
    color: props.color,
    src: props.src,
    imgError: imgError.value
  })
)

const avatarStyles = computed(() => getAvatarStyles(props.size))

const avatarText = computed(() => generateAvatarText(props.children))

const handleImgError = () => handleImageError((value) => { imgError.value = value })

const handleImgLoad = () => handleImageLoad((value) => { imgError.value = value })
</script>

// src/components/Avatar/Avatar.jsx
import React, { useState } from 'react'
import { 
  getAvatarClasses, 
  getAvatarStyles, 
  generateAvatarText,
  handleImageError,
  handleImageLoad
} from './utils.js'
import './style.css'

const Avatar = ({
  src = '',
  alt = '',
  size = 'md',
  variant = 'circular',
  color = 'default',
  children = '',
  className = '',
  ...props
}) => {
  const [imgError, setImgError] = useState(false)

  const avatarClasses = getAvatarClasses({ 
    size, 
    variant, 
    color, 
    src, 
    imgError 
  }).concat(className).filter(Boolean).join(' ')

  const avatarStyles = getAvatarStyles(size)
  const avatarText = generateAvatarText(children)

  const onImageError = () => handleImageError(setImgError)
  const onImageLoad = () => handleImageLoad(setImgError)

  return (
    <div className={avatarClasses} style={avatarStyles} {...props}>
      {src && !imgError ? (
        <img 
          src={src} 
          alt={alt} 
          onError={onImageError} 
          onLoad={onImageLoad} 
        />
      ) : children ? (
        <span className="wc-avatar-text">
          {avatarText}
        </span>
      ) : null}
    </div>
  )
}

Avatar.displayName = 'Avatar'

export default Avatar
