// src/components/Snackbar/Snackbar.jsx
import React, { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'

const iconMap = {
  success: '✓',
  info: 'ℹ',
  warning: '⚠',
  error: '✕'
}

export default function Snackbar({
  open = false,
  message = '',
  title = '',
  severity = 'info',
  variant = 'filled',
  autoHideDuration = 6000,
  anchorOrigin = { vertical: 'bottom', horizontal: 'left' },
  action: actionLabel = '',
  closable = true,
  showIcon = true,
  showProgress = false,
  onClose = () => {},
  onAction = () => {},
  children,
}) {
  const [visible, setVisible] = useState(open)
  const [progress, setProgress] = useState(100)

  useEffect(() => {
    setVisible(open)
    if (open) {
      setProgress(100)
    }
  }, [open])

  useEffect(() => {
    if (!visible || autoHideDuration <= 0) return
    
    const startTime = Date.now()
    const timer = setTimeout(() => {
      handleClose()
    }, autoHideDuration)
    
    // Progress bar animation
    if (showProgress) {
      const progressTimer = setInterval(() => {
        const elapsed = Date.now() - startTime
        const remaining = Math.max(0, 100 - (elapsed / autoHideDuration) * 100)
        setProgress(remaining)
        
        if (remaining <= 0) {
          clearInterval(progressTimer)
        }
      }, 50)
      
      return () => {
        clearTimeout(timer)
        clearInterval(progressTimer)
      }
    }
    
    return () => clearTimeout(timer)
  }, [visible, autoHideDuration, showProgress])

  const handleClose = () => {
    setVisible(false)
    onClose()
  }

  const handleAction = () => {
    onAction()
  }

  if (!visible) return null

  const baseClasses = 'fixed z-50 w-full max-w-sm bg-white dark:bg-neutral-800 rounded-lg shadow-lg border border-neutral-200 dark:border-neutral-700 p-4 transition-all duration-300 ease-in-out'
  const classes = [baseClasses]
  
  // Position classes
  const { vertical, horizontal } = anchorOrigin
  classes.push(vertical === 'top' ? 'top-4' : 'bottom-4')
  
  if (horizontal === 'left') classes.push('left-4')
  else if (horizontal === 'right') classes.push('right-4')
  else classes.push('left-1/2 transform -translate-x-1/2')
  
  // Variant styles
  if (variant === 'filled') {
    const colorMap = {
      success: 'bg-success-500 border-success-500',
      info: 'bg-primary-500 border-primary-500',
      warning: 'bg-warning-500 border-warning-500',
      error: 'bg-error-500 border-error-500',
    }
    classes.push(colorMap[severity])
  } else if (variant === 'outlined') {
    const colorMap = {
      success: 'border-success-500 text-success-600 dark:text-success-400 border-l-4',
      info: 'border-primary-500 text-primary-600 dark:text-primary-400 border-l-4',
      warning: 'border-warning-500 text-warning-600 dark:text-warning-400 border-l-4',
      error: 'border-error-500 text-error-600 dark:text-error-400 border-l-4',
    }
    classes.push(colorMap[severity])
  } else {
    classes.push('text-neutral-900 dark:text-neutral-100')
  }

  const actionClasses =
    variant === 'filled'
      ? 'hover:bg-white hover:bg-opacity-20 focus:ring-white text-sm font-medium px-3 py-1 rounded-md transition-colors'
      : {
          success: 'text-success-600 dark:text-success-400 hover:bg-success-50 dark:hover:bg-success-900/20',
          info: 'text-primary-600 dark:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/20',
          warning: 'text-warning-600 dark:text-warning-400 hover:bg-warning-50 dark:hover:bg-warning-900/20',
          error: 'text-error-600 dark:text-error-400 hover:bg-error-50 dark:hover:bg-error-900/20',
        }[severity] + ' text-sm font-medium px-3 py-1 rounded-md transition-colors'

  const closeButtonClasses =
    variant === 'filled'
      ? 'inline-flex rounded-md p-1 hover:bg-white hover:bg-opacity-20 transition-colors'
      : 'inline-flex rounded-md p-1 text-neutral-400 hover:text-neutral-500 transition-colors'

  const iconClasses = variant === 'filled' 
    ? 'text-gray' 
    : {
        success: 'text-success-500',
        info: 'text-primary-500',
        warning: 'text-warning-500',
        error: 'text-error-500'
      }[severity]

  const node = (
    <div className={classes.join(' ')} role="alert" aria-live="assertive" aria-atomic="true">
      <div className="flex items-start gap-3 w-full">
        {/* Icon */}
        {showIcon && (
          <div className={`flex-shrink-0 w-5 h-5 flex items-center justify-center font-bold text-lg ${iconClasses}`}>
            {iconMap[severity]}
          </div>
        )}
        
        {/* Content */}
        <div className="flex-1 min-w-0">
          {title && (
            <div className="font-semibold text-sm mb-1 leading-tight">
              {title}
            </div>
          )}
          {children || <div className="text-sm">{message}</div>}
        </div>
        
        {/* Action */}
        {(actionLabel || children?.action) && (
          <div className="flex-shrink-0">
            {children?.action || (
              <button className={actionClasses} onClick={handleAction} type="button">
                {actionLabel}
              </button>
            )}
          </div>
        )}
        
        {/* Close Button */}
        {closable && (
          <div className="flex-shrink-0">
            <button className={closeButtonClasses} onClick={handleClose} aria-label="关闭" type="button">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
              </svg>
            </button>
          </div>
        )}
      </div>
      
      {/* Progress Bar */}
      {showProgress && autoHideDuration > 0 && (
        <div className="mt-3 w-full bg-gray-200 dark:bg-gray-700 rounded-full h-1">
          <div 
            className={`h-1 rounded-full transition-all duration-100 ${
              variant === 'filled' 
                ? 'bg-white bg-opacity-30' 
                : {
                    success: 'bg-success-500',
                    info: 'bg-primary-500',
                    warning: 'bg-warning-500',
                    error: 'bg-error-500'
                  }[severity]
            }`}
            style={{ width: `${progress}%` }}
          />
        </div>
      )}
    </div>
  )

  return createPortal(node, document.body)
}

// src/components/Snackbar/Snackbar.vue
<template>
  <teleport to="body">
    <transition
      name="snackbar"
      enter-active-class="transition ease-out duration-300"
      enter-from-class="opacity-0 translate-y-2"
      enter-to-class="opacity-100 translate-y-0"
      leave-active-class="transition ease-in duration-200"
      leave-from-class="opacity-100 translate-y-0"
      leave-to-class="opacity-0 translate-y-2"
    >
      <div 
        v-if="open" 
        :class="snackbarClasses"
        role="alert"
        aria-live="assertive"
        aria-atomic="true"
      >
        <div class="flex items-start gap-3 w-full">
          <!-- Icon -->
          <div 
            v-if="showIcon"
            :class="iconClasses"
            class="flex-shrink-0 w-5 h-5 flex items-center justify-center font-bold text-lg"
          >
            {{ iconText }}
          </div>
          
          <!-- Content -->
          <div class="flex-1 min-w-0">
            <div
              v-if="title"
              class="font-semibold text-sm mb-1 leading-tight"
            >
              {{ title }}
            </div>
            <slot>
              <div class="text-sm">
                {{ message }}
              </div>
            </slot>
          </div>
          
          <!-- Action -->
          <div
            v-if="$slots.action || action"
            class="flex-shrink-0"
          >
            <slot name="action">
              <button
                v-if="action"
                type="button"
                :class="actionClasses"
                @click="handleActionClick"
              >
                {{ action }}
              </button>
            </slot>
          </div>
          
          <!-- Close Button -->
          <div
            v-if="closable"
            class="flex-shrink-0"
          >
            <button 
              type="button"
              :class="closeButtonClasses"
              aria-label="关闭"
              @click="handleClose"
            >
              <svg
                class="w-4 h-4"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"
                />
              </svg>
            </button>
          </div>
        </div>
        
        <!-- Progress Bar -->
        <div 
          v-if="showProgress && autoHideDuration > 0"
          class="mt-3 w-full bg-gray-200 dark:bg-gray-700 rounded-full h-1"
        >
          <div 
            :class="progressBarClasses"
            class="h-1 rounded-full transition-all duration-100"
            :style="{ width: `${progress}%` }"
          />
        </div>
      </div>
    </transition>
  </teleport>
</template>

<script setup>
import { computed, watch, onMounted, onUnmounted, ref } from 'vue'

const props = defineProps({
  open: {
    type: Boolean,
    default: false
  },
  message: {
    type: String,
    default: ''
  },
  title: {
    type: String,
    default: ''
  },
  autoHideDuration: {
    type: Number,
    default: 6000
  },
  anchorOrigin: {
    type: Object,
    default: () => ({ vertical: 'bottom', horizontal: 'left' })
  },
  severity: {
    type: String,
    default: 'info',
    validator: (value) => ['success', 'info', 'warning', 'error'].includes(value)
  },
  variant: {
    type: String,
    default: 'filled',
    validator: (value) => ['filled', 'outlined', 'standard'].includes(value)
  },
  action: {
    type: String,
    default: ''
  },
  closable: {
    type: Boolean,
    default: true
  },
  showIcon: {
    type: Boolean,
    default: true
  },
  showProgress: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['close', 'action'])

const iconMap = {
  success: '✓',
  info: 'ℹ',
  warning: '⚠',
  error: '✕'
}

let autoHideTimer = null
let progressTimer = null
const progress = ref(100)

const snackbarClasses = computed(() => {
  const baseClasses = 'fixed z-50 w-full max-w-sm bg-white dark:bg-neutral-800 rounded-lg shadow-lg border border-neutral-200 dark:border-neutral-700 p-4 transition-all duration-300 ease-in-out'
  const classes = [baseClasses]
  
  // Position classes
  const { vertical, horizontal } = props.anchorOrigin
  
  if (vertical === 'top') {
    classes.push('top-4')
  } else {
    classes.push('bottom-4')
  }
  
  if (horizontal === 'left') {
    classes.push('left-4')
  } else if (horizontal === 'right') {
    classes.push('right-4')
  } else {
    classes.push('left-1/2 transform -translate-x-1/2')
  }
  
  // Variant styles
  if (props.variant === 'filled') {
    const colorMap = {
      success: 'bg-success-500 border-success-500',
      info: 'bg-primary-500 border-primary-500',
      warning: 'bg-warning-500 border-warning-500',
      error: 'bg-error-500 border-error-500'
    }
    classes.push(colorMap[props.severity])
  } else if (props.variant === 'outlined') {
    const colorMap = {
      success: 'border-success-500 text-success-600 dark:text-success-400 border-l-4',
      info: 'border-primary-500 text-primary-600 dark:text-primary-400 border-l-4',
      warning: 'border-warning-500 text-warning-600 dark:text-warning-400 border-l-4',
      error: 'border-error-500 text-error-600 dark:text-error-400 border-l-4'
    }
    classes.push(colorMap[props.severity])
  } else {
    classes.push('text-neutral-900 dark:text-neutral-100')
  }
  
  return classes
})

const actionClasses = computed(() => {
  const baseClasses = 'text-sm font-medium px-3 py-1 rounded-md transition-colors duration-150 focus:outline-none focus:ring-2 focus:ring-offset-2'
  const classes = [baseClasses]
  
  if (props.variant === 'filled') {
    classes.push('hover:bg-white hover:bg-opacity-20 focus:ring-white')
  } else {
    const colorMap = {
      success: 'text-success-600 dark:text-success-400 hover:bg-success-50 dark:hover:bg-success-900/20 focus:ring-success-500',
      info: 'text-primary-600 dark:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/20 focus:ring-primary-500',
      warning: 'text-warning-600 dark:text-warning-400 hover:bg-warning-50 dark:hover:bg-warning-900/20 focus:ring-warning-500',
      error: 'text-error-600 dark:text-error-400 hover:bg-error-50 dark:hover:bg-error-900/20 focus:ring-error-500'
    }
    classes.push(colorMap[props.severity])
  }
  
  return classes
})

const closeButtonClasses = computed(() => {
  const baseClasses = 'inline-flex rounded-md p-1 focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors duration-150'
  const classes = [baseClasses]
  
  if (props.variant === 'filled') {
    classes.push('hover:bg-white hover:bg-opacity-20 focus:ring-white')
  } else {
    const colorMap = {
      success: 'text-success-400 hover:text-success-500 focus:ring-success-500',
      info: 'text-primary-400 hover:text-primary-500 focus:ring-primary-500',
      warning: 'text-warning-400 hover:text-warning-500 focus:ring-warning-500',
      error: 'text-error-400 hover:text-error-500 focus:ring-error-500'
    }
    classes.push(colorMap[props.severity] || 'text-neutral-400 hover:text-neutral-500 focus:ring-neutral-500')
  }
  
  return classes
})

const iconClasses = computed(() => {
  if (props.variant === 'filled') {
    return 'text-gray'
  } else {
    const colorMap = {
      success: 'text-success-500',
      info: 'text-primary-500',
      warning: 'text-warning-500',
      error: 'text-error-500'
    }
    return colorMap[props.severity]
  }
})

const progressBarClasses = computed(() => {
  if (props.variant === 'filled') {
    return 'bg-white bg-opacity-30'
  } else {
    const colorMap = {
      success: 'bg-success-500',
      info: 'bg-primary-500',
      warning: 'bg-warning-500',
      error: 'bg-error-500'
    }
    return colorMap[props.severity]
  }
})

const iconText = computed(() => iconMap[props.severity] || iconMap.info)

const handleClose = () => emit('close')
const handleActionClick = () => emit('action')

const startAutoHideTimer = () => {
  if (props.autoHideDuration > 0) {
    progress.value = 100
    const startTime = Date.now()
    
    autoHideTimer = setTimeout(() => {
      handleClose()
    }, props.autoHideDuration)
    
    // Progress bar animation
    if (props.showProgress) {
      progressTimer = setInterval(() => {
        const elapsed = Date.now() - startTime
        const remaining = Math.max(0, 100 - (elapsed / props.autoHideDuration) * 100)
        progress.value = remaining
        
        if (remaining <= 0) {
          clearInterval(progressTimer)
        }
      }, 50)
    }
  }
}

const clearTimers = () => {
  if (autoHideTimer) {
    clearTimeout(autoHideTimer)
    autoHideTimer = null
  }
  if (progressTimer) {
    clearInterval(progressTimer)
    progressTimer = null
  }
}

watch(() => props.open, (newVal) => {
  if (newVal) {
    startAutoHideTimer()
  } else {
    clearTimers()
  }
})

onMounted(() => {
  if (props.open) startAutoHideTimer()
})

onUnmounted(() => clearTimers())
</script>
