// src/components/Box/Box.vue
<template>
  <component 
    :is="component" 
    :class="boxClasses"
    :style="computedStyles"
  >
    <slot />
  </component>
</template>

<script setup>
import { computed } from 'vue'
import { getBoxClasses, getBoxStyles } from './utils.js'
import './style.css'

const props = defineProps({
  component: {
    type: String,
    default: 'div'
  },
  // Spacing props
  p: [String, Number],
  pt: [String, Number],
  pr: [String, Number],
  pb: [String, Number],
  pl: [String, Number],
  px: [String, Number],
  py: [String, Number],
  m: [String, Number],
  mt: [String, Number],
  mr: [String, Number],
  mb: [String, Number],
  ml: [String, Number],
  mx: [String, Number],
  my: [String, Number],
  // Display
  display: String,
  // Flexbox
  flexDirection: String,
  justifyContent: String,
  alignItems: String,
  flexWrap: String,
  gap: [String, Number],
  // Colors
  bgcolor: String,
  color: String,
  // Border
  border: [String, Number],
  borderRadius: [String, Number],
  // Width and Height
  width: [String, Number],
  height: [String, Number],
  minWidth: [String, Number],
  minHeight: [String, Number],
  maxWidth: [String, Number],
  maxHeight: [String, Number],
})

const boxClasses = computed(() => getBoxClasses(props))

const computedStyles = computed(() => getBoxStyles(props))
</script>

// src/components/Box/Box.jsx
import React from 'react'
import './style.css'
import { getBoxClasses, getBoxStyles } from './utils.js'

/**
 * 通用布局组件 Box (React)
 * 和 Vue 版保持接口一致，尽量通过 style 而非 class 实现，保证灵活性
 */
export default function Box({
  component: Comp = 'div',
  children,
  className = '',
  // Spacing
  p, pt, pr, pb, pl, px, py,
  m, mt, mr, mb, ml, mx, my,
  // Flex & layout
  display,
  flexDirection,
  justifyContent,
  alignItems,
  flexWrap,
  gap,
  // Colors & border
  bgcolor,
  color,
  border,
  borderRadius,
  // Size
  width, height, minWidth, minHeight, maxWidth, maxHeight,
  style: styleProp = {},
  ...rest
}) {
  const boxClasses = getBoxClasses({
    display, flexDirection, justifyContent, alignItems, flexWrap, gap
  }).concat(className).filter(Boolean).join(' ')

  const boxStyles = {
    ...getBoxStyles({
      p, pt, pr, pb, pl, px, py,
      m, mt, mr, mb, ml, mx, my,
      display, flexDirection, justifyContent, alignItems, flexWrap, gap,
      bgcolor, color, border, borderRadius,
      width, height, minWidth, minHeight, maxWidth, maxHeight
    }),
    ...styleProp
  }

  return (
    <Comp className={boxClasses} style={boxStyles} {...rest}>
      {children}
    </Comp>
  )
}
