// packages/angular/src/components/PricingTable/PricingTable.ts
import { ChangeDetectionStrategy, Component, ViewEncapsulation, input, output } from '@angular/core'

export interface PricingPlan {
  name: string
  price?: string
  features?: string[]
  cta?: string
  highlighted?: boolean
}

@Component({
  selector: 'wc-pricing-table',
  standalone: true,
  template: `
    <div class="wc-pricing {{ className() }}">
      @for (plan of plans(); track plan.name) {
        <div class="wc-pricing__card {{ plan.highlighted ? 'wc-pricing__card--highlighted' : '' }}">
          <div class="wc-pricing__name">{{ plan.name }}</div>
          @if (plan.price) {
            <div class="wc-pricing__price">{{ plan.price }}</div>
          }
          @if (plan.features) {
            <ul class="wc-pricing__features">
              @for (feature of plan.features; track feature) {
                <li>{{ feature }}</li>
              }
            </ul>
          }
          @if (plan.cta) {
            <button class="wc-pricing__cta" (click)="selected.emit(plan)">{{ plan.cta }}</button>
          }
        </div>
      }
    </div>
  `,
  styles: [
    ':host{display:contents}',
    `.wc-pricing{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;box-sizing:border-box}
.wc-pricing__card{display:flex;flex-direction:column;gap:12px;padding:24px;border:1px solid var(--wc-border-default,rgba(0,0,0,0.1));border-radius:12px;background:var(--wc-surface-canvas,#fff);color:var(--wc-text-primary,#1a1a1a)}
.wc-pricing__card--highlighted{border-color:var(--wc-accent,#3b82f6);box-shadow:0 4px 16px rgba(59,130,246,0.15)}
.wc-pricing__name{font-size:1.125rem;font-weight:700}
.wc-pricing__price{font-size:2rem;font-weight:800}
.wc-pricing__features{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:6px;font-size:0.875rem;color:var(--wc-text-secondary,#6b7280)}
.wc-pricing__cta{margin-top:auto;padding:10px 16px;border:0;border-radius:8px;background:var(--wc-accent,#3b82f6);color:#fff;font:inherit;font-weight:600;cursor:pointer}`,
  ],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PricingTable {
  readonly plans = input<PricingPlan[]>([])
  readonly className = input('')
  readonly selected = output<PricingPlan>()
}

// src/components/PricingTable/PricingTable.vue
<template>
  <div class="pricing-grid" :style="gridStyle">
    <div v-for="plan in plans" :key="plan.name" class="plan-card" :class="{ popular: plan.popular }">
      <h3 class="plan-name">{{ plan.name }}</h3>
      <p class="plan-price">{{ plan.price }}</p>
      <ul class="plan-features">
        <li v-for="f in plan.features" :key="f">{{ f }}</li>
      </ul>
      <button class="plan-btn">{{ plan.button || '选择' }}</button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PricingTable',
  props: {
    plans: { type: Array, default: () => [] },
    columns: { type: Number, default: 3 },
  },
  computed: {
    gridStyle() { return { gridTemplateColumns: `repeat(${this.columns}, minmax(0,1fr))` } }
  }
}
</script>

<style scoped>
.pricing-grid{display:grid;gap:24px;}
.plan-card{border:1px solid var(--color-border,#e5e7eb);border-radius:8px;padding:24px;text-align:center;background:white;display:flex;flex-direction:column;gap:12px;}
.plan-card.popular{border-width:2px;border-color:var(--color-primary,#3b82f6);} .plan-name{margin:0;font-size:1.25rem;font-weight:600;} .plan-price{margin:0;font-size:2rem;color:var(--color-primary,#3b82f6);} .plan-features{list-style:none;padding:0;margin:0;flex:1 1 auto;text-align:left;font-size:0.875rem;}
.plan-btn{padding:8px 16px;border-radius:4px;border:none;background:var(--color-primary,#3b82f6);color:white;cursor:pointer;font-size:0.875rem;}
@media(prefers-color-scheme:dark){.plan-card{background:var(--color-dark-surface,#1f2937);border-color:var(--color-dark-border,#374151);} .plan-btn{background:var(--color-primary,#3b82f6);} }
</style>
