// packages/vue/src/components/PricingTable/PricingTable.vue
<template>
  <div
    class="pricing-grid"
    :style="gridStyle"
  >
    <div
      v-for="plan in plans"
      :key="plan.name"
      class="plan-card"
      :class="{ popular: plan.popular }"
    >
      <h3 class="plan-name">
        {{ plan.name }}
      </h3>
      <p class="plan-price">
        {{ plan.price }}
      </p>
      <ul class="plan-features">
        <li
          v-for="f in plan.features"
          :key="f"
        >
          {{ f }}
        </li>
      </ul>
      <button class="plan-btn">
        {{ plan.button || '选择' }}
      </button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PricingTable',
  props: {
    plans: { type: Array, default: () => [] },
    columns: { type: Number, default: 3 },
  },
  computed: {
    gridStyle() { return { gridTemplateColumns: `repeat(${this.columns}, minmax(0,1fr))` } }
  }
}
</script>

<style src="./style.css"></style>

// src/components/PricingTable/PricingTable.jsx
import React from 'react'

/**
 * PricingTable – React 组件
 * Props
 *   plans   Array<{name,price,features,button,popular}>
 *   columns number
 */
export default function PricingTable({ plans = [], columns = 3, className = '' }) {
  const gridStyle = {
    gridTemplateColumns: `repeat(${columns}, minmax(0,1fr))`,
  }

  return (
    <div className={`pricing-grid ${className}`.trim()} style={gridStyle}>
      {plans.map((plan) => (
        <div key={plan.name} className={`plan-card${plan.popular ? ' popular' : ''}`}>
          <h3 className="plan-name">{plan.name}</h3>
          <p className="plan-price">{plan.price}</p>
          <ul className="plan-features">
            {plan.features?.map((f) => (
              <li key={f}>{f}</li>
            ))}
          </ul>
          <button className="plan-btn">{plan.button || '选择'}</button>
        </div>
      ))}
    </div>
  )
}
