// packages/react/src/components/VideoPlayer/VideoPlayer.jsx
import React, { useRef, useState, useEffect } from 'react'
import { useLocale } from '../../LocaleReact'
import { formatTime, calculateSeekPosition, toggleFullscreen } from './utils'
import './style.css'

const PlayIcon = () => (
  <svg className="video-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M8 5.5v13l10-6.5-10-6.5Z" />
  </svg>
)

const PauseIcon = () => (
  <svg className="video-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M8 6v12" />
    <path d="M16 6v12" />
  </svg>
)

const VolumeIcon = () => (
  <svg className="video-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M4 10v4h4l5 4V6L8 10H4Z" />
    <path d="M16 9.5a4 4 0 0 1 0 5" />
    <path d="M18.5 7a7.5 7.5 0 0 1 0 10" />
  </svg>
)

const MutedIcon = () => (
  <svg className="video-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M4 10v4h4l5 4V6L8 10H4Z" />
    <path d="m17 10 4 4" />
    <path d="m21 10-4 4" />
  </svg>
)

const FullscreenIcon = () => (
  <svg className="video-icon" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M8 4H4v4" />
    <path d="M16 4h4v4" />
    <path d="M20 16v4h-4" />
    <path d="M4 16v4h4" />
  </svg>
)

const VideoPlayer = ({
  src,
  autoplay = false,
  loop = false,
  className = '',
  style = {},
  ...rest
}) => {
  const { messages } = useLocale()
  const videoRef = useRef(null)
  const [playing, setPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [volume, setVolume] = useState(0.7)
  const [muted, setMuted] = useState(false)
  const [duration, setDuration] = useState(0)
  const [current, setCurrent] = useState(0)

  const formattedCurrent = formatTime(current)
  const formattedDuration = formatTime(duration)

  const togglePlay = () => {
    const v = videoRef.current
    if (!v) return
    if (v.paused) {
      v.play()
    } else {
      v.pause()
    }
  }

  const updateProgress = () => {
    const v = videoRef.current
    if (!v) return
    setDuration(v.duration || 0)
    setCurrent(v.currentTime)
    setProgress(v.duration ? (v.currentTime / v.duration) * 100 : 0)
    setPlaying(!v.paused)
  }

  const seek = (e) => {
    const v = videoRef.current
    if (v) {
      v.currentTime = calculateSeekPosition(e, duration)
    }
  }

  const toggleMute = () => {
    setMuted((prev) => {
      const next = !prev
      if (videoRef.current) videoRef.current.muted = next
      return next
    })
  }

  const handleFullscreen = () => {
    toggleFullscreen(videoRef.current?.parentElement)
  }

  // sync volume
  useEffect(() => {
    if (videoRef.current) videoRef.current.volume = volume
  }, [volume])

  useEffect(() => {
    const v = videoRef.current
    if (!v) return
    v.muted = muted
    v.loop = loop
    if (autoplay) v.play()
  }, [autoplay, loop, muted])

  return (
    <div className={`video-wrapper ${className}`} style={style} {...rest}>
      <video
        ref={videoRef}
        className="video-el"
        src={src}
        onTimeUpdate={updateProgress}
        onEnded={() => setPlaying(false)}
      />
      <div className="controls">
        <button className="ctrl-btn" aria-label={playing ? messages.pauseVideo : messages.playVideo} onClick={togglePlay}>{playing ? <PauseIcon /> : <PlayIcon />}</button>
        <div className="progress" role="slider" tabIndex={0} aria-label={messages.videoProgress} aria-valuenow={Math.round(progress)} aria-valuemin={0} aria-valuemax={100} onClick={seek}>
          <div className="progress-bar" style={{ width: `${progress}%` }} />
        </div>
        <span className="time">{formattedCurrent} / {formattedDuration}</span>
        <button className="ctrl-btn" aria-label={muted ? messages.unmuteVideo : messages.muteVideo} onClick={toggleMute}>{muted ? <MutedIcon /> : <VolumeIcon />}</button>
        <input className="volume" type="range" min="0" max="1" step="0.05" value={volume} aria-label={messages.volume} onChange={(e)=>setVolume(Number(e.target.value))} />
        <button className="ctrl-btn" aria-label={messages.enterFullscreen} onClick={handleFullscreen}><FullscreenIcon /></button>
      </div>
    </div>
  )
}

VideoPlayer.displayName = 'VideoPlayer'
export default VideoPlayer

// packages/vue/src/components/VideoPlayer/VideoPlayer.vue
<template>
  <div class="video-wrapper">
    <video
      ref="video"
      class="video-el"
      :src="src"
      @timeupdate="updateProgress"
      @ended="onEnded"
    />
    <div class="controls">
      <button
        class="ctrl-btn"
        :aria-label="playing ? messages.pauseVideo : messages.playVideo"
        @click="togglePlay"
      >
        <svg
          v-if="playing"
          class="video-icon"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path d="M8 6v12" />
          <path d="M16 6v12" />
        </svg>
        <svg
          v-else
          class="video-icon"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path d="M8 5.5v13l10-6.5-10-6.5Z" />
        </svg>
      </button>
      <div
        class="progress"
        role="slider"
        tabindex="0"
        :aria-label="messages.videoProgress"
        :aria-valuenow="Math.round(progress)"
        aria-valuemin="0"
        aria-valuemax="100"
        @click="seek($event)"
      >
        <div
          class="progress-bar"
          :style="{ width: progress + '%' }"
        />
      </div>
      <span class="time">{{ formattedCurrent }} / {{ formattedDuration }}</span>
      <button
        class="ctrl-btn"
        :aria-label="muted ? messages.unmuteVideo : messages.muteVideo"
        @click="toggleMute"
      >
        <svg
          v-if="muted"
          class="video-icon"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path d="M4 10v4h4l5 4V6L8 10H4Z" />
          <path d="m17 10 4 4" />
          <path d="m21 10-4 4" />
        </svg>
        <svg
          v-else
          class="video-icon"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path d="M4 10v4h4l5 4V6L8 10H4Z" />
          <path d="M16 9.5a4 4 0 0 1 0 5" />
          <path d="M18.5 7a7.5 7.5 0 0 1 0 10" />
        </svg>
      </button>
      <input
        v-model.number="volume"
        class="volume"
        type="range"
        min="0"
        max="1"
        step="0.05"
        :aria-label="messages.volume"
      >
      <button
        class="ctrl-btn"
        :aria-label="messages.enterFullscreen"
        @click="handleFullscreen"
      >
        <svg
          class="video-icon"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path d="M8 4H4v4" />
          <path d="M16 4h4v4" />
          <path d="M20 16v4h-4" />
          <path d="M4 16v4h4" />
        </svg>
      </button>
    </div>
  </div>
</template>

<script>
import { ref, computed, onMounted, watch } from 'vue'
import { useLocale } from '../../LocaleVUE'
import { formatTime, calculateSeekPosition, toggleFullscreen } from './utils'
import './style.css'

export default {
  name: 'VideoPlayer',
  props: {
    src: { type: String, required: true },
    autoplay: { type: Boolean, default: false },
    loop: { type: Boolean, default: false },
  },
  setup(props) {
    const { messages } = useLocale()
    const video = ref(null)
    const playing = ref(false)
    const progress = ref(0)
    const volume = ref(0.7)
    const muted = ref(false)
    const duration = ref(0)
    const current = ref(0)

    const formattedCurrent = computed(() => formatTime(current.value))
    const formattedDuration = computed(() => formatTime(duration.value))

    const togglePlay = () => {
      if (!video.value) return
      if (video.value.paused) {
        video.value.play()
      } else {
        video.value.pause()
      }
    }
    
    const updateProgress = () => {
      if (!video.value) return
      duration.value = video.value.duration || 0
      current.value = video.value.currentTime
      progress.value = duration.value ? (current.value / duration.value) * 100 : 0
      playing.value = !video.value.paused
    }
    
    const seek = (e) => {
      if (video.value) {
        video.value.currentTime = calculateSeekPosition(e, duration.value)
      }
    }
    
    const toggleMute = () => {
      muted.value = !muted.value
      if (video.value) video.value.muted = muted.value
    }
    
    const handleFullscreen = () => {
      toggleFullscreen(video.value?.parentElement)
    }

    watch(volume, (v) => { if (video.value) video.value.volume = v })
    const onEnded = () => { playing.value = false }

    onMounted(() => {
      if (video.value) {
        video.value.volume = volume.value
        video.value.muted = muted.value
        video.value.loop = props.loop
        if (props.autoplay) video.value.play()
      }
    })

    return { 
      video, playing, progress, togglePlay, updateProgress, seek, 
      volume, muted, toggleMute, handleFullscreen, 
      formattedCurrent, formattedDuration, onEnded, messages
    }
  }
}
</script>

<style src="./style.css"></style>
