// packages/react/src/components/Form/FormGroup.jsx
import React from 'react'
import './style.css'
import { getFormGroupClasses } from './utils.js'

const FormGroup = ({
  row = false,
  spacing = 'normal', // compact | normal | comfortable
  className = '',
  style = {},
  children,
  ...props
}) => {
  const classes = [
    'form-group',
    row && 'form-group--row',
    spacing === 'compact' && 'form-group--spacing-compact',
    spacing === 'comfortable' && 'form-group--spacing-comfortable',
    className
  ].filter(Boolean).join(' ')

  return (
    <div className={classes} style={style} {...props}>
      {children}
    </div>
  )
}

FormGroup.displayName = 'FormGroup'

export default FormGroup

// packages/vue/src/components/Form/FormGroup.vue
<template>
  <div
    class="form-group"
    :class="formGroupClasses"
  >
    <slot />
  </div>
</template>

<script setup>
import { computed } from 'vue'
import './style.css'

const props = defineProps({
  row: {
    type: Boolean,
    default: false
  },
  spacing: {
    type: String,
    default: 'normal',
    validator: (value) => ['compact', 'normal', 'comfortable'].includes(value)
  }
})

const formGroupClasses = computed(() => {
  const classes = []
  
  if (props.row) {
    classes.push('form-group--row')
  }
  
  if (props.spacing === 'compact') {
    classes.push('form-group--spacing-compact')
  } else if (props.spacing === 'comfortable') {
    classes.push('form-group--spacing-comfortable')
  }
  
  return classes
})
</script>
