// packages/react/src/components/SlideOver/SlideOver.jsx
import React, { useCallback, useRef } from 'react'
import { Portal, useOverlayLayer } from '../../interactions.jsx'
import './style.css'

/**
 * SlideOver (React)
 * 侧滑面板，支持左右方向、宽度自定义。
 */
const SlideOver = ({ open = false, onClose = () => {}, placement = 'right', width = 400, children, header, footer }) => {
  const panelRef = useRef(null)

  const handleClose = useCallback(() => {
    onClose?.()
  }, [onClose])

  useOverlayLayer({
    open,
    elementRef: panelRef,
    modal: true,
    lockScroll: true,
    restoreFocus: true,
    initialFocus: true,
    closeOnEscape: true,
    closeOnPointerDownOutside: false,
    onEscapeKeyDown: handleClose,
    zIndex: 3000,
  })

  return (
    <Portal>
      {open ? (
        <div className="wc-slideover-wrapper">
          <div className="wc-slideover-overlay" onClick={handleClose} />
          <div
            ref={panelRef}
            className={`wc-slideover-panel wc-slideover-${placement}`}
            style={{ width: typeof width === 'number' ? `${width}px` : width }}
            role="dialog"
            aria-modal="true"
            tabIndex={-1}
          >
            {header && <header className="wc-slideover-header">{header}</header>}
            <div className="wc-slideover-body">{children}</div>
            {footer && <footer className="wc-slideover-footer">{footer}</footer>}
            <button className="wc-slideover-close" type="button" onClick={handleClose} aria-label="关闭">
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M6 6l12 12M18 6 6 18" />
              </svg>
            </button>
          </div>
        </div>
      ) : null}
    </Portal>
  )
}

export default SlideOver

// packages/vue/src/components/SlideOver/SlideOver.vue
<template>
  <teleport to="body">
    <transition name="slideover">
      <div
        v-if="model"
        class="wc-slideover-wrapper"
        tabindex="-1"
        @keydown.esc="close"
      >
        <div
          class="wc-slideover-overlay"
          @click="close"
        />
        <div
          ref="panelRef"
          class="wc-slideover-panel"
          :class="[`wc-slideover-${placement}`]"
          :style="panelStyle"
          role="dialog"
          aria-modal="true"
          tabindex="-1"
        >
          <header
            v-if="$slots.header"
            class="wc-slideover-header"
          >
            <slot name="header" />
          </header>
          <div class="wc-slideover-body">
            <slot />
          </div>
          <footer
            v-if="$slots.footer"
            class="wc-slideover-footer"
          >
            <slot name="footer" />
          </footer>
          <button
            class="wc-slideover-close"
            type="button"
            aria-label="关闭"
            @click="close"
          >
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="M6 6l12 12M18 6 6 18" />
            </svg>
          </button>
        </div>
      </div>
    </transition>
  </teleport>
</template>

<script>
import { computed, ref, watch } from 'vue'
import { useOverlayLayer } from '../../interactions'
import './style.css'
export default {
  name: 'SlideOver',
  props: {
    modelValue: {
      type: Boolean,
      default: false
    },
    placement: {
      type: String,
      default: 'right',
      validator: (v) => ['left', 'right'].includes(v)
    },
    width: {
      type: [String, Number],
      default: '400px'
    }
  },
  emits: ['update:modelValue', 'open', 'close'],
  setup(props, { emit }) {
    const panelRef = ref(null)

    const model = computed({
      get: () => props.modelValue,
      set: (v) => emit('update:modelValue', v)
    })
    const close = () => {
      model.value = false
      emit('close')
    }
    const panelStyle = computed(() => ({ width: typeof props.width === 'number' ? props.width + 'px' : props.width }))

    useOverlayLayer({
      open: model,
      elementRef: panelRef,
      modal: true,
      lockScroll: true,
      restoreFocus: true,
      initialFocus: true,
      closeOnEscape: true,
      closeOnPointerDownOutside: false,
      onEscapeKeyDown: close,
      zIndex: 3000
    })

    watch(() => props.modelValue, (open) => {
      if (open) {
        emit('open')
      }
    }, { immediate: true })

    return { model, close, panelStyle, panelRef }
  }
}
</script>
