// packages/vue/src/components/Button/Button.vue
<template>
  <button
    :class="buttonClasses"
    :disabled="disabled || loading"
    :type="type"
    :style="buttonStyles"
    @click="handleClick"
    @mouseover="handleMouseOver"
    @mouseout="handleMouseOut"
    @focus="handleFocus"
    @blur="handleBlur"
  >
    <span
      v-if="loading"
      class="wc-btn__loading"
    >
      <svg
        class="animate-spin h-4 w-4"
        fill="none"
        viewBox="0 0 24 24"
      >
        <circle
          class="opacity-25"
          cx="12"
          cy="12"
          r="10"
          stroke="currentColor"
          stroke-width="4"
        />
        <path
          class="opacity-75"
          fill="currentColor"
          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
        />
      </svg>
    </span>
    <span
      v-if="startIcon && !loading"
      class="wc-btn__start-icon"
    >
      <slot name="startIcon">{{ startIcon }}</slot>
    </span>
    <span
      class="wc-btn__content"
      :class="{ 'opacity-0': loading }"
    >
      <slot />
    </span>
    <span
      v-if="endIcon && !loading"
      class="wc-btn__end-icon"
    >
      <slot name="endIcon">{{ endIcon }}</slot>
    </span>
  </button>
</template>

<script setup>
import { computed } from 'vue'
import {
  isValidVariant,
  isValidSize,
  isValidType,
  isValidRounded,
  isValidButtonStyle,
  getButtonClasses,
  handleButtonClick as utilHandleButtonClick
} from './utils.js'
import './style.css'

const props = defineProps({
  variant: {
    type: String,
    default: 'primary',
    validator: isValidVariant
  },
  buttonStyle: {
    type: String,
    default: 'default',
    validator: isValidButtonStyle
  },
  size: {
    type: String,
    default: 'md',
    validator: isValidSize
  },
  disabled: {
    type: Boolean,
    default: false
  },
  loading: {
    type: Boolean,
    default: false
  },
  fullWidth: {
    type: Boolean,
    default: false
  },
  type: {
    type: String,
    default: 'button',
    validator: isValidType
  },
  href: {
    type: String,
    default: null
  },
  target: {
    type: String,
    default: '_self'
  },
  startIcon: {
    type: String,
    default: null
  },
  endIcon: {
    type: String,
    default: null
  },
  rounded: {
    type: [Boolean, String],
    default: true,
    validator: isValidRounded
  },
  uppercase: {
    type: Boolean,
    default: false
  },
  ripple: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['click', 'mouseover', 'mouseout', 'focus', 'blur'])

const buttonClasses = computed(() => getButtonClasses(props))

const buttonStyles = computed(() => ({}))

const handleClick = (event) => {
  utilHandleButtonClick({
    event,
    disabled: props.disabled,
    loading: props.loading,
    href: props.href,
    target: props.target,
    onClick: (e) => emit('click', e)
  })
}

const handleMouseOver = (event) => {
  emit('mouseover', event)
}

const handleMouseOut = (event) => {
  emit('mouseout', event)
}

const handleFocus = (event) => {
  emit('focus', event)
}

const handleBlur = (event) => {
  emit('blur', event)
}
</script>

// packages/react/src/components/Button/Button.jsx
import React from 'react'
import './style.css'
import {
  validVariants,
  getButtonClasses,
  handleButtonClick as utilHandleButtonClick
} from './utils.js'

const Button = ({
  children,
  variant = 'primary',
  buttonStyle = 'default',
  size = 'md',
  disabled = false,
  loading = false,
  fullWidth = false,
  type = 'button',
  href = null,
  target = '_self',
  startIcon = null,
  endIcon = null,
  rounded = true,
  uppercase = false,
  ripple = true,
  onClick,
  onMouseOver,
  onMouseOut,
  onFocus,
  onBlur,
  className = '',
  style = {},
  ...props
}) => {
  // 构建CSS类名
  const buttonClasses = getButtonClasses({
    variant,
    buttonStyle,
    size,
    disabled,
    loading,
    fullWidth,
    uppercase,
    rounded
  }).concat(className).filter(Boolean).join(' ')

  // 构建内联样式
  const buttonStyles = {
    ...style
  }

  const handleClick = (event) => {
    utilHandleButtonClick({
      event,
      disabled,
      loading,
      href,
      target,
      onClick
    })
  }

  const handleMouseOver = (event) => {
    onMouseOver?.(event)
  }

  const handleMouseOut = (event) => {
    onMouseOut?.(event)
  }

  const handleFocus = (event) => {
    onFocus?.(event)
  }

  const handleBlur = (event) => {
    onBlur?.(event)
  }

  const LoadingIcon = () => (
    <span className="wc-btn__loading">
      <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
    </span>
  )

  return (
    <button
      className={buttonClasses}
      disabled={disabled || loading}
      type={type}
      style={buttonStyles}
      onClick={handleClick}
      onMouseOver={handleMouseOver}
      onMouseOut={handleMouseOut}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      {loading && <LoadingIcon />}
      {startIcon && !loading && (
        <span className="wc-btn__start-icon">{startIcon}</span>
      )}
      <span className={`wc-btn__content ${loading ? 'opacity-0' : ''}`}>
        {children}
      </span>
      {endIcon && !loading && (
        <span className="wc-btn__end-icon">{endIcon}</span>
      )}
    </button>
  )
}

Button.displayName = 'Button'

export default Button
