// src/components/Banner/Banner.jsx
import React, { useState } from 'react'
import { 
  getBannerClasses, 
  getBannerIcon, 
  getBannerStyles,
  handleBannerClose,
  handleBannerAction
} from './utils.js'
import './style.css'

/**
 * Banner 组件 (React 版)
 * @param {Object} props
 */
export default function Banner({
  type = 'info',
  position = 'top',
  title = '',
  message = '',
  closable = true,
  showIcon = true,
  showDefaultAction = false,
  actionText = '立即行动',
  sticky = true,
  zIndex = 1000,
  onClose,
  onAction,
  children,
}) {
  const [visible, setVisible] = useState(true)
  if (!visible) return null

  const bannerClasses = getBannerClasses(type, position, sticky)
  const bannerStyles = getBannerStyles(zIndex)
  const iconContent = getBannerIcon(type)

  const handleClose = () => {
    handleBannerClose(setVisible, onClose)
  }

  const handleAction = () => {
    handleBannerAction(onAction)
  }

  return (
    <div
      className={bannerClasses}
      style={bannerStyles}
    >
      <div className="wc-banner-content">
        {showIcon && (
          <div className="wc-banner-icon">
            {iconContent}
          </div>
        )}
        <div className="wc-banner-text">
          {title && <div className="wc-banner-title">{title}</div>}
          <div className="wc-banner-message">{children || message}</div>
        </div>
        {(children && children.actions) || showDefaultAction ? (
          <div className="wc-banner-actions">
            {children && children.actions ? (
              children.actions
            ) : (
              <button
                onClick={handleAction}
                className="wc-banner-action-btn"
              >
                {actionText}
              </button>
            )}
          </div>
        ) : null}
        {closable && (
          <button
            onClick={handleClose}
            className="wc-banner-close"
            aria-label="关闭"
          >
            ×
          </button>
        )}
      </div>
    </div>
  )
}

// src/components/Banner/Banner.vue
<template>
  <div
    v-if="visible"
    :class="bannerClasses"
    :style="bannerStyles"
  >
    <div class="wc-banner-content">
      <div v-if="showIcon" class="wc-banner-icon">
        <span v-html="iconContent"></span>
      </div>
      <div class="wc-banner-text">
        <div v-if="title" class="wc-banner-title">{{ title }}</div>
        <div class="wc-banner-message">
          <slot>{{ message }}</slot>
        </div>
      </div>
      <div v-if="$slots.actions || showDefaultAction" class="wc-banner-actions">
        <slot name="actions">
          <button
            v-if="showDefaultAction"
            @click="handleAction"
            class="wc-banner-action-btn"
            type="button"
          >
            {{ actionText }}
          </button>
        </slot>
      </div>
      <button
        v-if="closable"
        @click="handleClose"
        class="wc-banner-close"
        type="button"
        aria-label="关闭"
      >
        ×
      </button>
    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { 
  isValidType, 
  isValidPosition,
  getBannerClasses,
  getBannerIcon,
  getBannerStyles,
  handleBannerClose,
  handleBannerAction
} from './utils.js'
import './style.css'

const props = defineProps({
  type: {
    type: String,
    default: 'info',
    validator: isValidType
  },
  position: {
    type: String,
    default: 'top',
    validator: isValidPosition
  },
  title: {
    type: String,
    default: ''
  },
  message: {
    type: String,
    default: ''
  },
  closable: {
    type: Boolean,
    default: true
  },
  showIcon: {
    type: Boolean,
    default: true
  },
  showDefaultAction: {
    type: Boolean,
    default: false
  },
  actionText: {
    type: String,
    default: '立即行动'
  },
  sticky: {
    type: Boolean,
    default: true
  },
  zIndex: {
    type: Number,
    default: 1000
  }
})

const emit = defineEmits(['close', 'action'])

const visible = ref(true)

const bannerClasses = computed(() => getBannerClasses(props.type, props.position, props.sticky))

const bannerStyles = computed(() => getBannerStyles(props.zIndex))

const iconContent = computed(() => getBannerIcon(props.type))

const handleClose = () => {
  handleBannerClose((value) => { visible.value = value }, () => emit('close'))
}

const handleAction = () => {
  handleBannerAction(() => emit('action'))
}
</script>
